services:
  - type: web
    name: hospital-standards-challenge
    runtime: node
    buildCommand: npm install && npm run build && cp server/table.sql dist/table.sql
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
