import { useState } from "react";
import { useLocation } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft, BarChart3, TrendingUp, GraduationCap, BrainCircuit,
  Users, Building2, Stethoscope, ChevronRight, ShieldCheck,
  ClipboardList, FileText, Lock, AlertTriangle, ShieldAlert, Bot, Globe, Briefcase,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { useQuery } from "@tanstack/react-query";
import { LEADERSHIP_LABELS } from "@shared/schema";

const LEADERSHIP_RANK: Record<string, number> = {
  learner: 0, educator: 1, director: 2, ceo: 3, admin: 4, super_admin: 5,
};

const BYPASS_ACCOUNTS = ["akshaysaluja", "rsaluja"];

function getEffectiveRole(user: { isAdmin: boolean; leadershipRole?: string | null; username?: string }) {
  if (BYPASS_ACCOUNTS.includes(user.username ?? "")) return "super_admin";
  const lr = (user.leadershipRole as string) || "learner";
  if (user.isAdmin && (LEADERSHIP_RANK[lr] ?? 0) < LEADERSHIP_RANK["admin"]) return "admin";
  return lr;
}

interface ConsoleCard {
  id: string;
  title: string;
  description: string;
  icon: React.ElementType;
  iconBg: string;
  iconColor: string;
  href: string;
  minRole: string;
  badge?: string;
}

const CONSOLE_CARDS: ConsoleCard[] = [
  {
    id: "survey-readiness",
    title: "Survey Readiness Agent",
    description: "Live compliance score — all 132 AAAHC standards tracked, color-coded by surveyor risk. Green above 90%, amber 75–90%, red below 75%.",
    icon: ShieldCheck,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-600",
    href: "/survey-readiness",
    minRole: "director",
    badge: "Live",
  },
  {
    id: "content-intelligence",
    title: "Content Intelligence Agent",
    description: "Upload a policy document and AI reads it, tags AAAHC standards, generates quiz questions, flags conflicts, and creates a mini-training module ready for one-click approval.",
    icon: Bot,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/survey-readiness",
    minRole: "director",
    badge: "AI",
  },
  {
    id: "compliance-tasks",
    title: "Compliance Task Manager",
    description: "View, assign, and track all compliance tasks by status — pending, in progress, completed, and overdue. Create new tasks manually or review tasks generated by the AI agents. Overdue tasks auto-escalate.",
    icon: ClipboardList,
    iconBg: "bg-sky-500/10",
    iconColor: "text-sky-600",
    href: "/compliance-tasks",
    minRole: "director",
    badge: "Tool",
  },
  {
    id: "executive-brief",
    title: "Executive Readiness Agent",
    description: "Generates a weekly plain-English compliance brief for CEOs and CNOs. Combines readiness scores, overdue items, expiring documents, and staff training gaps into a one-page summary with trend direction. Delivers via email.",
    icon: Briefcase,
    iconBg: "bg-emerald-500/10",
    iconColor: "text-emerald-600",
    href: "/executive-brief",
    minRole: "ceo",
    badge: "Agent",
  },
  {
    id: "regulatory-watch",
    title: "Regulatory Watch Agent",
    description: "Monitors AAAHC and Joint Commission standards pages for updates and new requirements. Flags affected compliance items, creates review tasks, and alerts your compliance officer automatically.",
    icon: Globe,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/regulatory-watch",
    minRole: "director",
    badge: "Agent",
  },
  {
    id: "staff-learning",
    title: "Staff Learning Agent",
    description: "Maps quiz completions to AAAHC compliance items. Identifies staff with training gaps, fires targeted reminders, and escalates to managers when anyone is 14+ days overdue.",
    icon: GraduationCap,
    iconBg: "bg-blue-500/10",
    iconColor: "text-blue-600",
    href: "/staff-learning",
    minRole: "director",
    badge: "Agent",
  },
  {
    id: "executive-report",
    title: "Executive Readiness Report",
    description: "Facility-wide readiness scores, trend charts, and guided education plan status with CSV/PDF export.",
    icon: TrendingUp,
    iconBg: "bg-primary/10",
    iconColor: "text-primary",
    href: "/executive-report",
    minRole: "director",
    badge: "Exec",
  },
  {
    id: "user-management",
    title: "User Management",
    description: "View all registered learners, track engagement and accuracy, and assign leadership roles.",
    icon: Users,
    iconBg: "bg-chart-2/10",
    iconColor: "text-chart-2",
    href: "/admin",
    minRole: "director",
  },
  {
    id: "guided-education",
    title: "Guided Education Oversight",
    description: "Monitor active remediation plans, track overdue assignments, and verify supervisor sign-offs.",
    icon: GraduationCap,
    iconBg: "bg-violet-500/10",
    iconColor: "text-violet-600",
    href: "/corrective-actions",
    minRole: "director",
  },
  {
    id: "ai-coach",
    title: "AI Leadership Coach",
    description: "AI-generated readiness summaries, staff performance insights, and recommended focus areas.",
    icon: BrainCircuit,
    iconBg: "bg-chart-4/10",
    iconColor: "text-chart-4",
    href: "/admin",
    minRole: "director",
    badge: "AI",
  },
];

interface TeamRiskEntry {
  id: number;
  userId: number;
  username: string;
  firstName: string;
  lastName: string;
  department: string | null;
  riskAreas: string;
  notes: string;
  updatedAt: string;
}

function TeamRiskSummary({ module }: { module: string }) {
  const { data, isLoading } = useQuery<{ assessments: TeamRiskEntry[] }>({
    queryKey: ["/api/risk-assessment/team", module],
    queryFn: () => fetch(`/api/risk-assessment/team?module=${module}`, { credentials: "include" }).then(r => r.json()),
  });

  const [expanded, setExpanded] = useState(false);

  const assessments = data?.assessments ?? [];

  const riskFrequency = (() => {
    const freq: Record<string, number> = {};
    for (const a of assessments) {
      try {
        const areas = JSON.parse(a.riskAreas) as string[];
        for (const area of areas) {
          freq[area] = (freq[area] || 0) + 1;
        }
      } catch {}
    }
    return Object.entries(freq).sort((a, b) => b[1] - a[1]).slice(0, 8);
  })();

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-2xl border border-border bg-card overflow-hidden"
      data-testid="card-team-risk-summary"
    >
      <button
        className="w-full flex items-center gap-3 px-5 py-4 text-left hover:bg-muted/20 transition-colors"
        onClick={() => setExpanded(v => !v)}
        data-testid="button-toggle-team-risks"
      >
        <div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center flex-shrink-0">
          <ShieldAlert size={18} className="text-orange-500" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <h2 className="font-bold text-sm">Team Risk Self-Assessments</h2>
            {assessments.length > 0 && (
              <span className="px-1.5 py-0.5 rounded-full text-xs font-black bg-orange-500/15 text-orange-500 border border-orange-500/20">
                {assessments.length} submitted
              </span>
            )}
          </div>
          <p className="text-sm text-muted-foreground mt-0.5">Staff-identified risk areas across your facility</p>
        </div>
        {expanded
          ? <ChevronRight size={16} className="text-muted-foreground rotate-90 transition-transform" />
          : <ChevronRight size={16} className="text-muted-foreground transition-transform" />}
      </button>

      <AnimatePresence initial={false}>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="border-t border-border/40 px-5 pb-5 pt-4 flex flex-col gap-5">
              {isLoading ? (
                <div className="flex items-center justify-center py-8">
                  <div className="w-5 h-5 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                </div>
              ) : assessments.length === 0 ? (
                <div className="rounded-xl border border-dashed border-border bg-muted/20 p-5 text-center">
                  <ShieldAlert size={20} className="text-muted-foreground mx-auto mb-2" />
                  <p className="text-sm font-semibold text-muted-foreground">No assessments submitted yet</p>
                  <p className="text-xs text-muted-foreground mt-1">Staff can complete their self-assessment from their training dashboard.</p>
                </div>
              ) : (
                <>
                  {/* Most common risk areas */}
                  {riskFrequency.length > 0 && (
                    <div className="flex flex-col gap-2">
                      <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Most flagged risk areas</p>
                      <div className="flex flex-col gap-2">
                        {riskFrequency.map(([area, count], i) => {
                          const pct = Math.round((count / assessments.length) * 100);
                          return (
                            <div key={area} className="flex items-center gap-2" data-testid={`row-risk-freq-${i}`}>
                              <div className="flex-1 min-w-0">
                                <div className="flex items-center justify-between gap-2 mb-0.5">
                                  <span className="text-xs font-semibold truncate">{area}</span>
                                  <span className="text-xs font-bold text-orange-500 flex-shrink-0">{count} staff</span>
                                </div>
                                <div className="h-1.5 rounded-full bg-muted overflow-hidden">
                                  <div
                                    className="h-full rounded-full bg-orange-500/70"
                                    style={{ width: `${pct}%` }}
                                  />
                                </div>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  )}

                  {/* Individual submissions */}
                  <div className="flex flex-col gap-2">
                    <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Individual submissions</p>
                    <div className="flex flex-col gap-2">
                      {assessments.map((a) => {
                        let areas: string[] = [];
                        try { areas = JSON.parse(a.riskAreas) as string[]; } catch {}
                        const displayName = (a.firstName || a.lastName)
                          ? `${a.firstName} ${a.lastName}`.trim()
                          : a.username;
                        return (
                          <div
                            key={a.id}
                            className="rounded-xl border border-border bg-background p-3 flex flex-col gap-1.5"
                            data-testid={`row-team-risk-${a.userId}`}
                          >
                            <div className="flex items-center gap-2">
                              <div className="w-6 h-6 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                                <span className="text-[10px] font-black text-primary">
                                  {displayName.charAt(0).toUpperCase()}
                                </span>
                              </div>
                              <span className="text-xs font-bold">{displayName}</span>
                              {a.department && (
                                <span className="text-[10px] text-muted-foreground font-semibold">{a.department}</span>
                              )}
                            </div>
                            <div className="flex flex-wrap gap-1.5">
                              {areas.map((area, i) => (
                                <span
                                  key={i}
                                  className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-orange-500/8 text-orange-600 dark:text-orange-400 border border-orange-500/20"
                                >
                                  {area}
                                </span>
                              ))}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function LeadershipHubPage() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();

  const effectiveRole = user ? getEffectiveRole(user) : "learner";
  const effectiveRank = LEADERSHIP_RANK[effectiveRole] ?? 0;

  const isAsc = user?.organizationType === "asc";
  const moduleLabel = isAsc ? "ASC" : "Hospital";
  const ModuleIcon = isAsc ? Stethoscope : Building2;

  const leadershipLabel = user
    ? (LEADERSHIP_LABELS as Record<string, string>)[effectiveRole] ?? effectiveRole
    : "—";

  const canAccess = (card: ConsoleCard) =>
    effectiveRank >= (LEADERSHIP_RANK[card.minRole] ?? 99);

  const isBypass = BYPASS_ACCOUNTS.includes(user?.username ?? "");
  const needsMfa = !isBypass && effectiveRank >= LEADERSHIP_RANK["ceo"];
  const { data: mfaStatus } = useQuery<{ required: boolean; enabled: boolean; verified: boolean }>({
    queryKey: ["/api/mfa/status"],
    enabled: needsMfa,
  });

  return (
    <div className="min-h-screen pb-20">
      {/* Sub-header */}
      <div className="sticky top-[58px] z-40 border-b border-border bg-background/95 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-6 py-3 flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setLocation("/")}
            data-testid="button-back-to-training"
            aria-label="Back to training"
          >
            <ArrowLeft size={20} />
          </Button>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <h1 className="font-bold text-base text-foreground">Leadership Console</h1>
              <span
                className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-bold bg-primary/10 text-primary border border-primary/20"
                data-testid="badge-module-scope"
              >
                <ModuleIcon size={11} />
                {moduleLabel}
              </span>
            </div>
            <p className="text-sm font-medium text-foreground/70" data-testid="text-role-label">
              {leadershipLabel} · facility-scoped view
            </p>
          </div>
          <div className="flex items-center gap-1.5 flex-shrink-0">
            <ShieldCheck size={14} className="text-primary" />
            <span className="text-xs font-semibold text-primary hidden sm:inline">Secured</span>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-5xl mx-auto px-6 pt-8 flex flex-col gap-8">

        {/* MFA setup banner for ceo+ users */}
        {needsMfa && mfaStatus && !mfaStatus.enabled && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border-2 border-orange-500/60 bg-orange-50 dark:bg-orange-500/15 p-5 flex items-start gap-4"
            data-testid="banner-mfa-setup"
          >
            <div className="w-10 h-10 rounded-xl bg-orange-500/20 flex items-center justify-center flex-shrink-0">
              <AlertTriangle size={20} className="text-orange-600 dark:text-orange-400" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-sm mb-1 text-foreground">Two-Factor Authentication Required</h2>
              <p className="text-sm text-foreground/80 leading-relaxed mb-3">
                Your role requires MFA to access reporting tools. Set up your authenticator app now to unlock the Executive Report, AI Coach, and data exports.
              </p>
              <Button size="sm" onClick={() => setLocation("/mfa-setup")} data-testid="button-setup-mfa-from-hub">
                Set Up MFA Now
              </Button>
            </div>
          </motion.div>
        )}

        {/* MFA verify banner — set up but not verified this session */}
        {needsMfa && mfaStatus?.enabled && !mfaStatus.verified && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-2xl border-2 border-primary/50 bg-primary/8 p-5 flex items-start gap-4"
            data-testid="banner-mfa-verify"
          >
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
              <ShieldCheck size={20} className="text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <h2 className="font-bold text-sm mb-1">Verify Your Identity</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                Enter your authenticator code to access reporting tools for this session.
              </p>
              <Button size="sm" onClick={() => setLocation("/mfa-verify")} data-testid="button-verify-mfa-from-hub">
                Enter Code
              </Button>
            </div>
          </motion.div>
        )}

        {/* Scope banner */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className="rounded-2xl border border-border bg-card p-5 flex items-start gap-4"
          data-testid="card-scope-info"
        >
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
            <BarChart3 size={20} className="text-primary" />
          </div>
          <div className="min-w-0">
            <h2 className="font-bold text-sm mb-1">Your data scope</h2>
            <p className="text-sm text-muted-foreground leading-relaxed" data-testid="text-scope-description">
              {effectiveRole === "super_admin" || effectiveRole === "admin"
                ? "You have platform-wide access. All facilities and modules are visible."
                : effectiveRole === "ceo"
                  ? `You are viewing ${moduleLabel} data for your assigned facility with executive-level access including data exports and audit logs.`
                  : effectiveRole === "director"
                    ? `You are viewing ${moduleLabel} data for your assigned facility. Contact a system admin to request multi-site access.`
                    : effectiveRole === "educator"
                      ? `You can review completion and manage Guided Education Plans for learners in your department (${moduleLabel}).`
                      : "Your access level does not include leadership tools."}
            </p>
          </div>
        </motion.div>

        {/* Facility scoping note for hospital/ASC separation */}
        {(effectiveRole === "admin" || effectiveRole === "super_admin") && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            className="rounded-xl border border-orange-500/50 bg-orange-50 dark:bg-orange-500/10 px-4 py-3 flex items-center gap-2 text-sm text-foreground/80"
            data-testid="banner-multi-module"
          >
            <ClipboardList size={15} className="flex-shrink-0 text-orange-500" />
            <span>
              <strong>Multi-module admin:</strong> Hospital and ASC data are segregated. Use the pathway switcher on the learner dashboard to change your active module context.
            </span>
          </motion.div>
        )}

        {/* Console cards */}
        <div>
          <h2 className="text-sm font-bold uppercase tracking-wider text-foreground/60 mb-4" data-testid="text-tools-label">
            Leadership Tools
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {CONSOLE_CARDS.map((card, i) => {
              const accessible = canAccess(card);
              const Icon = card.icon;
              return (
                <motion.div
                  key={card.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.06 }}
                  data-testid={`card-console-${card.id}`}
                  className={`rounded-2xl border-2 p-5 flex flex-col gap-3 transition-all ${
                    accessible
                      ? "border-border bg-card hover:border-primary/40 hover:shadow-md cursor-pointer"
                      : "border-border/60 bg-muted/30 opacity-75 cursor-not-allowed"
                  }`}
                  onClick={() => accessible && setLocation(card.href)}
                >
                  <div className="flex items-start gap-3">
                    <div className={`w-10 h-10 rounded-xl ${card.iconBg} flex items-center justify-center flex-shrink-0`}>
                      {accessible
                        ? <Icon size={20} className={card.iconColor} />
                        : <Lock size={18} className="text-muted-foreground" />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <h3 className="font-bold text-sm leading-tight" data-testid={`text-card-title-${card.id}`}>
                          {card.title}
                        </h3>
                        {card.badge && accessible && (
                          <span className={`px-1.5 py-0.5 rounded text-xs font-black uppercase tracking-wider ${card.iconBg} ${card.iconColor}`}>
                            {card.badge}
                          </span>
                        )}
                        {!accessible && (
                          <span className="px-1.5 py-0.5 rounded text-xs font-bold uppercase tracking-wider bg-muted text-muted-foreground">
                            Restricted
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                        {card.description}
                      </p>
                    </div>
                  </div>
                  {accessible && (
                    <div className="flex justify-end">
                      <span className={`inline-flex items-center gap-1 text-xs font-semibold ${card.iconColor}`}>
                        Open <ChevronRight size={13} />
                      </span>
                    </div>
                  )}
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Team Risk Summary */}
        <TeamRiskSummary module={isAsc ? "asc" : "hospital"} />

        {/* Permission summary */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="rounded-xl border border-border bg-card p-4"
          data-testid="card-permission-summary"
        >
          <h3 className="font-bold text-xs uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-1.5">
            <ShieldCheck size={13} />
            Access Summary
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
            {[
              { label: "Your Role", value: leadershipLabel, testid: "text-summary-role" },
              { label: "Module", value: moduleLabel, testid: "text-summary-module" },
              { label: "Scope", value: effectiveRank >= 3 ? "All Facilities" : "Own Facility", testid: "text-summary-scope" },
              { label: "Data Access", value: isAsc ? "ASC Only" : "Hospital Only", testid: "text-summary-data" },
            ].map(item => (
              <div key={item.label} className="flex flex-col gap-0.5">
                <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">{item.label}</span>
                <span className="text-sm font-bold" data-testid={item.testid}>{item.value}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Back to learning */}
        <div className="flex justify-center">
          <Button
            variant="outline"
            onClick={() => setLocation("/")}
            data-testid="button-back-to-learning"
            className="gap-2"
          >
            <ArrowLeft size={15} />
            Back to Training Dashboard
          </Button>
        </div>
      </div>
    </div>
  );
}
