import type { Level } from "./schema";
import { ascPatientRightsLevel } from "./asc-patient-rights";
import { ascInfectionPreventionLevel } from "./asc-infection-prevention";

export const ascLevels: Level[] = [
  ascPatientRightsLevel,
  {
    id: "asc_governance",
    module: "asc",
    draft: true,
    name: "Governance",
    description: "ASC domain: governing body structure, oversight, and accountability. Top-level container — no content yet.",
    icon: "Landmark",
    color: "hsl(255, 65%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "asc_administration",
    module: "asc",
    draft: true,
    name: "Administration",
    description: "ASC domain: organizational management, policies, personnel, and operations. Top-level container — no content yet.",
    icon: "Briefcase",
    color: "hsl(195, 75%, 45%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "asc_quality_of_care",
    module: "asc",
    draft: true,
    name: "Quality of Care",
    description: "ASC domain: clinical quality, patient assessment, and care delivery standards. Top-level container — no content yet.",
    icon: "HeartPulse",
    color: "hsl(345, 70%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "asc_clinical_records",
    module: "asc",
    draft: true,
    name: "Clinical Records",
    description: "ASC domain: clinical record content, documentation standards, and health information management. Top-level container — no content yet.",
    icon: "FileText",
    color: "hsl(165, 60%, 40%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "asc_anesthesia_surgery_services",
    module: "asc",
    draft: true,
    name: "Anesthesia and Surgery Services",
    description: "ASC domain: anesthesia services, surgical/procedural services, and perioperative care. Top-level container — no content yet.",
    icon: "Syringe",
    color: "hsl(15, 80%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  ascInfectionPreventionLevel,
  {
    id: "asc_facilities_environment",
    module: "asc",
    draft: true,
    name: "Facilities and Environment",
    description: "ASC domain: physical environment, life safety, equipment, utilities, and emergency preparedness. Top-level container — no content yet.",
    icon: "Building2",
    color: "hsl(35, 85%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "asc_medicare_conditions_for_coverage",
    module: "asc",
    draft: true,
    name: "Medicare Conditions for Coverage",
    description: "ASC domain: CMS Conditions for Coverage (42 CFR Part 416) compliance for Medicare-certified ASCs. Top-level container — no content yet.",
    icon: "Stamp",
    color: "hsl(220, 70%, 40%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
];
