import type { Level } from "./schema";

export const ascLevels: Level[] = [
  {
    id: "asc_surgical_safety",
    module: "asc",
    draft: true,
    name: "Surgical Safety & Universal Protocol",
    description: "Site marking, time-out, and the Universal Protocol in the ambulatory surgery center setting.",
    icon: "ShieldAlert",
    color: "hsl(0, 75%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Universal Protocol (Placeholder)",
        content: "Placeholder content. The Universal Protocol consists of preprocedure verification, site marking, and a documented time-out immediately before the procedure.",
        keyPoint: "Three Universal Protocol elements: verification, site marking, time-out.",
      },
    ],
    questions: [
      {
        id: "asc_ss_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Who must actively participate in the surgical time-out at an ASC?",
        options: [
          "Only the circulating nurse",
          "All members of the procedural team, who pause to actively participate",
          "Only the surgeon",
          "The receptionist via intercom",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. The time-out requires active participation from all team members.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_ss_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: When should the procedural site be marked?",
        options: [
          "After anesthesia induction",
          "Before the patient enters the procedure room, with the patient involved when possible",
          "Whenever the surgeon remembers",
          "Only for orthopedic cases",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Site marking occurs before the procedure with the patient involved.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_ss_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: A surgeon refuses to mark the site because the case is bilateral. What is the correct response?",
        options: [
          "Skip the site marking",
          "Mark both sides per Universal Protocol and document",
          "Mark only the side the surgeon will start with",
          "Cancel the case",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Bilateral cases still require site marking per protocol.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_ss_q4",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: A time-out reveals the consent form lists the wrong procedure. What must happen?",
        options: [
          "Proceed and update the consent later",
          "Stop and resolve the discrepancy before proceeding",
          "Have the surgeon sign for the patient",
          "Continue if the surgeon is confident",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Discrepancies must be resolved before proceeding.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "asc_anesthesia_safety",
    module: "asc",
    draft: true,
    name: "Anesthesia Safety",
    description: "Pre-anesthesia assessment, monitoring, and emergency airway readiness in the ASC.",
    icon: "HeartPulse",
    color: "hsl(340, 75%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Pre-Anesthesia Assessment (Placeholder)",
        content: "Placeholder content. A pre-anesthesia evaluation must be completed and documented prior to administration of anesthesia.",
        keyPoint: "Document pre-anesthesia evaluation before every case.",
      },
    ],
    questions: [
      {
        id: "asc_an_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: When must the pre-anesthesia evaluation be completed for an ASC patient?",
        options: [
          "After induction",
          "Before administration of the first dose of anesthesia",
          "At the post-op appointment",
          "Only for general anesthesia",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Pre-anesthesia evaluation must be completed and documented before anesthesia is administered.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_an_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Which equipment must be immediately available wherever moderate or deep sedation is administered?",
        options: [
          "Defibrillator and reversal agents only",
          "Oxygen, suction, age-appropriate airway equipment, monitoring, reversal agents, and resuscitative drugs",
          "Pulse oximeter only",
          "A working telephone only",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. A full set of resuscitation and monitoring equipment is required at the point of care.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_an_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: A post-anesthesia evaluation must be completed within what timeframe after recovery?",
        options: [
          "Within 7 days",
          "Within 48 hours after the procedure, by a qualified provider",
          "Only if the patient calls in with concerns",
          "Within 30 days",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. CMS Conditions for Coverage require post-anesthesia evaluation within 48 hours.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "asc_infection_prevention",
    module: "asc",
    draft: true,
    name: "Infection Prevention (Surgical)",
    description: "Sterile technique, instrument reprocessing, and surgical site infection prevention in the ASC.",
    icon: "Microscope",
    color: "hsl(152, 70%, 40%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Instrument Reprocessing (Placeholder)",
        content: "Placeholder content. All surgical instruments must be reprocessed per manufacturer instructions for use (IFU) with documented evidence.",
        keyPoint: "Follow manufacturer IFU for every instrument cycle.",
      },
    ],
    questions: [
      {
        id: "asc_ip_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Whose instructions must guide the reprocessing of surgical instruments at an ASC?",
        options: [
          "The surgeon's preference card",
          "The manufacturer's instructions for use (IFU)",
          "The vendor's marketing brochure",
          "The administrator's email memo",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Reprocessing must follow the manufacturer IFU.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_ip_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: How often must the sterilizer's biological indicator be tested for steam sterilization in the ASC?",
        options: [
          "Once per year",
          "At least weekly, and with every implant load",
          "Only when something goes wrong",
          "Only at recertification",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Biological indicator testing is at least weekly and with every implant load.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_ip_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Surgical attire in the OR semi-restricted area should include which of the following?",
        options: [
          "Street clothes are fine if covered by a lab coat",
          "Facility-laundered scrubs, head covering that covers the hair, and clean shoes/shoe covers",
          "Personal scrubs from home are preferred",
          "No specific requirements",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Surgical attire standards require facility-laundered scrubs and appropriate head covering.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
  {
    id: "asc_assessment_discharge",
    module: "asc",
    draft: true,
    name: "Patient Assessment & Discharge",
    description: "H&P, post-op assessment, discharge criteria, and responsible adult escort requirements.",
    icon: "ClipboardCheck",
    color: "hsl(210, 82%, 45%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "H&P Update (Placeholder)",
        content: "Placeholder content. A complete H&P must be in the chart, with an update completed and documented within 30 days of the procedure.",
        keyPoint: "H&P with update documented within 30 days.",
      },
    ],
    questions: [
      {
        id: "asc_ad_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: What is the maximum age of a History and Physical that may be used for an ASC procedure?",
        options: [
          "60 days, with no update",
          "30 days, with an update at the day of procedure",
          "1 year, with no update",
          "No timeframe is specified",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. CMS Conditions for Coverage require an H&P within 30 days with a same-day update.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_ad_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Which discharge requirement is specific to ASCs?",
        options: [
          "Patients may drive themselves home if they feel fine",
          "Patients receiving anesthesia must be discharged in the company of a responsible adult",
          "Patients must stay overnight",
          "Discharge instructions are optional",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Patients receiving anesthesia must be discharged with a responsible adult.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_ad_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Discharge criteria from PACU should be based on what?",
        options: [
          "The clock — fixed time after the case ends",
          "Documented physiological criteria such as the modified Aldrete score, met and recorded",
          "Whether the next patient is ready",
          "The surgeon's verbal okay only",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Discharge requires documented physiological criteria, not just elapsed time.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "asc_governance",
    module: "asc",
    draft: true,
    name: "Governance & Administration",
    description: "Governing body responsibilities, medical staff bylaws, and policy oversight in the ASC.",
    icon: "Scale",
    color: "hsl(280, 60%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Governing Body (Placeholder)",
        content: "Placeholder content. The ASC governing body is legally responsible for the conduct of the center, including quality of care.",
        keyPoint: "Governing body is legally responsible for the ASC.",
      },
    ],
    questions: [
      {
        id: "asc_gov_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Which body holds ultimate legal responsibility for the operation of an ASC?",
        options: [
          "The administrator",
          "The governing body",
          "The medical director only",
          "The accreditation surveyor",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. The governing body holds ultimate legal responsibility.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_gov_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: How often must the governing body review and approve major ASC policies?",
        options: [
          "Once at opening only",
          "At least annually, with documented evidence",
          "Only when staff request changes",
          "Only after a sentinel event",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Major policies must be reviewed at least annually.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_gov_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Medical staff bylaws for an ASC must address which of the following?",
        options: [
          "Marketing strategy",
          "Privileging, peer review, and standards of practice for the medical staff",
          "Patient parking only",
          "Only fee schedules",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Bylaws must define privileging, peer review, and standards of practice.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "asc_quality_risk",
    module: "asc",
    draft: true,
    name: "Quality & Risk Management",
    description: "Quality assessment and performance improvement (QAPI), adverse event reporting, and risk management in the ASC.",
    icon: "AlertTriangle",
    color: "hsl(35, 85%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "QAPI Program (Placeholder)",
        content: "Placeholder content. Each ASC must maintain an ongoing QAPI program that uses data, sets priorities, and acts on findings.",
        keyPoint: "Data-driven QAPI program that drives action.",
      },
    ],
    questions: [
      {
        id: "asc_qr_q1",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: Which event must be reported to the accrediting body and analyzed via root cause analysis?",
        options: [
          "A late start of a case",
          "A surgical site infection that occurs occasionally",
          "A wrong-site surgery or other sentinel event",
          "A patient who reschedules",
        ],
        correctIndex: 2,
        explanation: "Placeholder explanation. Sentinel events trigger reporting and root cause analysis.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "asc_qr_q2",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: What is the purpose of tracking transfers from the ASC to a hospital?",
        options: [
          "Marketing material",
          "Quality and safety monitoring — transfers are an indicator that may signal opportunities to improve",
          "There is no requirement to track them",
          "To bill the receiving hospital",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Transfer tracking is a required quality indicator for ASCs.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "asc_qr_q3",
        module: "asc",
        draft: true,
        question: "PLACEHOLDER: A patient develops a post-op infection 10 days after surgery. What is the ASC's responsibility?",
        options: [
          "Nothing — the patient is no longer at the ASC",
          "Capture the case in surveillance, investigate, and feed findings into QAPI",
          "Only inform the surgeon's private practice",
          "Refer the patient to a different ASC",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Post-discharge SSIs are part of surveillance and QAPI.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
];
