import type { Level } from "./schema";

export const clinicLevels: Level[] = [
  {
    id: "clinic_patient_rights",
    module: "clinic",
    draft: true,
    name: "Patient Rights",
    description: "Ambulatory Clinic domain: patient rights and responsibilities. Top-level container — no content yet.",
    icon: "ScrollText",
    color: "hsl(210, 82%, 45%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_governance",
    module: "clinic",
    draft: true,
    name: "Governance",
    description: "Ambulatory Clinic domain: governing body structure, oversight, and accountability. Top-level container — no content yet.",
    icon: "Landmark",
    color: "hsl(255, 65%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_administration",
    module: "clinic",
    draft: true,
    name: "Administration",
    description: "Ambulatory Clinic domain: organizational management, policies, personnel, and operations. Top-level container — no content yet.",
    icon: "Briefcase",
    color: "hsl(195, 75%, 45%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_quality_improvement",
    module: "clinic",
    draft: true,
    name: "Quality Improvement",
    description: "Ambulatory Clinic domain: performance measurement, peer review, and ongoing QI activities. Top-level container — no content yet.",
    icon: "TrendingUp",
    color: "hsl(280, 60%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_clinical_records",
    module: "clinic",
    draft: true,
    name: "Clinical Records",
    description: "Ambulatory Clinic domain: clinical record content, documentation standards, and health information management. Top-level container — no content yet.",
    icon: "FileText",
    color: "hsl(165, 60%, 40%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_infection_prevention_safety",
    module: "clinic",
    draft: true,
    name: "Infection Prevention and Safety",
    description: "Ambulatory Clinic domain: infection prevention practices, hand hygiene, device reprocessing, and patient safety. Top-level container — no content yet.",
    icon: "ShieldCheck",
    color: "hsl(152, 70%, 40%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
  {
    id: "clinic_facilities_environment",
    module: "clinic",
    draft: true,
    name: "Facilities and Environment",
    description: "Ambulatory Clinic domain: physical environment, life safety, equipment, utilities, and emergency preparedness. Top-level container — no content yet.",
    icon: "Building2",
    color: "hsl(35, 85%, 50%)",
    requiredScore: 0,
    studyMaterial: [],
    questions: [],
  },
];
