import type { Level } from "./schema";

export const clinicLevels: Level[] = [
  {
    id: "clinic_patient_rights",
    module: "clinic",
    draft: true,
    name: "Patient Rights & Responsibilities",
    description: "Outpatient clinic standards for informed consent, privacy, and patient grievance handling under Joint Commission AHC and AAAHC.",
    icon: "ScrollText",
    color: "hsl(210, 82%, 45%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Notice of Rights (Placeholder)",
        content: "Placeholder content. Clinics must provide patients a written notice of their rights at or before the first visit, in language they can understand.",
        keyPoint: "Patients receive a written notice of rights at first encounter.",
      },
      {
        title: "Informed Consent (Placeholder)",
        content: "Placeholder content. Informed consent must be documented for any procedure beyond routine examination, including risks, benefits, and alternatives.",
        keyPoint: "Document informed consent for all non-routine procedures.",
      },
    ],
    questions: [
      {
        id: "clinic_pr_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: When must an ambulatory clinic provide a patient with a written notice of patient rights?",
        options: [
          "At or before the first patient encounter",
          "Only when the patient asks for one",
          "Within 30 days of the first visit",
          "Only if the patient is admitted for observation",
        ],
        correctIndex: 0,
        explanation: "Placeholder explanation. Joint Commission AHC and AAAHC require that the notice of rights be provided at or before the first patient encounter.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_pr_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: Which of the following best describes documented informed consent in an outpatient clinic setting?",
        options: [
          "A signed acknowledgment that the patient was seen by a clinician",
          "A note in the chart that says 'consent obtained'",
          "Documentation of risks, benefits, alternatives, and the patient's agreement to proceed",
          "A verbal agreement witnessed by a single staff member",
        ],
        correctIndex: 2,
        explanation: "Placeholder explanation. Informed consent requires documented discussion of risks, benefits, alternatives, and the patient's agreement.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_pr_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A clinic patient files a formal grievance about a billing dispute. What is the clinic's accreditation obligation?",
        options: [
          "Forward the complaint to the billing vendor and close the file",
          "Acknowledge the grievance, investigate, and provide a written response within the timeframe defined in policy",
          "Wait until the patient escalates before responding",
          "Refer the patient to small claims court",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Accredited clinics must have a grievance process that acknowledges, investigates, and responds in writing.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "clinic_pr_q4",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A pediatric patient's parent refuses a recommended vaccination. What is the appropriate clinic response?",
        options: [
          "Discharge the family from the practice immediately",
          "Document the refusal, the education provided, and the parent's understanding of risks",
          "Administer the vaccine over the parent's objection if the clinician believes it is in the child's best interest",
          "Bill the parent for a separate refusal visit",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Refusals must be documented along with the education provided and confirmation of patient/guardian understanding.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "clinic_infection_control",
    module: "clinic",
    draft: true,
    name: "Infection Control (Outpatient)",
    description: "Hand hygiene, point-of-care device reprocessing, and outpatient-specific infection prevention practices.",
    icon: "ShieldCheck",
    color: "hsl(152, 70%, 40%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Hand Hygiene (Placeholder)",
        content: "Placeholder content. Hand hygiene is required before and after every patient contact, including non-touch encounters when entering the patient zone.",
        keyPoint: "Hand hygiene before and after every patient contact.",
      },
    ],
    questions: [
      {
        id: "clinic_ic_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A medical assistant uses the same finger-stick lancet device on two patients in the injection room. What is the violation?",
        options: [
          "No violation if the lancet tip was changed",
          "Single-patient-use lancet devices must never be shared between patients, even with a tip change",
          "Only a violation if blood was visible on the device",
          "Only a violation if both patients were diabetic",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Single-patient-use lancet devices may not be shared between patients under any circumstance.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "clinic_ic_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: How often should clinic staff perform hand hygiene during a routine patient encounter?",
        options: [
          "Only when leaving the room",
          "Before patient contact, before clean/aseptic tasks, after body fluid exposure risk, after patient contact, and after contact with patient surroundings",
          "Once per patient is sufficient",
          "Only when hands are visibly soiled",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. WHO 5 Moments for Hand Hygiene apply in outpatient settings.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_ic_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A clinic uses semi-critical reusable equipment (such as a vaginal probe). What level of reprocessing is required between patients?",
        options: [
          "Soap and water cleaning",
          "Low-level disinfection",
          "High-level disinfection or sterilization",
          "Wipe with alcohol",
        ],
        correctIndex: 2,
        explanation: "Placeholder explanation. Semi-critical equipment requires high-level disinfection or sterilization between patients.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "clinic_quality_improvement",
    module: "clinic",
    draft: true,
    name: "Quality Improvement",
    description: "Performance measurement, peer review, and ongoing quality improvement activities for ambulatory clinics.",
    icon: "TrendingUp",
    color: "hsl(280, 60%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "QI Program Basics (Placeholder)",
        content: "Placeholder content. Clinics must maintain an active quality improvement program with measurable goals reviewed at least annually.",
        keyPoint: "QI program with measurable goals reviewed annually.",
      },
    ],
    questions: [
      {
        id: "clinic_qi_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: How often should a clinic's QI plan and goals be formally reviewed?",
        options: [
          "Only when the surveyor visits",
          "At least annually, with documented evidence of review",
          "Once at the time of accreditation, then never again",
          "Only after a sentinel event",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. QI plans require documented review at least annually.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_qi_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: Which of the following best represents a measurable QI goal?",
        options: [
          "Improve patient satisfaction",
          "Reduce no-show appointment rate from 18% to 12% within 12 months",
          "Make sure staff feel happy",
          "Be a great clinic",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Measurable goals include a baseline, target, and timeframe.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_qi_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A peer review process for clinic providers should include which element?",
        options: [
          "Self-rating only",
          "Periodic review of clinical care by qualified peers using defined criteria",
          "Patient satisfaction surveys only",
          "Annual financial review",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Peer review must use qualified peers and defined clinical criteria.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "clinic_environment_of_care",
    module: "clinic",
    draft: true,
    name: "Environment of Care",
    description: "Life safety, medical equipment management, hazardous materials, and utilities in the clinic setting.",
    icon: "Building2",
    color: "hsl(35, 85%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Life Safety (Placeholder)",
        content: "Placeholder content. Egress paths must be unobstructed, and fire extinguishers must be inspected monthly with documented evidence.",
        keyPoint: "Egress clear; extinguishers inspected monthly.",
      },
    ],
    questions: [
      {
        id: "clinic_eoc_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A surveyor finds storage boxes stacked in the hallway leading to the rear exit. What is the citation?",
        options: [
          "No citation if the hallway is wide enough",
          "Egress paths must remain unobstructed at all times",
          "Citation only if the boxes are flammable",
          "Citation only after a fire drill is failed",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Means of egress must remain clear of all obstructions.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_eoc_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: How often must portable fire extinguishers be visually inspected?",
        options: [
          "Annually",
          "Monthly",
          "Every five years",
          "Only after they are used",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Visual inspections of portable extinguishers are required monthly.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_eoc_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A clinic stores oxygen cylinders in an exam room. What is the standard?",
        options: [
          "Cylinders may be free-standing as long as they are out of foot traffic",
          "Cylinders must be secured upright in a stand or rack to prevent falling",
          "Cylinders may be laid flat under the exam table",
          "Cylinders only need to be secured when full",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Compressed gas cylinders must be secured upright at all times.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
  {
    id: "clinic_staff_credentialing",
    module: "clinic",
    draft: true,
    name: "Staff Qualifications & Credentialing",
    description: "Verification of licensure, primary source verification, and ongoing competency assessment in clinics.",
    icon: "BadgeCheck",
    color: "hsl(195, 75%, 45%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Primary Source Verification (Placeholder)",
        content: "Placeholder content. Licensed staff credentials must be verified through the issuing source, not by reviewing a copy of the license alone.",
        keyPoint: "Verify licenses through the primary issuing source.",
      },
    ],
    questions: [
      {
        id: "clinic_cred_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A clinic verifies an RN's license by photocopying the wallet card. Is this sufficient?",
        options: [
          "Yes — a photocopy is acceptable evidence",
          "No — credentials must be verified through the issuing licensing board (primary source verification)",
          "Yes — if the supervisor signs the photocopy",
          "Only if the RN is a new hire",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Primary source verification through the licensing board is required.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "clinic_cred_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: How often should clinical competency be assessed for clinic staff?",
        options: [
          "Once at hire and never again",
          "At hire and ongoing on a defined schedule with documented evidence",
          "Only when a complaint is filed",
          "Only at re-credentialing",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Competency must be assessed at hire and ongoing, with documentation.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_cred_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: Who must perform primary source verification of physician credentials in a clinic?",
        options: [
          "The physician's spouse",
          "The clinic's designated credentialing function or contracted credentials verification organization",
          "The patient",
          "A receptionist with internet access",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Credentialing must be done by an authorized function or recognized CVO.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
  {
    id: "clinic_emergency_preparedness",
    module: "clinic",
    draft: true,
    name: "Emergency Preparedness",
    description: "Emergency operations planning, drills, and continuity of care for ambulatory clinics.",
    icon: "Siren",
    color: "hsl(0, 75%, 50%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Emergency Operations Plan (Placeholder)",
        content: "Placeholder content. Clinics must maintain an Emergency Operations Plan covering communications, resources, safety, staff, utilities, and patient activities.",
        keyPoint: "EOP covers six critical areas: communications, resources, safety, staff, utilities, patient activities.",
      },
    ],
    questions: [
      {
        id: "clinic_ep_q1",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: How often must a clinic conduct emergency drills?",
        options: [
          "Once every five years",
          "At least annually, with after-action review documented",
          "Only after a real emergency",
          "Only if the surveyor requests one",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Emergency drills must occur at least annually with documented after-action review.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "clinic_ep_q2",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: Which of the following is a required element of a clinic's Emergency Operations Plan?",
        options: [
          "A list of preferred vendors only",
          "Plans for communications, resources/assets, safety/security, staff responsibilities, utilities, and patient clinical/support activities",
          "Insurance policy numbers only",
          "Marketing continuity plan only",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. CMS and Joint Commission outline six core areas.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "clinic_ep_q3",
        module: "clinic",
        draft: true,
        question: "PLACEHOLDER: A clinic loses power for two hours during a storm. Which documentation is most important after the event?",
        options: [
          "Marketing post about the resilience of the clinic",
          "After-action review documenting impact on patient care, response, and improvement opportunities",
          "Photos of the dark waiting room",
          "Nothing — power loss is routine",
        ],
        correctIndex: 1,
        explanation: "Placeholder explanation. Real events should be reviewed and documented like drills.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
];
