export interface DiagnosticQuestion {
  id: string;
  sectionId: string;
  question: string;
  options: string[];
  correctIndex: number;
}

export const diagnosticQuestions: DiagnosticQuestion[] = [
  // Transport of Instruments (5)
  { id: "dq-t1", sectionId: "transport", question: "An OR tech places soiled instruments in a basin and carries them uncovered through the hallway to the decontamination area. What is the primary compliance issue?",
    options: ["The basin should have been a rigid container with a biohazard label", "Soiled instruments must be transported in closed, leak-proof containers to prevent exposure and contamination", "The instruments should have been sprayed with enzymatic cleaner before leaving the OR", "Carrying instruments by hand is acceptable if the tech wears double gloves"],
    correctIndex: 1 },
  { id: "dq-t2", sectionId: "transport", question: "During instrument transport, a tech notices the lid of the soiled container has a small crack. What is the correct action?",
    options: ["Continue transport since the crack is minor and instruments are already inside", "Replace the container immediately before continuing transport", "Tape over the crack and proceed with transport", "Transfer to a biohazard bag and continue"],
    correctIndex: 1 },
  { id: "dq-t3", sectionId: "transport", question: "A new technician stacks two filled instrument transport containers on top of each other on a cart. Why might this be problematic?",
    options: ["Stacking is acceptable as long as both containers are properly latched", "The weight from stacking can crush delicate instruments in the lower container and compromise seal integrity", "Stacking is only an issue if containers exceed 50 pounds total", "The top container may slide off during transport, creating a spill hazard only"],
    correctIndex: 1 },
  { id: "dq-t4", sectionId: "transport", question: "Enzymatic spray is applied to instruments at the point of use. What is the primary purpose of this step?",
    options: ["To sterilize the instruments before they reach the decontamination area", "To prevent bioburden from drying on instrument surfaces during transport", "To eliminate the need for ultrasonic cleaning later in the process", "To lubricate instrument joints for easier disassembly in SPD"],
    correctIndex: 1 },
  { id: "dq-t5", sectionId: "transport", question: "A transport cart used for soiled instruments is also occasionally used to deliver clean supplies. What is the compliance concern?",
    options: ["Multi-use carts are permitted if wiped down between uses", "Dedicated carts must be used for soiled transport to prevent cross-contamination of clean supplies", "The cart only needs to be replaced if visibly soiled after instrument transport", "Using the same cart is acceptable if clean supplies are covered"],
    correctIndex: 1 },

  // Environment & Surfaces (5)
  { id: "dq-e1", sectionId: "environment", question: "A patient room thermometer reads 78°F. Staff say the temperature has been stable at this level all day. Is this within the acceptable range?",
    options: ["The acceptable range for patient care areas is 68–75°F, so 78°F exceeds the upper limit", "Any temperature between 65–80°F is acceptable for patient comfort", "Temperature requirements only apply to operating rooms, not general patient rooms", "78°F is acceptable as long as humidity is below 50%"],
    correctIndex: 0 },
  { id: "dq-e2", sectionId: "environment", question: "A housekeeper cleans a terminal room after discharge. She wipes high-touch surfaces but skips the overhead light handles because she cannot reach them. What should happen?",
    options: ["Overhead light handles are classified as low-touch surfaces and do not require terminal cleaning", "All high-touch surfaces including overhead light handles must be cleaned during terminal cleaning, and tools should be provided to reach them", "Light handles only need cleaning if the patient was on isolation precautions", "The next nurse can clean the light handles before using them"],
    correctIndex: 1 },
  { id: "dq-e3", sectionId: "environment", question: "A crack in a procedure room's floor tile exposes the subflooring beneath. Why is this a compliance finding?",
    options: ["Cracked tiles are only a finding if they present a tripping hazard to patients", "Damaged flooring compromises the impervious surface needed for proper cleaning and infection prevention", "Floor cracks are acceptable if sealed with caulk within 30 days", "The finding only applies if the room is used for sterile procedures"],
    correctIndex: 1 },
  { id: "dq-e4", sectionId: "environment", question: "Humidity in the OR reads 65%. Staff have not reported any concerns. What is the issue?",
    options: ["OR humidity must be maintained between 20–60%, so 65% is above the acceptable range and increases infection risk", "65% humidity is within acceptable limits for ORs in most climate zones", "Humidity only matters during active surgical cases, not between procedures", "High humidity is only a concern if condensation is visible on surfaces"],
    correctIndex: 0 },
  { id: "dq-e5", sectionId: "environment", question: "A nurse places a personal fan on her workstation to stay cool during a warm day. What is the compliance concern?",
    options: ["Personal fans are permitted at nursing stations as long as they do not face patient areas", "Personal fans can distribute airborne contaminants and disrupt controlled airflow patterns in clinical areas", "Fans are acceptable if approved by the charge nurse and infection prevention", "The only concern is electrical safety — the fan must be plugged into a red outlet"],
    correctIndex: 1 },

  // Clean vs. Dirty (5)
  { id: "dq-s1", sectionId: "segregation", question: "A nurse stores extra clean linens on top of a covered biohazard waste container because shelf space is limited. What is wrong with this practice?",
    options: ["Clean supplies must never be stored on or near biohazard waste containers regardless of whether they are covered", "This is acceptable as long as the linens are in a sealed bag", "The practice is permitted temporarily during high-census situations", "Clean linens on a covered container are acceptable since there is no direct contact with waste"],
    correctIndex: 0 },
  { id: "dq-s2", sectionId: "segregation", question: "The soiled utility room and clean supply room share a wall but have separate entrances. Staff use the clean supply room as a shortcut to reach the soiled room. Why is this a problem?",
    options: ["Traffic flow from clean to soiled areas introduces contaminants into the clean supply room and violates separation principles", "Shared walls automatically violate segregation requirements", "This is acceptable if staff change gloves between rooms", "The shortcut is only a problem during active patient care hours"],
    correctIndex: 0 },
  { id: "dq-s3", sectionId: "segregation", question: "A medication nurse prepares IV medications on a counter that was just used to document patient wound measurements. What is the concern?",
    options: ["Medication preparation surfaces must be dedicated and cleaned with appropriate disinfectant before use — cross-contamination from wound care documentation materials is a risk", "Documentation surfaces can double as medication prep areas if wiped with alcohol", "This is acceptable if the nurse wears gloves during medication preparation", "The concern only applies if wound dressings were physically present on the counter"],
    correctIndex: 0 },
  { id: "dq-s4", sectionId: "segregation", question: "A staff member takes a used bedpan to the soiled utility room, rinses it, then walks back through the hallway carrying the rinsed bedpan to get a clean one. What is the issue?",
    options: ["Rinsed bedpans are considered clean and may be transported through hallways", "Soiled or used patient care items should not be transported through clean corridors — the bedpan should be processed entirely within the soiled utility room", "The bedpan only needs to be covered during transport through hallways", "This is acceptable if the bedpan is visibly clean after rinsing"],
    correctIndex: 1 },
  { id: "dq-s5", sectionId: "segregation", question: "Clean supply room temperature reads 80°F. Staff say the air conditioning has been unreliable. Why does this matter for clean storage?",
    options: ["Elevated temperatures can compromise the integrity of certain supplies and medications, and the HVAC issue should be reported and resolved promptly", "Supply room temperature is not regulated as long as supplies are in sealed packaging", "80°F is within acceptable range for supply storage areas", "Temperature only matters for medication storage, not general clean supplies"],
    correctIndex: 0 },

  // Sterile Storage (5)
  { id: "dq-ss1", sectionId: "sterile_storage", question: "Sterile supplies are stored on shelving that is 6 inches off the floor. Is this height compliant?",
    options: ["Sterile supplies must be stored 8–10 inches off the floor to allow for proper cleaning and prevent splash contamination", "6 inches is the minimum required height for sterile storage", "Floor clearance requirements only apply to supplies in the OR, not central storage", "Any height off the floor is acceptable as long as supplies are wrapped"],
    correctIndex: 0 },
  { id: "dq-ss2", sectionId: "sterile_storage", question: "A sterile package is found 14 inches below a ceiling-mounted sprinkler head. Is this compliant?",
    options: ["Sterile supplies must be stored at least 18 inches below sprinkler heads to avoid water damage and maintain fire code compliance", "14 inches is within the acceptable range below sprinkler heads", "Sprinkler clearance requirements only apply to flammable materials, not sterile supplies", "The clearance rule only applies if the sprinkler system is a wet-pipe system"],
    correctIndex: 0 },
  { id: "dq-ss3", sectionId: "sterile_storage", question: "Peel-pack pouches are stacked four high on a sterile storage shelf. What is the compliance issue?",
    options: ["Peel packs should be stacked no more than two high to prevent crushing and compromising the sterile barrier", "Stacking height limits only apply to rigid containers, not peel packs", "Four-high stacking is acceptable if pouches are the same size", "Peel packs must be stored flat, never stacked at all"],
    correctIndex: 0 },
  { id: "dq-ss4", sectionId: "sterile_storage", question: "Dust covers are placed over sterile items on open shelving. The shelving is located directly under an HVAC vent. Is this setup adequate?",
    options: ["Dust covers alone do not compensate for direct HVAC airflow, which can push contaminants onto sterile packaging even through covers", "Dust covers fully protect sterile items regardless of air vent proximity", "HVAC air in healthcare facilities is filtered, so vent location is irrelevant", "Direct airflow only matters if the room has positive pressure"],
    correctIndex: 0 },
  { id: "dq-ss5", sectionId: "sterile_storage", question: "A rigid sterilization container weighs 28 pounds fully loaded. What is the concern?",
    options: ["Rigid containers should not exceed 25 pounds to prevent handling injuries and ensure safe instrument processing", "The weight limit for rigid containers is 35 pounds", "Weight limits only apply during autoclaving, not storage", "28 pounds is acceptable if two staff members lift the container together"],
    correctIndex: 0 },

  // Instrument Integrity (5)
  { id: "dq-i1", sectionId: "instruments", question: "A surgical technician notices a ratcheted instrument does not hold at the first click position. What should happen?",
    options: ["The instrument should be removed from service and reported for repair, as a failed ratchet compromises function and patient safety", "First-click position is not required — the instrument only needs to hold at full ratchet", "The tech can adjust the ratchet tension with pliers before the next case", "The instrument can be used if the surgeon is informed of the issue"],
    correctIndex: 0 },
  { id: "dq-i2", sectionId: "instruments", question: "Scissors are tested for sharpness and fail to cut cleanly through the first two inches of the test material. What is the correct action?",
    options: ["The scissors must be removed from the set and sent for sharpening or replacement before being used on a patient", "A two-inch cutting deficiency is within acceptable tolerance for most surgical scissors", "The surgeon can sharpen the scissors with a honing stone between cases", "Dull scissors can still be used for blunt dissection procedures"],
    correctIndex: 0 },
  { id: "dq-i3", sectionId: "instruments", question: "An instrument has visible staining that does not come off with standard cleaning. Is this instrument safe to use?",
    options: ["Persistent staining may indicate corrosion, mineral deposits, or biofilm — the instrument must be evaluated and potentially removed from service", "Surface staining is cosmetic and does not affect instrument function or safety", "Stained instruments are acceptable if they pass a visual inspection under magnification", "The stain will be removed during the next autoclave cycle"],
    correctIndex: 0 },
  { id: "dq-i4", sectionId: "instruments", question: "During an instrument count, one retractor from the tray is missing. The circulating nurse finds it in the sink soaking. What should be documented?",
    options: ["The discrepancy should be documented with the instrument's location and the set should not be considered complete until all pieces are accounted for and properly processed together", "Finding the missing instrument resolves the count — no documentation is needed", "Only missing sharps require documentation, not retractors", "Documentation is only required if the instrument was missing during an active surgical case"],
    correctIndex: 0 },
  { id: "dq-i5", sectionId: "instruments", question: "A microsurgical instrument tip is slightly bent after a case. The tech straightens it manually. Is this acceptable?",
    options: ["Microsurgical instruments must be repaired by qualified technicians — manual straightening can cause micro-fractures that compromise the instrument and patient safety", "Manual straightening is an acceptable field repair for minor tip deflections", "Bent tips are only a concern if the bend exceeds 15 degrees", "The instrument can be used if the surgeon approves the repair"],
    correctIndex: 0 },

  // Facilities & Equipment (5)
  { id: "dq-f1", sectionId: "facilities", question: "A blanket warmer thermometer reads 132°F. Staff say they checked it an hour ago and it was at 128°F. What is the finding?",
    options: ["The current reading of 132°F exceeds the 130°F maximum for blanket warmers, regardless of the previous reading", "132°F is within the acceptable 2°F calibration tolerance above the 130°F limit", "The previous compliant reading demonstrates the warmer is functioning properly", "Blanket warmer temperatures only need to be checked once per shift"],
    correctIndex: 0 },
  { id: "dq-f2", sectionId: "facilities", question: "A code cart is found with expired laryngoscope batteries. All other items on the cart are current. What is the compliance status?",
    options: ["Any expired item on a code cart means the entire cart is non-compliant and must be restocked before it can be returned to service", "Laryngoscope batteries are not considered critical items and have a grace period", "The cart is compliant as long as the primary defibrillator is functional", "Battery expiration only matters if the laryngoscope fails to illuminate"],
    correctIndex: 0 },
  { id: "dq-f3", sectionId: "facilities", question: "An eye wash station is tested and produces only a trickle of water from one nozzle. What action is required?",
    options: ["The eye wash station must be taken out of service and repaired immediately — both nozzles must provide adequate flushing flow", "A single functioning nozzle meets the minimum requirement for emergency eye washing", "Eye wash stations only need to be tested monthly, so the issue can wait for scheduled maintenance", "The trickle is sufficient as long as the water temperature is within range"],
    correctIndex: 0 },
  { id: "dq-f4", sectionId: "facilities", question: "A fluid warmer in the OR is set to 115°F. The warmer contains IV fluids for the current case. What is the concern?",
    options: ["Fluid warmers must not exceed 110°F to prevent degradation of IV solutions and potential patient harm", "115°F is the standard setting for IV fluid warming in surgical cases", "Fluid warmer limits only apply to blood products, not crystalloid IV solutions", "The temperature is acceptable as long as fluids are used within 4 hours"],
    correctIndex: 0 },
  { id: "dq-f5", sectionId: "facilities", question: "An emergency generator test log shows the generator was tested 45 days ago. What is the compliance concern?",
    options: ["Emergency generators must be tested at least every 30 days per NFPA and Joint Commission requirements", "45-day testing intervals are acceptable if the generator passed its last annual load test", "Generator testing frequency is determined by the manufacturer, not regulatory standards", "Monthly testing is only required for hospitals with more than 200 beds"],
    correctIndex: 0 },

  // SPD & Decontamination (5)
  { id: "dq-spd1", sectionId: "spd_decontam", question: "A decontamination technician is wearing a surgical mask instead of a face shield while processing instruments at the sink. What needs to change?",
    options: ["Decontamination requires full face protection including a face shield or goggles with a mask to protect against splashes and aerosols", "A surgical mask provides sufficient protection during manual decontamination", "Face shields are only required when using ultrasonic cleaners, not manual sinks", "Full face protection is only needed for instruments contaminated with known pathogens"],
    correctIndex: 0 },
  { id: "dq-spd2", sectionId: "spd_decontam", question: "An ultrasonic cleaner cavitation test shows uneven results across the test strip. What does this indicate?",
    options: ["Uneven cavitation means the transducers may be failing and instruments processed in affected zones may not be adequately cleaned", "Minor variations in cavitation patterns are normal and expected", "The test only needs to be repeated if results are completely negative", "Uneven cavitation is acceptable if the overall energy output meets minimum thresholds"],
    correctIndex: 0 },
  { id: "dq-spd3", sectionId: "spd_decontam", question: "A biological indicator (BI) from a sterilization load comes back positive. What is the required response?",
    options: ["All items from that load must be recalled, quarantined, and reprocessed — the sterilizer must be taken out of service until the cause is identified and resolved", "A single positive BI can be attributed to testing error and requires only a repeat test", "Only implantable items from the load need to be recalled", "The load is acceptable if the chemical indicators in the same load changed color correctly"],
    correctIndex: 0 },
  { id: "dq-spd4", sectionId: "spd_decontam", question: "An SPD tech uses tap water for the final rinse of instruments after ultrasonic cleaning. Is this appropriate?",
    options: ["Critical and semi-critical instruments require a rinse with treated or purified water — tap water may contain minerals and microorganisms that compromise instrument integrity", "Tap water is acceptable for rinsing since instruments will be sterilized afterward", "Water quality requirements only apply to flexible endoscope reprocessing", "Any potable water source is approved for instrument rinsing in decontamination"],
    correctIndex: 0 },
  { id: "dq-spd5", sectionId: "spd_decontam", question: "Instrument processing documentation shows that a washer-disinfector cycle reached 170°F for 8 minutes. The manufacturer requires 180°F for 10 minutes. What is the status?",
    options: ["The cycle did not meet manufacturer parameters and must be considered a failed cycle — instruments must be reprocessed", "170°F for 8 minutes provides adequate thermal disinfection for most surgical instruments", "A 10°F variance is within acceptable calibration tolerance for washer-disinfectors", "The instruments can still be used if they pass a visual cleanliness inspection"],
    correctIndex: 0 },

  // OR & Sterile Technique (5)
  { id: "dq-or1", sectionId: "or_sterile_field", question: "During a procedure, a sterile towel slides off the instrument table and touches the floor. A tech picks it up and places it back. What is the violation?",
    options: ["Any sterile item that contacts an unsterile surface is contaminated and must be removed from the field immediately", "Sterile towels can be replaced on the field if picked up within the 5-second rule", "Floor contact only contaminates the side that touched the floor — the other side remains sterile", "The towel can be reused if sprayed with sterile saline"],
    correctIndex: 0 },
  { id: "dq-or2", sectionId: "or_sterile_field", question: "An OR door is propped open during a case to allow equipment to be brought in more easily. What is the compliance impact?",
    options: ["Open OR doors disrupt the positive pressure environment needed to prevent airborne contamination of the surgical field", "Briefly propping doors open has no measurable effect on air quality during cases", "Door position only matters during orthopedic implant cases, not general surgery", "Propped doors are acceptable if the OR has laminar airflow at the surgical site"],
    correctIndex: 0 },
  { id: "dq-or3", sectionId: "or_sterile_field", question: "A circulating nurse reaches across the sterile field to adjust an overhead light. What principle was violated?",
    options: ["Unsterile personnel must never reach over a sterile field — the light should be adjusted from outside the sterile boundary or by a scrubbed team member", "Overhead adjustments are permitted since the arms do not touch the sterile surface", "The nurse can reach across if wearing sterile gloves over her non-sterile sleeves", "Light adjustments are exempt from sterile field boundaries"],
    correctIndex: 0 },
  { id: "dq-or4", sectionId: "or_sterile_field", question: "Surgical counts are performed at the beginning of the case and at closure. The policy also requires a count before closing any body cavity. The team skips the cavity count because it is a short case. What is the issue?",
    options: ["Surgical counts must follow policy exactly — skipping a required count based on case duration is a deviation regardless of case length", "Cavity counts are optional for cases under 60 minutes per most facility policies", "The final closure count covers any items that would have been caught in the cavity count", "Short cases have a lower risk of retained items, so the cavity count is discretionary"],
    correctIndex: 0 },
  { id: "dq-or5", sectionId: "or_sterile_field", question: "A scrub tech opens a peel-pack by tearing it toward herself instead of peeling the edges apart. Why is this a concern?",
    options: ["Tearing a peel-pack can cause particles from the packaging to fall onto the sterile contents, compromising sterility", "Tearing and peeling produce identical results as long as the inner contents are not touched", "Peel-pack opening technique only matters for implantable devices", "The concern is only about efficiency, not contamination risk"],
    correctIndex: 0 },

  // Surgical Safety & Consent (5)
  { id: "dq-ss-1", sectionId: "universal_protocol", question: "A patient signs a surgical consent form, but the procedure listed says 'knee surgery' without specifying which knee. Is this consent valid?",
    options: ["Surgical consent must specify the exact procedure and laterality — 'knee surgery' without specifying left or right is insufficient", "General descriptions are acceptable if the surgeon verbally clarifies during the time-out", "The consent is valid as long as the patient can verbally confirm which knee", "Laterality only needs to be documented on the surgical site marking, not the consent form"],
    correctIndex: 0 },
  { id: "dq-ss-2", sectionId: "universal_protocol", question: "During a time-out, the surgeon is scrubbing at the sink and verbally acknowledges the time-out information called out by the circulating nurse. Is this compliant?",
    options: ["The time-out requires active participation by all team members — a surgeon scrubbing at the sink is not actively participating in the verification process", "Verbal acknowledgment from the surgeon satisfies the active participation requirement", "The surgeon's participation is only required for the surgical site verification, not the full time-out", "Active participation means the surgeon must be present in the OR but does not need to stop other activities"],
    correctIndex: 0 },
  { id: "dq-ss-3", sectionId: "universal_protocol", question: "A patient's History and Physical (H&P) in the chart is dated 32 days ago. Surgery is scheduled for today. What must happen?",
    options: ["The H&P must be updated or redone — it cannot be more than 30 days old at the time of surgery per Joint Commission standards", "A 32-day-old H&P is within the acceptable 5-day grace period", "The anesthesiologist's pre-op assessment substitutes for an expired H&P", "The H&P is valid if the patient's condition has not changed"],
    correctIndex: 0 },
  { id: "dq-ss-4", sectionId: "universal_protocol", question: "A patient who speaks only Mandarin needs to sign an informed consent. The patient's bilingual teenage daughter offers to interpret. Is this acceptable?",
    options: ["A qualified medical interpreter must be used — family members, especially minors, should not serve as interpreters for informed consent", "Family member interpretation is acceptable if documented in the chart", "Teenage children can interpret if they demonstrate adequate language proficiency", "Any bilingual person present can serve as an interpreter in urgent situations"],
    correctIndex: 0 },
  { id: "dq-ss-5", sectionId: "universal_protocol", question: "The surgical site marking on a patient's left shoulder is partially obscured by surgical prep solution. What should happen before proceeding?",
    options: ["The surgical site must be clearly visible at the time of the time-out — the mark should be re-verified or re-applied if obscured", "Prep solution over the mark does not invalidate it since the mark was confirmed before prepping", "The team can proceed if they all remember where the mark was placed", "Site marking verification is only required for bilateral procedures"],
    correctIndex: 0 },

  // Patient Care & Documentation (5)
  { id: "dq-pc1", sectionId: "patient_care_docs", question: "A nurse documents medication administration 2 hours after giving the medication because the unit was busy. What is the compliance concern?",
    options: ["Medication administration must be documented at the time of administration — delayed documentation increases error risk and does not reflect real-time patient status", "A 2-hour documentation delay is within the acceptable window for most medications", "Delayed documentation is acceptable during high-acuity situations if noted in the chart", "Documentation timing only matters for controlled substances, not routine medications"],
    correctIndex: 0 },
  { id: "dq-pc2", sectionId: "patient_care_docs", question: "A patient's fall risk assessment was completed on admission 4 days ago. The patient's condition has changed significantly since then. What should happen?",
    options: ["Fall risk assessments must be reassessed whenever a patient's condition changes significantly, not just at scheduled intervals", "The admission assessment remains valid for the entire hospital stay", "Reassessment is only required every 7 days per Joint Commission standards", "Condition changes only trigger reassessment if the patient actually falls"],
    correctIndex: 0 },
  { id: "dq-pc3", sectionId: "patient_care_docs", question: "A nurse uses a patient's room number to verify identity before administering medication. What is wrong with this approach?",
    options: ["Patient identification requires two person-specific identifiers such as name and date of birth — room number is a location identifier, not a patient identifier", "Room number is an acceptable secondary identifier if used with the patient's name", "Room number verification is acceptable for patients who have been in the same room for more than 24 hours", "Any two unique identifiers including room number satisfy the identification requirement"],
    correctIndex: 0 },
  { id: "dq-pc4", sectionId: "patient_care_docs", question: "A patient on contact precautions needs a portable X-ray. The tech enters the room with the machine but does not gown or glove. What is the violation?",
    options: ["Contact precautions require gown and gloves for all individuals entering the room regardless of whether they will have direct patient contact", "Gown and gloves are only required for direct patient contact during contact precautions", "Radiology techs are exempt from contact precautions when using portable equipment", "PPE is optional if the tech maintains 3 feet of distance from the patient"],
    correctIndex: 0 },
  { id: "dq-pc5", sectionId: "patient_care_docs", question: "A patient's pain is reassessed 6 hours after receiving a PRN pain medication. The facility policy requires reassessment within 1 hour. What is the finding?",
    options: ["Pain reassessment timing must follow facility policy — a 6-hour delay when the policy requires 1 hour is a documentation and care compliance failure", "PRN medication reassessment timing is a guideline, not a regulatory requirement", "Reassessment within the same shift satisfies the documentation requirement", "The 1-hour requirement only applies to IV pain medications, not oral medications"],
    correctIndex: 0 },

  // EOC & Safety Compliance (5)
  { id: "dq-eoc1", sectionId: "eoc_safety", question: "A fire extinguisher in a clinical hallway is due for annual inspection next month but the pressure gauge shows it is in the green zone. Is it compliant?",
    options: ["If the annual inspection is not yet overdue, a fire extinguisher with a green pressure reading is currently compliant", "Fire extinguishers must be replaced rather than inspected annually", "The pressure gauge reading is irrelevant — only the inspection tag date matters", "Annual inspections can be deferred up to 6 months if the pressure gauge reads normal"],
    correctIndex: 0 },
  { id: "dq-eoc2", sectionId: "eoc_safety", question: "Staff are asked to describe the RACE acronym during a fire drill. One nurse says the A stands for 'Alert.' What is incorrect?",
    options: ["In RACE, the A stands for Alarm (pull the fire alarm) — Alert is not the correct term and could delay critical notification", "Alert and Alarm are interchangeable in the RACE acronym", "The A in RACE stands for Assess the situation", "RACE only applies to code red situations, not fire drills"],
    correctIndex: 0 },
  { id: "dq-eoc3", sectionId: "eoc_safety", question: "Medical gas cylinders are stored in a room. There are 14 full oxygen cylinders standing upright. What is the potential violation?",
    options: ["NFPA limits storage to 12 full-size cylinders of oxidizing gases per smoke compartment without additional protections", "There is no regulatory limit on the number of oxygen cylinders in a storage room", "The 12-cylinder limit only applies to flammable gases, not oxygen", "Up to 24 cylinders are permitted if the room has a fire sprinkler system"],
    correctIndex: 0 },
  { id: "dq-eoc4", sectionId: "eoc_safety", question: "A clinical staff member finds a chemical spill in the hallway. She does not know what the chemical is. What is the first action?",
    options: ["Secure the area and consult the Safety Data Sheet (SDS) to identify the chemical and appropriate cleanup procedures before attempting to clean it", "Clean the spill immediately with universal absorbent material to prevent injuries", "Call environmental services and wait for them to handle the spill", "Evacuate the entire floor as a precaution until the chemical is identified"],
    correctIndex: 0 },
  { id: "dq-eoc5", sectionId: "eoc_safety", question: "A PCBA (above-ceiling) inspection reveals dust accumulation on pipes and unsealed penetrations around cable bundles. What are the compliance implications?",
    options: ["Unsealed penetrations compromise fire compartment integrity and dust accumulation indicates inadequate maintenance of the space above the ceiling", "Above-ceiling conditions are only inspected during major construction projects", "Dust above the ceiling is expected and does not constitute a finding", "Penetration seals are only required for plumbing pipes, not electrical cables"],
    correctIndex: 0 },
];
