import type { Level } from "./schema";

export const dnvOtLevel: Level = {
  id: "dnv_ot",
  module: "dnv",
  name: "Surgical & Anesthesia Services",
  description: "DNV DIAS Sections 12–13 — OT/AS standards for operating theatre organization, surgical safety, anesthesia administration, pre/post anesthesia evaluation, and documentation.",
  icon: "Scissors",
  color: "hsl(195, 65%, 42%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "OT/AS: Surgical & Anesthesia Services",
    plainLanguageSummary:
      "DNV's Operating Theatre and Anesthesia Services sections require that surgical and anesthesia services be organized, staffed, and operated in accordance with recognized standards. Every operating theatre must have essential emergency equipment immediately available. The OR register must be complete and current. Anesthesia services must be organized under a qualified physician director, with privileges granted to each anesthesia provider. Pre-anesthesia evaluation must occur within 48 hours before surgery, and post-anesthesia evaluation must be completed within 48 hours after surgery. Wrong-site/wrong-patient/wrong-procedure prevention processes (e.g., WHO Surgical Safety Checklist) are required.",
    keyOperationalExpectations: [
      "Operating theatres supervised by a qualified RN, ODP, or physician.",
      "Emergency equipment available to each theatre: defibrillator, AMBU-bag, cardiac monitor, suction, emergency call system.",
      "OR register maintained complete and current for all surgical cases.",
      "Pre-anesthesia evaluation within 48 hours before anesthesia administration.",
      "Post-anesthesia evaluation documented within 48 hours after surgery.",
      "Wrong-site, wrong-patient, wrong-procedure prevention process implemented (e.g., WHO Checklist).",
    ],
    commonRiskPoints: [
      "Pre-anesthesia evaluation completed more than 48 hours before surgery.",
      "Post-anesthesia evaluation not completed within 48 hours after surgery.",
      "OR register missing required data elements (anesthesia type, surgeon names, pre/post-op diagnosis).",
      "Emergency equipment present but not maintained, inspected, or tested.",
    ],
    cmsTags: ["OT.1", "OT.2", "OT.3", "OT.4", "OT.5", "OT.6", "AS.1", "AS.2", "AS.3"],
  },
  studyMaterial: [
    {
      title: "OT.1/OT.2 — Operating Theatre Organization and Staffing",
      content:
        "Surgical services must be organized under the supervision of either a qualified registered nurse, an Operating Department Practitioner (ODP), or a physician with appropriate surgical services experience. The organization must provide adequate staffing for all surgical services including circulating, scrub, and supervisory roles. Staff must have specialized training for their roles. Any individuals being trained or observing must be appropriately supervised. Staffing schedules must ensure adequate numbers and registered nursing supervision.",
      keyPoint:
        "OR must have RN, ODP, or physician supervisor with surgical services experience. All OR staff require specialized training. Observers must be supervised.",
    },
    {
      title: "OT.3 — Required Emergency Equipment",
      content:
        "The following equipment must be present, in operating condition, and immediately available to each theatre: (a) emergency call system, (b) cardiac monitor, (c) resuscitator/AMBU-bag, (d) defibrillator, (e) suction equipment, and (f) provisions for emergency airway intervention. Equipment must be maintained, inspected, and tested through the organization's biomedical engineering program. A tracheotomy set must also be available (cricothyroidotomy set is not a substitute).",
      keyPoint:
        "6 required equipment items per theatre: emergency call, cardiac monitor, AMBU-bag, defibrillator, suction, emergency airway provisions. Tracheotomy set also required — cricothyroidotomy set is NOT a substitute.",
    },
    {
      title: "OT.4/OT.5 — OR Register and Post-Operative Care",
      content:
        "The OR register must be complete and current for every surgical case, documenting: patient name, date of birth, patient ID number, date and time of operation, name of surgeon and assistants, scrub and circulating personnel names, anesthesia type and administering practitioner, procedure performed in full, and pre/post-op diagnosis. Immediate post-operative care must be provided in a dedicated recovery area separate from the OR. Criteria for recovery discharge must be established and followed.",
      keyPoint:
        "OR register requires 10 specific data elements — missing ANY element = non-compliant. Recovery area must be separate from the OR theatre.",
    },
    {
      title: "OT.6 — Surgical Documentation and Wrong-Site Prevention",
      content:
        "An operative report must be written or dictated immediately after surgery and before patient transfer to the next level of care. If dictation is delayed, an immediate post-op note with required elements must be written. A process to prevent wrong-site, wrong-patient, and wrong-procedure surgery must be implemented — DNV recommends the WHO Surgical Safety Checklist. Continuity of care documentation must accompany all unit transfers.",
      keyPoint:
        "Operative report required before transfer from OR. If delayed, immediate post-op note required with all elements. WHO Surgical Safety Checklist or equivalent wrong-site prevention process is required.",
    },
    {
      title: "AS.1/AS.3 — Anesthesia Organization, Privileges, and Evaluation",
      content:
        "Anesthesia services must be organized under a qualified physician director responsible for all anesthesia provided throughout the organization. Each anesthesia provider requires specific clinical privileges delineating the types and complexity of anesthesia they may administer and whether supervision is required. Pre-anesthesia evaluation must occur within 48 hours before anesthesia administration (measured from first medication dose). Post-anesthesia evaluation must be completed and documented within 48 hours after surgery by a qualified individual. Elements of post-anesthesia evaluation are specific (respiratory, cardiovascular, mental status, temperature, pain, nausea, hydration).",
      keyPoint:
        "Pre-anesthesia eval: within 48 hours before first anesthesia dose. Post-anesthesia eval: within 48 hours after surgery. Both must be documented with specific elements.",
    },
  ],
  questions: [
    {
      id: "dnv_ot_01",
      question: "Under DNV OT.3, which of the following must be immediately available to EACH operating theatre?",
      options: [
        "A surgical microscope and C-arm fluoroscopy unit",
        "Cardiac monitor, defibrillator, AMBU-bag, suction, emergency call system, and emergency airway provisions",
        "A perfusion pump and blood warmer",
        "A cryotherapy unit and electrosurgical generator",
      ],
      correctIndex: 1,
      explanation: "DNV OT.3 requires six specific items immediately available to each theatre: cardiac monitor, defibrillator, resuscitator/AMBU-bag, suction equipment, emergency call system, and provisions for emergency airway intervention. These items must be in operating condition and maintained.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_02",
      question: "A hospital's OR register documents the procedure and surgeon's name but omits the type of anesthesia and the name of the anesthesia provider. Under DNV OT.4, this is:",
      options: [
        "Acceptable if the anesthesia record is filed separately",
        "Non-compliant — anesthesia type and administering practitioner are required OR register elements",
        "Acceptable for minor procedures not requiring general anesthesia",
        "Non-compliant only if the anesthesia provider was not credentialed",
      ],
      correctIndex: 1,
      explanation: "DNV OT.4 requires the OR register to document all required data elements including anesthesia type and the name of the anesthesia provider. The OR register must be complete — missing any required element constitutes non-compliance.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_03",
      question: "A pre-anesthesia evaluation is completed 72 hours before a patient's scheduled surgery. Under DNV AS.3, this is:",
      options: [
        "Acceptable if the patient's condition has not changed",
        "Non-compliant — pre-anesthesia evaluation must occur within 48 hours before anesthesia administration",
        "Acceptable for outpatient procedures",
        "Non-compliant only if the surgery is high-risk",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 requires pre-anesthesia evaluation to be performed within 48 hours before anesthesia administration (measured from the first medication dose). An evaluation completed 72 hours before falls outside this window and is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_04",
      question: "A patient is discharged 24 hours after surgery without a post-anesthesia evaluation documented in the medical record. Under DNV AS.3, this is:",
      options: [
        "Acceptable if the patient was discharged without complications",
        "Non-compliant — post-anesthesia evaluation must be documented within 48 hours after surgery",
        "Acceptable for outpatient procedures with same-day discharge",
        "Non-compliant only if the patient received general anesthesia",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 is explicit: even when patients are discharged before 48 hours, the post-anesthesia evaluation must still be completed and documented. Early discharge does not eliminate the post-anesthesia evaluation requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_05",
      question: "The hospital has no process for preventing wrong-site, wrong-patient, or wrong-procedure surgery. Under DNV OT.6, this is:",
      options: [
        "Acceptable if the hospital has never had a wrong-site event",
        "Non-compliant — a wrong-site/wrong-procedure/wrong-patient prevention process is required",
        "Acceptable if surgeons verbally confirm the site before incision",
        "Non-compliant only for facilities performing over 1,000 surgeries annually",
      ],
      correctIndex: 1,
      explanation: "DNV OT.6 requires a process to prevent wrong-site, wrong-patient, and wrong-procedure surgery. DNV recommends the WHO Surgical Safety Checklist or equivalent. Absence of any structured prevention process is non-compliant regardless of the facility's safety history.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_06",
      question: "Under DNV OT.2, who may serve as the supervisor responsible for operating theatre services?",
      options: [
        "A licensed practical nurse (LPN) with OR experience",
        "A registered nurse, ODP, or physician with appropriate surgical services experience",
        "A certified surgical technologist with 10+ years of experience",
        "A hospital administrator with clinical oversight training",
      ],
      correctIndex: 1,
      explanation: "DNV OT.2 requires the OR to be supervised by a qualified registered nurse, Operating Department Practitioner (ODP), or physician with appropriate education and experience in surgical services management. Other roles cannot serve as the OR supervisor.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_07",
      question: "Under DNV AS.1, who must direct the hospital's anesthesia services?",
      options: [
        "A CRNA with 10+ years of experience",
        "A qualified physician director",
        "The Chief Nursing Officer",
        "The hospital's quality manager",
      ],
      correctIndex: 1,
      explanation: "DNV AS.1 requires anesthesia services to be organized under the direction of a qualified physician. The physician director is responsible for all anesthesia services provided throughout the organization, including all off-site locations.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_08",
      question: "A surgeon dictates the operative report 3 days after surgery. Under DNV OT.6, what immediate documentation was required?",
      options: [
        "No immediate documentation — dictation within 72 hours satisfies the standard",
        "An immediate post-operative note with required elements written before patient transfer from the OR",
        "A nursing note describing the procedure",
        "A brief verbal summary communicated to the receiving unit",
      ],
      correctIndex: 1,
      explanation: "DNV OT.6 requires the operative report to be written or dictated immediately after surgery and before patient transfer. When dictation is delayed, an immediate post-op note containing all required elements must be written before transfer. A 3-day delay without an immediate note is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_09",
      question: "Under DNV OT.3, a cricothyroidotomy set is present in the OR as the emergency airway device. A tracheotomy set is not available. This is:",
      options: [
        "Acceptable — a cricothyroidotomy set is a valid substitute for a tracheotomy set",
        "Non-compliant — a tracheotomy set is required and a cricothyroidotomy set is not a substitute",
        "Acceptable for facilities that do not perform tracheotomy procedures",
        "Non-compliant only if airway emergencies have occurred",
      ],
      correctIndex: 1,
      explanation: "DNV OT.3 explicitly states that a tracheotomy set must be available and that a cricothyroidotomy set should NOT be considered a substitute. Both devices serve different clinical purposes — the standard specifically requires the tracheotomy set.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_10",
      question: "Which elements must be included in a post-anesthesia evaluation under DNV AS.3?",
      options: [
        "Pain score only",
        "Respiratory function, cardiovascular function, mental status, temperature, pain, nausea/vomiting, and hydration",
        "Vital signs and oxygen saturation only",
        "Level of consciousness and pain score",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 specifies that post-anesthesia evaluation must document: respiratory function (rate, airway, O2 sat), cardiovascular function (pulse, BP), mental status, temperature, pain, nausea and vomiting, and postoperative hydration. All seven elements must be addressed.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_11",
      question: "An OR observer from a medical school is present in the OR without any supervision from OR staff. Under DNV OT.2, this is:",
      options: [
        "Acceptable if the observer signed a confidentiality agreement",
        "Non-compliant — individuals observing must be appropriately supervised",
        "Acceptable if the observer is a licensed physician",
        "Non-compliant only if the observer touches any equipment",
      ],
      correctIndex: 1,
      explanation: "DNV OT.2 requires that individuals being trained or observing in the OR be appropriately supervised. Unsupervised observers create patient safety, privacy, and infection control risks — appropriate supervision is required regardless of the observer's credentials.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_12",
      question: "Under DNV OT.5, what must a recovery room or post-anesthesia care area provide?",
      options: [
        "A waiting area for family members",
        "Respiratory and cardiac monitoring, resuscitation equipment, and qualified clinical staff",
        "A dedicated pharmacist to manage post-op medications",
        "A physician present in the recovery area at all times",
      ],
      correctIndex: 1,
      explanation: "DNV OT.5 requires the recovery area to provide appropriate equipment (respiratory and cardiac monitoring, resuscitation equipment) and qualified clinical staff to adequately address the patient's plan of care according to the complexity of surgery performed.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_13",
      question: "The intraoperative anesthesia record does not document the techniques used and patient positions during a general anesthesia case. Under DNV AS.3, this is:",
      options: [
        "Acceptable if vital signs and drug administration are documented",
        "Non-compliant — techniques used and patient positions must be documented in the anesthesia record",
        "Acceptable for procedures lasting less than 30 minutes",
        "Non-compliant only for regional anesthesia cases",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 requires intraoperative anesthesia records to document techniques used and patient positions. These elements are required alongside drug documentation, vital signs, fluid management, and complications. Missing required elements renders the record incomplete.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_14",
      question: "A hospital's operating room equipment (defibrillator, cardiac monitor) is present but has not been inspected or maintained in 18 months. Under DNV OT.3, this is:",
      options: [
        "Acceptable if the equipment appears to be functioning",
        "Non-compliant — equipment must be maintained, inspected, and tested through the biomedical engineering program",
        "Acceptable if no equipment failures have occurred",
        "Non-compliant only for facilities performing high-risk cardiac procedures",
      ],
      correctIndex: 1,
      explanation: "DNV OT.3 requires that emergency equipment be maintained, inspected, and tested by the organization's biomedical equipment/clinical engineering program or contracted service. Presence without documented maintenance is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_15",
      question: "Under DNV AS.2, a CRNA wishes to administer general anesthesia without physician supervision. The hospital's policy permits this if the CRNA has been granted appropriate privileges. Under DNV AS.2, this is:",
      options: [
        "Always non-compliant — CRNAs must always be supervised by an anesthesiologist",
        "Potentially compliant — if the CRNA has been granted privileges for unsupervised practice and applicable law permits",
        "Always compliant — CRNAs are independently licensed practitioners",
        "Non-compliant unless state law explicitly requires CRNA supervision",
      ],
      correctIndex: 1,
      explanation: "DNV AS.2 requires privileges to specify the type of supervision required for each anesthesia provider. If the CRNA has been granted privileges for independent practice and national/state law permits this, it may be compliant. The key is that the privilege structure addresses supervision requirements explicitly.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_16",
      question: "The pre-anesthesia evaluation element that specifically measures the 48-hour time limit is measured from which event?",
      options: [
        "The time of surgical incision",
        "The time of first medication dose for inducing anesthesia",
        "The time the patient arrives in the pre-operative holding area",
        "The time the patient signs the consent form",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 specifies that the 48-hour time frame for pre-anesthesia evaluation ends when the first dose of medications for inducing anesthesia is administered. This is the precise measurement point defined in the standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_17",
      question: "An immediate post-operative note is written after surgery but does not include the pre-operative and post-operative diagnoses. Under DNV OT.6, this is:",
      options: [
        "Acceptable if the operative report will include this information when dictated",
        "Non-compliant — pre-op and post-op diagnoses are required elements of the immediate post-op note",
        "Acceptable for emergency procedures only",
        "Non-compliant only if there is a significant difference between pre and post-op diagnoses",
      ],
      correctIndex: 1,
      explanation: "DNV OT.6 SR.3f specifies that pre-op and post-op diagnosis are required elements of the immediate post-operative note. Missing required elements from the immediate note is non-compliant regardless of whether they will later appear in the operative report.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_18",
      question: "Under DNV OT.5, patients recovering from surgery may be cared for in their patient room rather than a dedicated recovery area only when:",
      options: [
        "The surgeon orders direct-to-room transfer",
        "A registered nurse provides direct observation at a comparable level of care during the recovery phase",
        "The patient had only local anesthesia",
        "The patient has no post-operative complications",
      ],
      correctIndex: 1,
      explanation: "DNV OT.5 permits direct-to-room recovery ONLY when a registered nurse provides direct observation of the patient in the room to ensure a comparable level of care to the recovery room. This is an exception, not the standard practice.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_19",
      question: "Under DNV AS.3, a pre-anesthesia evaluation must include which specific airway assessment element?",
      options: [
        "A chest X-ray",
        "A documented airway assessment",
        "A spirometry test",
        "A nasopharyngoscopy",
      ],
      correctIndex: 1,
      explanation: "DNV AS.3 SR.2b(3) requires the pre-anesthesia evaluation to include a documented airway assessment. This is one of the six specific required elements: medical history review, patient interview/examination, documented airway assessment, anesthesia risk assessment, drug and allergy history, and timely completion.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ot_20",
      question: "A surgical case is performed but not entered into the OR register until the following week. Under DNV OT.4, this is:",
      options: [
        "Acceptable if the operative report is completed immediately",
        "Non-compliant — the OR register must be complete and up to date",
        "Acceptable for weekend cases when administrative staff is not available",
        "Non-compliant only if the delay exceeds 30 days",
      ],
      correctIndex: 1,
      explanation: "DNV OT.4 SR.1 simply states the OR register shall be complete and up to date. Entering cases days after the fact violates the 'up to date' requirement and creates gaps in the surgical accountability record.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
