import type { Level } from "./schema";

export const dnvNsLevel: Level = {
  id: "dnv_ns",
  module: "dnv",
  name: "Nursing & Staffing",
  description: "DNV DIAS Sections 8–9 — NS/SM standards for nursing services organization, staffing levels, competency, and workforce management.",
  icon: "Heart",
  color: "hsl(350, 65%, 48%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "NS/SM: Nursing Services & Staffing Management",
    plainLanguageSummary:
      "DNV's Nursing Services and Staffing Management sections require hospitals to maintain an organized, qualified nursing staff under the direction of a registered nurse executive. Staffing levels must be based on patient acuity, not just census, and must be documented and adjusted in real time. All nursing staff must meet competency requirements. Nurse-to-patient ratios must be defined, monitored, and adjusted based on patient needs. Float pool and agency staff must meet the same competency standards as permanent staff.",
    keyOperationalExpectations: [
      "A registered nurse (RN) serves as the nursing executive with authority over nursing practice organization-wide.",
      "Staffing levels are based on patient acuity and census with real-time adjustment capability.",
      "Competency assessments completed for all nursing staff at orientation and at defined intervals.",
      "Float pool and agency staff demonstrate the same competencies as unit-based staff.",
      "Nursing policies and procedures are developed, reviewed annually, and approved by the nursing executive.",
      "Nurse-to-patient ratios are defined per unit type and monitored for compliance.",
    ],
    commonRiskPoints: [
      "Staffing determined by census (headcount) rather than patient acuity scoring.",
      "Competency assessments completed at hire but not repeated at annual intervals.",
      "Agency nurses used without verifying their competencies match unit requirements.",
      "Nurse-to-patient ratios defined but not monitored or adjusted when exceeded.",
    ],
    cmsTags: ["NS.1", "NS.2", "NS.3", "NS.4", "NS.5", "SM.1", "SM.2", "SM.3"],
  },
  studyMaterial: [
    {
      title: "NS.1 — Nursing Executive Authority",
      content:
        "The nursing service must be organized and directed by a registered nurse (RN) executive. This individual must have authority over nursing practice throughout the entire organization — not just inpatient units. The nursing executive must be qualified through education and experience appropriate to the scope and complexity of services. The nursing executive is accountable for nursing policies, standards of practice, staffing plans, and competency of nursing personnel.",
      keyPoint:
        "The nursing executive must be an RN with organization-wide authority. Qualification must match the scope and complexity of the hospital's nursing services.",
    },
    {
      title: "NS.2 — Staffing Based on Patient Acuity",
      content:
        "Nursing staffing must be based on patient acuity — the complexity and intensity of care needed — not just patient census (headcount). The hospital must use a systematic method to measure patient acuity and translate acuity scores into staffing requirements. Staffing plans must be flexible enough to allow real-time adjustments when patient acuity changes. Staffing levels must be documented each shift, and variance from the staffing plan must be tracked.",
      keyPoint:
        "Acuity-based staffing ≠ census-based staffing. The hospital must have a documented acuity measurement system that drives real-time staffing decisions.",
    },
    {
      title: "NS.3 — Nursing Competency",
      content:
        "All nursing personnel must demonstrate competency before providing patient care. Competency assessments must occur at orientation and at defined intervals thereafter (typically annually). Competencies must be specific to the patient populations served on each unit. Simulation, return demonstration, direct observation, and written testing are acceptable competency assessment methods. Competency records must be maintained in personnel files.",
      keyPoint:
        "Competency = unit-specific, patient-population-specific, assessed at orientation AND annually. Records must be documented in personnel files.",
    },
    {
      title: "NS.4 — Float Pool and Agency Staff",
      content:
        "Float pool nurses who work across multiple units and agency/contract nurses must meet the same competency standards as permanent unit-based staff. Before being assigned to a unit, float/agency nurses must have documented competencies specific to that unit's patient population. The organization is accountable for competency of all nursing staff providing care — regardless of employment status. Agency staff competencies must be verified, not assumed based on the agency's training programs.",
      keyPoint:
        "Float and agency staff must demonstrate UNIT-SPECIFIC competencies verified by the organization, not just agency training certificates.",
    },
    {
      title: "SM.1/SM.2 — Staffing Plans and Workforce Management",
      content:
        "The hospital must maintain written staffing plans for each patient care unit that define nurse-to-patient ratios, skill mix requirements, and charge nurse coverage. Plans must be reviewed at least annually. When staffing falls below the defined plan, a formal variance process must be triggered — including documentation of the variance, mitigating actions taken, and review for patterns. Systematic understaffing revealed through variance analysis must be addressed through the quality management system.",
      keyPoint:
        "Staffing plans must define ratios and skill mix by unit. Variances must be documented, mitigated, tracked for patterns, and escalated to QM if systematic.",
    },
  ],
  questions: [
    {
      id: "dnv_ns_01",
      question: "Under DNV NS.1, who must serve as the director of the nursing service?",
      options: [
        "A licensed practical nurse (LPN) with 10+ years of experience",
        "A registered nurse (RN) with authority over nursing practice organization-wide",
        "A physician with nursing administration training",
        "A hospital administrator with a clinical background",
      ],
      correctIndex: 1,
      explanation: "DNV NS.1 requires the nursing service to be directed by a registered nurse (RN) executive with organization-wide authority over nursing practice. LPNs, physicians, or non-clinical administrators cannot fulfill this role.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_02",
      question: "A hospital determines nursing staffing based solely on the number of patients (census) without considering patient acuity. Under DNV NS.2, this is:",
      options: [
        "Acceptable if census-based staffing has worked historically",
        "Non-compliant — staffing must be based on patient acuity, not just census",
        "Acceptable for medical-surgical units only",
        "Non-compliant only during high-census periods",
      ],
      correctIndex: 1,
      explanation: "DNV NS.2 requires staffing to be based on patient acuity — the complexity and intensity of care needed. Census-based staffing (headcount) fails to account for the varying care demands of different patient populations and acuity levels.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_03",
      question: "An ICU nurse's competency was assessed at orientation 3 years ago but has not been re-assessed since. Under DNV NS.3, this is:",
      options: [
        "Acceptable if no performance concerns have been identified",
        "Non-compliant — competency must be assessed at defined intervals, typically annually",
        "Acceptable for nurses with 5+ years of ICU experience",
        "Non-compliant only for nurses who have transferred from other units",
      ],
      correctIndex: 1,
      explanation: "DNV NS.3 requires competency assessment at orientation AND at defined intervals thereafter (typically annually). A single orientation assessment is insufficient — competency must be maintained and verified on an ongoing basis.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_04",
      question: "An agency nurse is assigned to the pediatric unit based on the staffing agency's training certificate. No unit-specific competency assessment has been completed by the hospital. Under DNV NS.4, this is:",
      options: [
        "Acceptable — the agency's training certificate satisfies competency requirements",
        "Non-compliant — the organization must verify unit-specific competencies for all agency staff",
        "Acceptable if the agency nurse has pediatric nursing experience",
        "Non-compliant only if the agency nurse has never worked with children",
      ],
      correctIndex: 1,
      explanation: "DNV NS.4 requires the organization to verify unit-specific competencies for all nursing staff, including agency/contract nurses. Agency training certificates do not substitute for organization-verified, unit-specific competency assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_05",
      question: "Under DNV SM.1, when staffing falls below the defined plan, what must occur?",
      options: [
        "Nothing — staffing variances are expected and require no documentation",
        "A formal variance process including documentation, mitigating actions, and pattern tracking",
        "Immediate notification to the state health department",
        "Automatic overtime for remaining staff with no additional documentation",
      ],
      correctIndex: 1,
      explanation: "DNV SM.1 requires a formal variance process when staffing falls below plan: documenting the variance, implementing mitigating actions, and tracking for patterns. Variances that become systematic must be escalated to the quality management system.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_06",
      question: "A float pool nurse from the medical-surgical unit is assigned to the cardiac ICU without any unit-specific competency verification. Under DNV NS.4, this is:",
      options: [
        "Acceptable if the nurse has 5 years of MS experience",
        "Non-compliant — float nurses must have documented unit-specific competencies before assignment",
        "Acceptable if the charge nurse provides additional supervision",
        "Non-compliant only if the assignment lasts longer than 8 hours",
      ],
      correctIndex: 1,
      explanation: "DNV NS.4 applies to float pool nurses as well as agency staff. Before being assigned to a unit, float nurses must have documented competencies specific to that unit's patient population — cardiac ICU competencies differ significantly from medical-surgical competencies.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_07",
      question: "The nursing executive has authority over nursing practice in the inpatient units but not in the emergency department or outpatient areas. Under DNV NS.1, this is:",
      options: [
        "Acceptable — the nursing executive typically covers inpatient areas only",
        "Non-compliant — the nursing executive must have organization-wide authority over nursing practice",
        "Acceptable if each department has its own nursing director",
        "Non-compliant only if the ED has separate accreditation",
      ],
      correctIndex: 1,
      explanation: "DNV NS.1 requires the nursing executive's authority to extend organization-wide, not just to inpatient units. All areas where nursing care is provided — including the ED, outpatient areas, and procedural areas — fall under the nursing executive's accountability.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_08",
      question: "A hospital's staffing plan defines nurse-to-patient ratios but never monitors whether actual staffing meets those ratios. Under DNV SM.1/SM.2, this is:",
      options: [
        "Acceptable — defining ratios satisfies the planning requirement",
        "Non-compliant — ratios must be monitored and variances must be tracked",
        "Acceptable if no patient harm has resulted from staffing levels",
        "Non-compliant only in high-acuity units",
      ],
      correctIndex: 1,
      explanation: "DNV SM.1/SM.2 requires that staffing plans be both defined and monitored. Defining ratios without monitoring whether they are met provides no assurance that patients receive appropriate nursing care levels.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_09",
      question: "Nursing policies and procedures have not been reviewed in 4 years. Under DNV NS.1, what is the required review frequency?",
      options: [
        "Every 5 years",
        "At least annually",
        "Only when changes in nursing practice occur",
        "Every 10 years",
      ],
      correctIndex: 1,
      explanation: "DNV NS.1 requires nursing policies and procedures to be reviewed at least annually and approved by the nursing executive. Annual review ensures policies reflect current standards of practice and organizational needs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_10",
      question: "A systematic analysis of staffing variances reveals that the medical-surgical unit is consistently understaffed by one nurse per shift. Under DNV SM.2, what action is required?",
      options: [
        "No action if no adverse events have occurred",
        "Escalation to the quality management system and development of a corrective action plan",
        "Documentation of the variance without further action",
        "Notification to staff that overtime is available",
      ],
      correctIndex: 1,
      explanation: "DNV SM.2 requires systematic understaffing revealed through variance analysis to be addressed through the quality management system. This includes developing corrective actions to resolve the underlying staffing deficiency.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_11",
      question: "Which method of competency assessment is acceptable under DNV NS.3?",
      options: [
        "Review of the nurse's educational transcripts only",
        "Simulation, return demonstration, direct observation, or written testing",
        "Years of clinical experience as a proxy for competency",
        "Peer attestation that the nurse is competent",
      ],
      correctIndex: 1,
      explanation: "DNV NS.3 accepts multiple competency assessment methods: simulation, return demonstration, direct observation, and written testing. Passive methods like reviewing transcripts, relying on years of experience, or peer attestation do not constitute formal competency assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_12",
      question: "Under DNV NS.2, what system must a hospital use to make real-time staffing adjustments?",
      options: [
        "A census-tracking system that counts patients by room",
        "A patient acuity measurement system that translates scores into staffing requirements",
        "A scheduling software system approved by the nursing executive",
        "A system that tracks nurse hours worked per quarter",
      ],
      correctIndex: 1,
      explanation: "DNV NS.2 requires a systematic method to measure patient acuity and translate acuity scores into staffing requirements. This system must be flexible enough to allow real-time adjustments — a simple census count does not satisfy this requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_13",
      question: "The nursing executive is a nurse with a bachelor's degree and 2 years of supervisory experience leading a 600-bed academic medical center. Under DNV NS.1, what concern arises?",
      options: [
        "No concern — any RN can serve as nursing executive",
        "The nursing executive's qualifications may not match the scope and complexity of services",
        "The concern is the bachelor's degree — a master's degree is always required",
        "No concern — 2 years of experience is the minimum under DNV",
      ],
      correctIndex: 1,
      explanation: "DNV NS.1 requires the nursing executive to be qualified through education AND experience appropriate to the scope and complexity of services. A 600-bed academic medical center requires a nursing executive whose qualifications match that complexity — 2 years of supervisory experience may be insufficient.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_14",
      question: "Staffing variances from the defined plan are documented but never reviewed for patterns. Under DNV SM.2, this is:",
      options: [
        "Compliant — documentation of variances satisfies the requirement",
        "Non-compliant — variances must be reviewed for patterns and systematic issues addressed",
        "Compliant if the nursing executive reviews individual variances",
        "Non-compliant only if adverse events occurred on understaffed shifts",
      ],
      correctIndex: 1,
      explanation: "DNV SM.2 requires variances to be documented AND reviewed for patterns. Pattern analysis is what identifies systematic understaffing that needs organizational intervention. Documentation alone without pattern review is incomplete compliance.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_15",
      question: "Under DNV NS.3, competency assessments for nursing staff must be specific to:",
      options: [
        "The general nursing license held by the nurse",
        "The patient populations served on the specific unit where the nurse works",
        "National nursing certification standards regardless of practice setting",
        "The nurse's prior educational program curriculum",
      ],
      correctIndex: 1,
      explanation: "DNV NS.3 requires competencies to be specific to the patient populations served on each unit. An ED nurse's competencies differ from an oncology nurse's competencies — unit-specific competency assessment ensures nurses can actually care for the patients they are assigned.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_16",
      question: "A hospital has no written staffing plans for its patient care units. Under DNV SM.1, this is:",
      options: [
        "Acceptable if staffing decisions are made by experienced charge nurses",
        "Non-compliant — written staffing plans are required for each patient care unit",
        "Acceptable for units with fewer than 20 beds",
        "Non-compliant only during Joint Commission survey periods",
      ],
      correctIndex: 1,
      explanation: "DNV SM.1 requires written staffing plans for each patient care unit defining nurse-to-patient ratios, skill mix, and charge nurse coverage. Verbal or informal staffing norms do not satisfy this requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_17",
      question: "Agency nursing staff routinely work in the organization's NICU. The hospital has never verified their neonatal-specific competencies. Under DNV NS.4, this represents:",
      options: [
        "Acceptable if the agency specializes in NICU staffing",
        "A significant deficiency — NICU-specific competencies must be verified by the organization",
        "Acceptable if a senior NICU nurse is always present to supervise",
        "A deficiency only if adverse events have occurred with agency nurses",
      ],
      correctIndex: 1,
      explanation: "DNV NS.4 requires the organization to verify competencies for ALL nursing staff including agency staff. The NICU is a high-acuity, specialty environment requiring specific skills. Agency specialization does not substitute for hospital-verified, NICU-specific competency assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_18",
      question: "The charge nurse on a unit verbally estimates that staffing is adequate each shift. Under DNV NS.2, what documentation is required?",
      options: [
        "No documentation required — verbal assessment satisfies the standard",
        "Written documentation of staffing levels each shift and any variances from the plan",
        "A weekly written summary of staffing patterns",
        "Monthly staffing reports reviewed by the nursing executive",
      ],
      correctIndex: 1,
      explanation: "DNV NS.2 requires staffing levels to be documented each shift. Written documentation provides accountability, supports pattern analysis, and demonstrates real-time monitoring of staffing adequacy. Verbal estimates do not satisfy the documentation requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_19",
      question: "Under DNV SM.1, how frequently must written staffing plans be reviewed?",
      options: [
        "Every 5 years",
        "At least annually",
        "Only when nursing leadership changes",
        "Every 3 years",
      ],
      correctIndex: 1,
      explanation: "DNV SM.1 requires written staffing plans to be reviewed at least annually. Annual review ensures that staffing plans reflect current patient volume, acuity trends, regulatory requirements, and organizational needs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ns_20",
      question: "Which of the following BEST describes the relationship between patient acuity and nursing staffing under DNV NS.2?",
      options: [
        "Patient count determines staffing; acuity is only considered for ICU patients",
        "Patient acuity scores must drive staffing decisions with real-time adjustment capability",
        "Staffing is based on historical averages, not real-time acuity",
        "Acuity is assessed weekly and staffing is adjusted monthly",
      ],
      correctIndex: 1,
      explanation: "DNV NS.2 requires patient acuity to drive staffing decisions in real time. The acuity measurement system must translate patient care complexity into staffing requirements and enable adjustments as patient conditions change during a shift.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
