import type { Level } from "./schema";

export const dnvSpLevel: Level = {
  id: "dnv_sp",
  module: "dnv",
  name: "Specialty Services",
  description: "DNV DIAS Sections 14–24 — Standards covering obstetrics, laboratory, blood management, medical imaging, nuclear medicine, rehabilitation, emergency department, dietary, organ procurement, and restraint/seclusion.",
  icon: "Layers",
  color: "hsl(300, 50%, 45%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "SP: Specialty Clinical Services",
    plainLanguageSummary:
      "DNV's Specialty Services sections establish requirements for a broad range of clinical services beyond core hospital functions. Each specialty (obstetrics, laboratory, blood management, imaging, nuclear medicine, rehabilitation, emergency, dietary, organ procurement) must be organized, staffed, and operated according to recognized standards for that specialty. Common themes across all specialties include: director/manager qualifications, staff competency, adequate equipment, documentation requirements, and integration with the quality management system. Restraint and seclusion have specific rights, ordering, monitoring, and training requirements.",
    keyOperationalExpectations: [
      "Each specialty service operates under a qualified director/manager with defined authority.",
      "Laboratory services are certified; blood products are quality-screened and records retained 10 years.",
      "Emergency department staffed 24 hours with qualified medical and nursing staff and triage process.",
      "Dietary services include a qualified dietitian with documented nutritional assessments for at-risk patients.",
      "Restraint/seclusion requires physician order, 1-hour face-to-face evaluation, and continuous monitoring.",
      "Organ procurement policies define notification, communication, and suitability determination processes.",
    ],
    commonRiskPoints: [
      "Restraint orders not time-limited; restraints continued beyond order period without renewal.",
      "Laboratory services provided without CLIA certification or with expired certification.",
      "Blood transfusion records not retained for the required 10-year period.",
      "Dietary nutritional assessments not conducted for high-risk patients (e.g., tube feeding patients).",
    ],
    cmsTags: ["OS.1", "LS.1", "BM.1", "MI.1", "NM.1", "RS.1", "ED.1", "DS.1", "TO.1", "RT.1", "RT.2", "RT.3", "RT.4"],
  },
  studyMaterial: [
    {
      title: "Laboratory and Blood Management (LS/BM)",
      content:
        "Laboratory services must be available 24 hours (including blood gas and electrolytes) and performed in a certified laboratory (CLIA compliance). Laboratory scope must be documented and available to medical staff. A pathologist must define which tissue specimens require gross vs microscopic examination. Blood use policies must minimize unnecessary transfusions and address alternatives. Quality-assured screening for transfusion-transmissible infections (HIV, Hep B, Hep C, syphilis, and applicable others) is required. Records of blood and blood component source and disposition must be retained for at least 10 years.",
      keyPoint:
        "Lab: 24-hour availability, CLIA certified, scope documented. Blood: 10-year record retention, quality-assured screening for HIV/Hep B/Hep C/syphilis. Pathologist defines tissue examination requirements.",
    },
    {
      title: "Medical Imaging and Nuclear Medicine (MI/NM)",
      content:
        "Medical imaging services must be organized appropriately for scope and complexity with a qualified physician responsible for clinical supervision. Radiation safety programs must protect patients and staff, including protective equipment and dose monitoring. Radiologists or qualified practitioners must authenticate all interpretation reports. Imaging records must be retained at least 5 years. Nuclear medicine services require a physician qualified in nuclear medicine as director, with radioactive materials managed per national/local law. Equipment must be calibrated at least annually.",
      keyPoint:
        "Imaging: qualified physician oversight, radiation safety program, authenticated reports, 5-year record retention. Nuclear medicine: physician director qualified in nuclear medicine, annual equipment calibration.",
    },
    {
      title: "Emergency Department and Rehabilitation (ED/RS)",
      content:
        "Emergency departments must be organized and integrated with other hospital departments, under physician medical staff direction, staffed 24 hours. Qualified triage by a professional is required upon patient presentation. If no emergency services are provided, policies for emergency appraisal and referral must exist. Rehabilitation services (PT/OT/speech/audiology) must be provided by qualified practitioners under a director with appropriate qualifications. Treatment plans must include: practitioner orders, treatment type/amount/frequency, measurable goals, and results documented in the medical record.",
      keyPoint:
        "ED: 24-hour medical/nursing staffing, physician direction, qualified triage. Rehab: qualified practitioners under a director, individualized treatment plans with measurable goals in the medical record.",
    },
    {
      title: "Dietary Services (DS)",
      content:
        "Dietary services must be organized with a qualified dietitian supervising the nutritional aspects of patient care. Nutritional assessments must be conducted for patients at risk (patients requiring artificial nutrition, patients with diagnoses that compromise nutritional intake, patients with conditions impacted by nutritional intake). Therapeutic diets must be prescribed by a qualified practitioner, documented in the medical record. A therapeutic diet manual, approved by the dietitian and the organization, must be maintained and available to all relevant staff.",
      keyPoint:
        "Qualified dietitian required. Nutritional assessments for at-risk patients (tube feeding, malabsorption, diet-impacted diagnoses). Therapeutic diet manual approved by dietitian and available to all staff.",
    },
    {
      title: "Restraint and Seclusion (RT)",
      content:
        "Restraint and seclusion may only be used when clinically necessary — not for staff convenience, discipline, or retaliation. Every use requires a physician order. A 1-hour face-to-face evaluation (medical and behavioral) is required for restraint/seclusion used for violent/self-destructive behavior. Orders for violent behavior are time-limited (1-4 hours depending on patient age and type). If restraint/seclusion continues 24 hours, a face-to-face physician assessment is required before renewal. Staff must receive training before applying restraints. Use must be monitored in the quality management system.",
      keyPoint:
        "Restraint/seclusion: physician order required, 1-hour face-to-face evaluation for violent behavior, time-limited orders, 24-hour face-to-face before renewal, staff training mandatory, QM monitoring required.",
    },
  ],
  questions: [
    {
      id: "dnv_sp_01",
      question: "Under DNV BM.1, for how long must records of blood and blood component source and disposition be retained?",
      options: [
        "5 years",
        "7 years",
        "10 years",
        "3 years",
      ],
      correctIndex: 2,
      explanation: "DNV BM.1 SR.5 requires records identifying the source and disposition of all blood and blood components to be retained for no less than 10 years from the date of disposition. This 10-year requirement is longer than the general 5-year medical record retention requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_02",
      question: "Under DNV RT.4, when restraint or seclusion is used for violent behavior, a face-to-face evaluation must occur within what timeframe?",
      options: [
        "4 hours",
        "2 hours",
        "1 hour",
        "30 minutes",
      ],
      correctIndex: 2,
      explanation: "DNV RT.4 SR.1 requires a face-to-face evaluation by trained staff within 1 hour after initiation of restraint or seclusion used to manage violent or self-destructive behavior. This 1-hour evaluation includes both physical and behavioral assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_03",
      question: "A hospital provides laboratory services without current CLIA certification. Under DNV LS.1, this is:",
      options: [
        "Acceptable if the laboratory is accredited by CAP",
        "Non-compliant — all laboratory services must be performed in a certified laboratory",
        "Acceptable for point-of-care testing only",
        "Non-compliant only for high-complexity testing",
      ],
      correctIndex: 1,
      explanation: "DNV LS.1 SR.2 requires that all laboratory services provided to patients be performed in a certified laboratory. CLIA certification (or equivalent national certification) is not optional — all laboratory testing, including waived and moderate complexity, must be certified appropriately.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_04",
      question: "Under DNV RT.1, restraint may NOT be used for which of the following purposes?",
      options: [
        "Preventing patient self-harm during a violent episode",
        "Staff convenience, discipline, or retaliation",
        "Managing patient behavior that jeopardizes immediate physical safety",
        "Protecting the patient from injuring others",
      ],
      correctIndex: 1,
      explanation: "DNV RT.1 SR.1c explicitly prohibits restraint or seclusion imposed by staff as a means of coercion, discipline, convenience, or retaliation. Restraint is only permissible to manage clinically necessary situations — never for staff convenience.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_05",
      question: "The obstetric unit does not have written policies for post-partum hemorrhage management. Under DNV OS.1, this is:",
      options: [
        "Acceptable if staff are trained to manage hemorrhage",
        "Non-compliant — written intrapartum policies including post-partum hemorrhage are required",
        "Acceptable for facilities with fewer than 100 deliveries annually",
        "Non-compliant only if a post-partum hemorrhage death has occurred",
      ],
      correctIndex: 1,
      explanation: "DNV OS.1 requires obstetric services to have written policies and procedures for intrapartum care including post-partum hemorrhage management. This is explicitly listed as one of the minimum required intrapartum policies.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_06",
      question: "Under DNV DS.1, a qualified dietitian is not full-time. What must the organization ensure?",
      options: [
        "Nothing — a part-time dietitian satisfies all dietary requirements",
        "Adequate provisions for dietary consultation coverage when the dietitian is not available, including evenings and weekends",
        "A nurse with nutrition training covers dietary assessments in the dietitian's absence",
        "Dietary services can operate without a dietitian if menus are pre-approved",
      ],
      correctIndex: 1,
      explanation: "DNV DS.1 acknowledges that dietitians may not be full-time but requires that when the dietitian is not available, adequate provisions for qualified dietary consultation must be in place — including evening and weekend coverage. Nutritional needs don't stop when the dietitian leaves.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_07",
      question: "Under DNV RT.3, if restraint and seclusion are used simultaneously, how must the patient be monitored?",
      options: [
        "Every 30 minutes by trained staff",
        "Continually face-to-face or by both video and audio equipment by trained staff",
        "Hourly by the attending physician",
        "Every 15 minutes by nursing staff",
      ],
      correctIndex: 1,
      explanation: "DNV RT.3 requires continual monitoring when restraint and seclusion are used simultaneously — either continual face-to-face monitoring or continual monitoring by both video AND audio equipment in close proximity. This is the highest monitoring requirement in the restraint standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_08",
      question: "Under DNV LS.1 SR.5, who determines which tissue specimens require microscopic examination?",
      options: [
        "The hospital administrator",
        "The medical staff and a pathologist together",
        "The attending surgeon alone",
        "The nursing staff",
      ],
      correctIndex: 1,
      explanation: "DNV LS.1 SR.5 requires the organization and a pathologist to determine which tissue specimens require macroscopic (gross) examination only, and which require both macroscopic and microscopic examinations. This decision requires pathologist expertise and cannot be made by surgeons or administrators alone.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_09",
      question: "Under DNV ED.2, the emergency department must have which of the following present 24 hours a day?",
      options: [
        "A cardiologist and a radiologist",
        "A qualified member of the medical staff available to supervise emergency services",
        "A board-certified emergency physician at all times",
        "An intensivist and a hospitalist",
      ],
      correctIndex: 1,
      explanation: "DNV ED.2 requires a qualified member of the medical staff to be on premises and available to supervise emergency services 24 hours a day. The specific specialty is not mandated — the requirement is for a qualified medical staff member to be physically present and available.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_10",
      question: "A patient has been in restraint for 26 hours for management of violent behavior. Under DNV RT.4, what must occur before a new restraint order is written?",
      options: [
        "A telephone consultation with the physician",
        "A face-to-face assessment by a physician or practitioner",
        "A nursing assessment and documentation",
        "Nothing additional — the original order covers the entire episode",
      ],
      correctIndex: 1,
      explanation: "DNV RT.4 SR.2 requires that after 24 hours of restraint or seclusion for management of violent/self-destructive behavior, a face-to-face assessment by a physician or other practitioner must occur before a new order is written. Telephone consultation is not sufficient for this 24-hour assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_11",
      question: "Under DNV NM.2, radioactive materials must be prepared and labeled by whom?",
      options: [
        "Any trained nuclear medicine technologist",
        "By or under the direct supervision of an appropriately trained registered pharmacist, physician, or nuclear medicine professional",
        "Any licensed healthcare professional",
        "Only by a physician specialized in nuclear medicine",
      ],
      correctIndex: 1,
      explanation: "DNV NM.2 SR.3 requires in-house preparation of radiopharmaceuticals to be performed by, or under the direct supervision of, an appropriately trained registered pharmacist, physician, or nuclear medicine professional deemed competent by the organization.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_12",
      question: "Under DNV DS.2, therapeutic diets must be prescribed by whom?",
      options: [
        "The dietitian alone",
        "A qualified practitioner or practitioners responsible for the care of the patient",
        "The nursing staff based on the dietitian's recommendation",
        "The patient and family in consultation with dietary staff",
      ],
      correctIndex: 1,
      explanation: "DNV DS.2 SR.2 requires all therapeutic diets to be prescribed by a practitioner or practitioners responsible for the care of the patient. Dietitians may recommend dietary interventions, but the therapeutic diet order must come from a qualified prescribing practitioner.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_13",
      question: "Under DNV BM.1 SR.3, blood products must be screened for which infections at minimum?",
      options: [
        "HIV only",
        "HIV, Hepatitis B, Hepatitis C, and syphilis (Treponema pallidum) plus other relevant infections",
        "Hepatitis B and C only",
        "HIV, Hepatitis B, and influenza",
      ],
      correctIndex: 1,
      explanation: "DNV BM.1 SR.3 requires quality-assured screening for HIV, Hepatitis B, Hepatitis C, syphilis (Treponema pallidum), and where relevant, other infections that pose a risk to blood safety such as Chagas disease and malaria. The minimum list is four specific infections.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_14",
      question: "Under DNV RS.3, rehabilitation services treatment plans must include which minimum elements?",
      options: [
        "Patient name, diagnosis, and insurance information",
        "Practitioner order, type/amount/frequency of service, measurable goals, and documented results",
        "A list of approved exercises and weekly progress photos",
        "Insurance authorization and expected length of service",
      ],
      correctIndex: 1,
      explanation: "DNV RS.3 requires rehabilitation treatment plans to include: the practitioner's order, type/amount/frequency/duration of services, measurable short and long-term goals, documented results and notes, and provision for plan reviews and revisions. All elements must appear in the medical record.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_15",
      question: "Under DNV RT.6, who must provide the training for staff who apply restraints?",
      options: [
        "Any senior clinical staff member",
        "Individuals qualified by education, training, and experience in techniques for addressing patient behaviors",
        "The hospital's legal team",
        "Any licensed nurse with 5 years of experience",
      ],
      correctIndex: 1,
      explanation: "DNV RT.6 SR.4 requires that individuals providing restraint training be qualified through education, training, and experience in techniques used to address patients' behaviors. Trainer qualification is an explicit requirement — not just any senior staff member can conduct restraint training.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_16",
      question: "Under DNV MI.8, radiology records must be retained for at least how long?",
      options: [
        "3 years",
        "5 years",
        "7 years",
        "10 years",
      ],
      correctIndex: 1,
      explanation: "DNV MI.8 SR.2 requires radiology records (copies of reports, films, scans, and other imaging records) to be maintained for at least 5 years, or in accordance with national/local laws if those laws require a longer period.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_17",
      question: "Under DNV DS.1, which of the following patients requires a nutritional assessment?",
      options: [
        "A patient admitted for elective knee replacement with no nutritional concerns",
        "A patient requiring total parenteral nutrition (TPN)",
        "A patient admitted for routine cardiac monitoring",
        "A patient admitted for observation after a minor procedure",
      ],
      correctIndex: 1,
      explanation: "DNV DS.1 requires nutritional assessments for patients at risk including ALL patients requiring artificial nutrition by any means (tube feeding, TPN, PPN). TPN represents one of the clearest indicators of nutritional compromise, triggering mandatory assessment.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_18",
      question: "Under DNV TO.1, what must the organ procurement policy address regarding deceased patients?",
      options: [
        "Billing procedures for organ procurement services",
        "Timely notification of the procurement organization for all individuals whose death is imminent or who have died in the organization",
        "Autopsy requirements for all deceased patients",
        "Compensation for organ donors' families",
      ],
      correctIndex: 1,
      explanation: "DNV TO.1 SR.1a requires the organ procurement policy to address timely notification of the department or organization responsible for procurement for all individuals whose death is imminent or who have died in the organization. This ensures no potential donor is missed.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_19",
      question: "Under DNV RT.5, the use of restraint and seclusion must be monitored as part of which organizational function?",
      options: [
        "The security department's incident tracking",
        "The hospital's Quality Management System",
        "The pharmacy's medication management program",
        "The human resources department's workforce tracking",
      ],
      correctIndex: 1,
      explanation: "DNV RT.5 SR.1 requires the use of restraint and seclusion to be monitored and evaluated on a continual basis as part of the hospital's Quality Management System. Restraint/seclusion data must be aggregated, trended, and analyzed for patterns — making it a quality management function.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_sp_20",
      question: "A hospital provides nuclear medicine services but nuclear medicine equipment has not been calibrated in 2 years. Under DNV NM.3, this is:",
      options: [
        "Acceptable if the equipment appears to be functioning correctly",
        "Non-compliant — nuclear medicine equipment must be calibrated at least annually",
        "Acceptable if the equipment is maintained by the manufacturer",
        "Non-compliant only for gamma cameras used in cardiac imaging",
      ],
      correctIndex: 1,
      explanation: "DNV NM.3 SR.2 requires nuclear medicine equipment to be maintained in safe operating condition and inspected, tested, and calibrated at least annually by qualified personnel. Annual calibration is a minimum requirement — a 2-year gap is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
