import type { Level } from "./schema";

export const dnvQmLevel: Level = {
  id: "dnv_qm",
  module: "dnv",
  name: "Quality Management",
  description: "DNV DIAS Section 3 — QM standards for quality management systems, QAPI, performance improvement, and root cause analysis.",
  icon: "BarChart3",
  color: "hsl(210, 65%, 45%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "QM: Quality Management",
    plainLanguageSummary:
      "DNV's Quality Management section requires hospitals to maintain a comprehensive, organization-wide quality management system (QMS) based on continuous quality improvement principles. The QMS must cover all departments and services, use data-driven performance measurement, include root cause analysis for adverse events, and report findings to the governing body. DNV uniquely requires integration with ISO 9001 quality principles and a formal QAPI (Quality Assessment and Performance Improvement) program.",
    keyOperationalExpectations: [
      "A written, organization-wide Quality Management Plan updated at least annually.",
      "Quality indicators are selected, measured, and trended across all patient care areas.",
      "Root cause analysis (RCA) is conducted for all sentinel events and near misses.",
      "Quality data is reported to the governing body and medical staff at defined intervals.",
      "Performance improvement projects follow a structured methodology (PDCA/PDSA or equivalent).",
      "Patient safety goals are integrated into the QMS and tracked over time.",
    ],
    commonRiskPoints: [
      "QM plan exists but is not updated annually or lacks measurable goals.",
      "RCA conducted but corrective actions are not tracked to completion.",
      "Quality data reported to governance but does not include trending or benchmarking.",
      "PI projects lack a defined methodology, baseline, intervention, or re-measurement phase.",
    ],
    cmsTags: ["QM.1", "QM.2", "QM.3", "QM.4", "QM.5", "QM.6", "QM.7", "QM.8", "QM.9", "QM.10"],
  },
  studyMaterial: [
    {
      title: "QM.1 — Organization-Wide Quality Management System",
      content:
        "DNV requires that each hospital maintain a comprehensive, organization-wide quality management system (QMS). The QMS must cover all hospital departments and services, be based on continuous quality improvement principles, and be described in a written Quality Management Plan. The plan must define scope, objectives, methodology, data sources, and reporting lines. It must be reviewed and updated at least annually and approved by the governing body.",
      keyPoint:
        "The QMS must be organization-wide, in writing, updated annually, and approved by the governing body. Partial or department-specific QM systems do not satisfy this standard.",
    },
    {
      title: "QM.2 — Performance Measurement and Indicators",
      content:
        "The organization must select quality indicators that reflect the scope and complexity of services. Indicators must be measurable, monitored on an ongoing basis, and used to drive improvement. DNV expects hospitals to use both internal data and external benchmarks. Data must be aggregated, trended over time, and analyzed to identify patterns. Indicator selection must include patient safety, clinical outcomes, patient satisfaction, and operational performance dimensions.",
      keyPoint:
        "Quality indicators must be measurable, trended over time, benchmarked externally, and span patient safety, outcomes, satisfaction, and operations.",
    },
    {
      title: "QM.3 — Root Cause Analysis and Sentinel Events",
      content:
        "A root cause analysis (RCA) must be performed for every sentinel event and near miss. The RCA process must be systematic, interdisciplinary, and focused on identifying system-level causes rather than individual blame. Corrective/preventive actions (CAPA) derived from the RCA must be documented, assigned owners, given timelines, and tracked through to verification of effectiveness. The hospital must have a defined list of sentinel events that trigger mandatory RCA.",
      keyPoint:
        "RCA must be systematic, interdisciplinary, and system-focused. CAPA must be tracked to verified effectiveness — not just documented.",
    },
    {
      title: "QM.4 — Reporting to Governing Body and Medical Staff",
      content:
        "Quality data, performance improvement results, and patient safety findings must be reported to both the governing body and the medical staff at defined intervals. The governing body must actively engage with quality reports — reviewing trends, approving corrective actions, and holding leadership accountable. Passive receipt of reports without documented discussion or action does not satisfy this standard.",
      keyPoint:
        "Quality data must reach governing body AND medical staff at defined intervals, with documented discussion and action — not passive receipt.",
    },
    {
      title: "QM.5 — QAPI Program Structure",
      content:
        "DNV requires a formal Quality Assessment and Performance Improvement (QAPI) program that integrates quality assessment with performance improvement. The QAPI program must include data collection, analysis, goal-setting, intervention, and re-measurement. The program must be multidisciplinary and include physician participation. At minimum, one structured PI project must be active at all times, with documentation of each phase.",
      keyPoint:
        "QAPI requires active, ongoing PI projects with all phases documented: baseline → intervention → re-measurement. Physician participation is mandatory.",
    },
  ],
  questions: [
    {
      id: "dnv_qm_01",
      question: "Under DNV QM.1, how frequently must the hospital's Quality Management Plan be reviewed and updated?",
      options: [
        "Every two years",
        "At least annually",
        "Every three years",
        "Only when deficiencies are identified",
      ],
      correctIndex: 1,
      explanation: "DNV QM.1 requires the Quality Management Plan to be reviewed and updated at least annually and approved by the governing body. Annual review ensures the plan remains current with organizational changes and emerging quality priorities.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_02",
      question: "A hospital's Quality Management System covers only the clinical departments but not environmental services or dietary. Which DNV standard is most directly violated?",
      options: [
        "QM.3 — Root Cause Analysis",
        "QM.1 — Organization-Wide QMS",
        "QM.5 — QAPI Program",
        "QM.4 — Governing Body Reporting",
      ],
      correctIndex: 1,
      explanation: "QM.1 requires the QMS to be organization-wide, covering all hospital departments and services. Excluding non-clinical departments like environmental services or dietary violates the organization-wide requirement of QM.1.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_03",
      question: "After conducting an RCA for a sentinel event, the hospital documents corrective actions but does not assign owners or timelines. What is the critical deficiency?",
      options: [
        "The RCA was not interdisciplinary enough",
        "Corrective actions are not tracked to verified effectiveness",
        "The sentinel event was not reported to DNV",
        "Quality indicators were not updated after the event",
      ],
      correctIndex: 1,
      explanation: "DNV QM.3 requires that corrective/preventive actions derived from RCA be assigned owners, given timelines, and tracked to verified effectiveness. Documenting actions without tracking completion fails the CAPA requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_04",
      question: "What does DNV require regarding quality data reported to the governing body?",
      options: [
        "Reports may be emailed without a meeting",
        "Passive receipt of reports is sufficient if documented",
        "Governing body must actively engage with documented discussion and action",
        "Reports are only required annually",
      ],
      correctIndex: 2,
      explanation: "DNV QM.4 requires active engagement — the governing body must review trends, approve corrective actions, and hold leadership accountable with documented discussion. Passive receipt of reports without discussion does not satisfy this standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_05",
      question: "A performance improvement project shows baseline data and an intervention but has no re-measurement phase after 6 months. Under DNV QM.5, this project is:",
      options: [
        "Compliant if the intervention was multidisciplinary",
        "Non-compliant — re-measurement is a required phase",
        "Compliant if reported to the governing body",
        "Non-compliant only if the intervention failed",
      ],
      correctIndex: 1,
      explanation: "DNV QAPI requires all phases: baseline → intervention → re-measurement. A project without re-measurement has not demonstrated whether the intervention was effective, which is the core purpose of the PI methodology.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_06",
      question: "Which of the following best describes DNV's expectation for quality indicators under QM.2?",
      options: [
        "Indicators are selected once and used indefinitely",
        "Indicators must only reflect patient satisfaction scores",
        "Indicators must be measurable, trended over time, and benchmarked externally",
        "Indicators are optional if the hospital has a good safety record",
      ],
      correctIndex: 2,
      explanation: "QM.2 requires that quality indicators be measurable, monitored continuously, trended over time, and compared against external benchmarks. They must span patient safety, clinical outcomes, satisfaction, and operations.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_07",
      question: "DNV's QAPI program requires physician participation. If a hospital's PI committee has no physician members, this represents a deficiency under which standard?",
      options: [
        "QM.3 — Root Cause Analysis",
        "QM.2 — Performance Indicators",
        "QM.5 — QAPI Program Structure",
        "QM.1 — Organization-Wide QMS",
      ],
      correctIndex: 2,
      explanation: "QM.5 requires that the QAPI program be multidisciplinary and include physician participation. A PI committee without physician members fails the multidisciplinary requirement of the QAPI program structure.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_08",
      question: "A root cause analysis focuses on identifying which staff member made the error rather than system-level causes. Under DNV QM.3, this approach is:",
      options: [
        "Acceptable if the staff member is disciplined",
        "A violation — RCA must be system-focused, not blame-focused",
        "Acceptable for medication errors only",
        "Compliant if the RCA team was interdisciplinary",
      ],
      correctIndex: 1,
      explanation: "DNV QM.3 requires RCA to focus on system-level causes, not individual blame. An RCA that primarily identifies the individual who made the error without examining system factors (policies, design, training, communication) does not meet the standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_09",
      question: "How does DNV's QM approach differ from traditional quality oversight in its philosophical foundation?",
      options: [
        "DNV focuses on punitive responses to poor outcomes",
        "DNV integrates ISO 9001 quality principles and continuous improvement methodology",
        "DNV requires only annual quality reviews",
        "DNV relies solely on external audits for quality assurance",
      ],
      correctIndex: 1,
      explanation: "DNV uniquely integrates ISO 9001 quality management principles into its hospital accreditation standards, emphasizing continuous quality improvement as a systematic, documented methodology rather than episodic review.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_10",
      question: "The governing body reviews quality reports but there is no documentation that they discussed trends or approved corrective actions. Under DNV QM.4, this is:",
      options: [
        "Compliant if reports are filed in meeting minutes",
        "Non-compliant — active engagement with documented discussion is required",
        "Compliant if the CMO is present at governing body meetings",
        "Non-compliant only if sentinel events occurred during that period",
      ],
      correctIndex: 1,
      explanation: "DNV QM.4 requires active engagement — not passive receipt. The governing body must review trends, discuss findings, and approve corrective actions with this engagement documented in meeting minutes.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_11",
      question: "Under DNV standards, which of the following events MUST trigger a root cause analysis?",
      options: [
        "Any patient complaint about wait times",
        "Sentinel events and near misses",
        "Any medication administered late",
        "Any fall without injury",
      ],
      correctIndex: 1,
      explanation: "DNV QM.3 requires RCA for all sentinel events and near misses. These represent the highest-risk events where system analysis is most critical for preventing recurrence.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_12",
      question: "A hospital tracks quality indicators but never compares them to external benchmarks. Under DNV QM.2, what is lacking?",
      options: [
        "Nothing — internal trending is sufficient",
        "External benchmarking, which is required to give indicators meaningful context",
        "More frequent data collection",
        "Governing body approval of each indicator",
      ],
      correctIndex: 1,
      explanation: "DNV QM.2 expects hospitals to use external benchmarks in addition to internal trending. Benchmarking provides context for whether performance is acceptable relative to peer organizations and national standards.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_13",
      question: "A Quality Management Plan is approved by the CEO but not the governing body. Under DNV QM.1, this is:",
      options: [
        "Acceptable — CEO approval satisfies the requirement",
        "Non-compliant — governing body approval is required",
        "Acceptable if the governing body is informed at the next meeting",
        "Non-compliant only if the plan hasn't been updated in over 2 years",
      ],
      correctIndex: 1,
      explanation: "DNV QM.1 requires the Quality Management Plan to be approved by the governing body, not just administrative leadership. Governing body accountability for quality is a core DNV principle.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_14",
      question: "Which methodology does DNV most closely align with for performance improvement projects?",
      options: [
        "Lean manufacturing only",
        "Six Sigma DMAIC exclusively",
        "PDCA/PDSA or equivalent structured improvement methodology",
        "ISO 14001 environmental management",
      ],
      correctIndex: 2,
      explanation: "DNV QM.5 requires structured PI methodology such as PDCA (Plan-Do-Check-Act) or PDSA (Plan-Do-Study-Act). While other methods like Lean or Six Sigma may be used, the key is a systematic, documented approach with all phases.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_15",
      question: "Quality data is reported to the governing body but not to the medical staff. Under DNV QM.4, this is:",
      options: [
        "Acceptable — governing body reporting satisfies the standard",
        "Non-compliant — both governing body AND medical staff must receive quality data",
        "Acceptable if medical staff attend governing body meetings",
        "Non-compliant only if patient harm occurred",
      ],
      correctIndex: 1,
      explanation: "DNV QM.4 requires quality data to be reported to both the governing body AND the medical staff at defined intervals. Reporting to only one of these bodies does not satisfy the dual reporting requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_16",
      question: "A hospital has one active PI project addressing medication errors. Under DNV QAPI requirements, is this sufficient?",
      options: [
        "Yes, one active project satisfies the minimum requirement",
        "No, at least three PI projects must be active simultaneously",
        "Yes, but only if it involves physicians",
        "No, PI projects are only required when deficiencies are cited",
      ],
      correctIndex: 0,
      explanation: "DNV QM.5 requires at minimum one active, structured PI project at all times with all phases documented. While more projects may demonstrate a stronger QAPI program, one active, fully documented project meets the minimum standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_17",
      question: "An organization conducts an RCA but only includes nursing staff, excluding physicians and pharmacy. Under DNV QM.3, what is the deficiency?",
      options: [
        "The RCA team must be interdisciplinary — excluding physicians and pharmacy is a deficiency",
        "There is no deficiency if nursing staff identified the cause",
        "The deficiency is only that pharmacy was excluded",
        "RCA teams are not required to be interdisciplinary under DNV",
      ],
      correctIndex: 0,
      explanation: "DNV QM.3 requires the RCA process to be interdisciplinary. For a medication-related sentinel event, excluding pharmacy and physicians would provide an incomplete system analysis and fails the interdisciplinary requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_18",
      question: "Which of the following quality dimensions must be included in indicator selection under DNV QM.2?",
      options: [
        "Financial performance only",
        "Patient safety, clinical outcomes, patient satisfaction, and operational performance",
        "Patient satisfaction and financial performance only",
        "Clinical outcomes and staff satisfaction only",
      ],
      correctIndex: 1,
      explanation: "DNV QM.2 requires quality indicators to span multiple dimensions: patient safety, clinical outcomes, patient satisfaction, and operational performance. A one-dimensional indicator set does not satisfy this multidimensional requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_19",
      question: "A corrective action from an RCA was implemented 6 months ago, but no follow-up evaluation of its effectiveness has been conducted. Under DNV QM.3, this represents:",
      options: [
        "Acceptable if the original event has not recurred",
        "A deficiency — effectiveness verification is required for all CAPA",
        "Acceptable if the action was physician-approved",
        "A deficiency only if the sentinel event involved patient death",
      ],
      correctIndex: 1,
      explanation: "DNV QM.3 requires CAPA to be tracked through to verified effectiveness. Simply implementing an action without verifying it worked is insufficient. Effectiveness verification closes the loop on the RCA process.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_qm_20",
      question: "Under DNV's quality framework, what distinguishes quality assessment from quality improvement?",
      options: [
        "Quality assessment is ongoing; quality improvement is one-time",
        "Assessment identifies current performance; improvement takes structured action to change it",
        "Quality improvement is only for clinical departments",
        "There is no meaningful distinction under DNV standards",
      ],
      correctIndex: 1,
      explanation: "QAPI integrates both: quality assessment identifies what current performance looks like (through data collection and analysis), while quality improvement implements structured interventions to change performance. Both elements are required — assessment without improvement is just data collection.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
