import type { Level } from "./schema";

export const dnvIcLevel: Level = {
  id: "dnv_ic",
  module: "dnv",
  name: "Infection Prevention & Control",
  description: "DNV DIAS Section 25 — IC standards for infection control program organization, HAI prevention, surveillance, MDROs, and reporting.",
  icon: "Shield",
  color: "hsl(140, 55%, 38%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "IC: Infection Prevention & Control",
    plainLanguageSummary:
      "DNV's Infection Control section requires hospitals to maintain a comprehensive, organization-wide infection prevention and control (IPC) program led by a qualified Infection Control Officer (ICO). The program must identify, report, investigate, prevent, and control infections and communicable diseases in both patients and staff. Active surveillance is required for HAIs (surgical site infections, CLABSI, CAUTI, VAP). MDROs require specific protocols. Data must be reported to an oversight group at minimum quarterly. The IPC program must be integrated with the quality management system.",
    keyOperationalExpectations: [
      "A designated Infection Control Officer (ICO) with defined scope of responsibilities.",
      "Organization-wide IPC program covering all patient care and support areas.",
      "Active surveillance for HAIs including SSIs, CLABSI, CAUTI, VAP, and MDRO.",
      "Hand hygiene compliance monitored and non-compliance addressed through QI.",
      "IPC data reported to oversight group (Infection Control Committee) at minimum quarterly.",
      "IPC program integrated with the quality management system and reported to medical staff and leadership.",
    ],
    commonRiskPoints: [
      "IPC program exists but does not cover all areas (e.g., dietary, environmental services excluded).",
      "HAI surveillance data collected but not reported to the Infection Control Committee quarterly.",
      "ICO appointed but scope of responsibilities not formally defined in writing.",
      "Hand hygiene program in place but compliance data not collected or acted upon.",
    ],
    cmsTags: ["IC.1", "IC.2", "IC.3", "IC.4", "IC.5", "IC.6", "IC.7"],
  },
  studyMaterial: [
    {
      title: "IC.1 — IPC Program Organization",
      content:
        "The hospital must maintain a comprehensive, organization-wide infection prevention and control program. The program must identify, report, investigate, prevent, and control infections and communicable diseases in both inpatient and outpatient populations, as well as hospital staff. The IPC program must be described in written policies and procedures, cover all hospital departments and locations, and include orientation of all new personnel (including contract staff, students, and volunteers). The Infection Control Officer must have a defined scope of responsibilities in writing.",
      keyPoint:
        "IPC must be organization-wide, cover staff AND patients (in/outpatient), include written scope for the ICO, and orient ALL new personnel including contractors and volunteers.",
    },
    {
      title: "IC.2 — HAI Prevention Strategies",
      content:
        "The IPC program must include specific mitigation strategies for healthcare-associated infections: (1) Surgical site infection (SSI) prevention including prophylactic antibiotic protocols; (2) Central line-associated bloodstream infection (CLABSI) bundle including aseptic insertion, line care, and prompt removal; (3) Catheter-associated urinary tract infection (CAUTI) prevention; (4) Ventilator-associated pneumonia (VAP) prevention; (5) Hand hygiene promotion including alcohol-based hand rub; (6) MDRO control including MRSA, C. diff, VRE, and MDRO gram-negatives; (7) Isolation protocols.",
      keyPoint:
        "Seven specific HAI categories require documented prevention strategies: SSI, CLABSI, CAUTI, VAP, hand hygiene, MDROs, and isolation protocols. Each requires a bundle or protocol.",
    },
    {
      title: "IC.3 — Active Surveillance",
      content:
        "Active surveillance requires the organization to proactively seek and identify infections rather than passively waiting for reports. Surveillance methods include: obtaining and reviewing infection data, monitoring aseptic practice, and using microbiological cultures from patients and the environment as indicated. Surveillance must cover all areas where infections could occur, including food service, refrigerators, ice machines, ventilation systems, autoclave rooms, surgical areas, and central supply. Data must be analyzed for patterns and trends.",
      keyPoint:
        "Active surveillance = proactive data collection across ALL areas. Surveillance extends to food service, air handlers, autoclave rooms, and supply storage — not just patient care areas.",
    },
    {
      title: "IC.4 — Incident Log and Reporting",
      content:
        "The organization must maintain a log of all incidents related to infections and communicable diseases for both patients and staff (including patient care and non-patient care staff, employees, contractors, and volunteers). The log must be secure, protected from unauthorized access, up-to-date, and readily accessible. To protect privacy, codes may be used instead of names. IPC data must be reported to the IPC oversight group (e.g., Infection Control Committee) at minimum quarterly. Reporting must also occur to local health authorities as required by law.",
      keyPoint:
        "Infection log must cover ALL persons (patients, staff, volunteers, contractors). Quarterly reporting to IPC Committee is minimum. Mandatory reporting to local health authorities required.",
    },
    {
      title: "IC.5 — Integration with QMS and Leadership",
      content:
        "The IPC program must be integrated with the organization's quality management system (QMS). IPC findings must be reported to the medical staff and leadership to ensure corrective actions are implemented and effective. The IPC program must include a process for coordinating with national and local emergency preparedness and health authorities to address communicable disease threats, bioterrorism, and outbreaks. The program must be evaluated on an ongoing basis and revised as necessary based on the evaluation.",
      keyPoint:
        "IPC is not standalone — it must integrate with QMS, report to medical staff AND leadership, and coordinate with public health authorities for outbreaks and bioterrorism.",
    },
  ],
  questions: [
    {
      id: "dnv_ic_01",
      question: "Under DNV IC.1, the IPC program must include orientation of which personnel?",
      options: [
        "Permanent employees only",
        "All new hospital personnel including contract staff, students, and volunteers",
        "Clinical staff only — non-clinical personnel are excluded",
        "Employees who directly handle infectious materials",
      ],
      correctIndex: 1,
      explanation: "DNV IC.1 requires IPC orientation for all new hospital personnel, including contract staff, students, and volunteers. Anyone entering the hospital environment can be a vector for infection transmission — orientation must be universal.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_02",
      question: "The hospital's IPC program covers clinical areas but excludes the dietary department and housekeeping. Under DNV IC.1, this is:",
      options: [
        "Acceptable — non-clinical areas have lower infection risk",
        "Non-compliant — the IPC program must be organization-wide covering all departments",
        "Acceptable if food service staff receive HACCP training",
        "Non-compliant only if a foodborne outbreak has occurred",
      ],
      correctIndex: 1,
      explanation: "DNV IC.1 requires the IPC program to be organization-wide, covering all hospital departments and locations. Dietary, housekeeping, and other support areas are significant sources of infection transmission risk and must be included in the IPC program.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_03",
      question: "Under DNV IC.4, how frequently must IPC data be reported to the Infection Control Committee?",
      options: [
        "Annually",
        "At minimum quarterly",
        "Monthly",
        "Semi-annually",
      ],
      correctIndex: 1,
      explanation: "DNV IC.4 requires IPC data to be reported to the organizational IPC oversight group at minimum quarterly. Quarterly reporting ensures that infection trends are identified and addressed in near-real time, not just at annual reviews.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_04",
      question: "Which of the following is NOT a specific HAI category requiring a documented prevention strategy under DNV IC.2?",
      options: [
        "Central line-associated bloodstream infection (CLABSI)",
        "Patient falls associated with infection",
        "Surgical site infection (SSI)",
        "Catheter-associated urinary tract infection (CAUTI)",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 requires documented prevention strategies for SSI, CLABSI, CAUTI, VAP, hand hygiene, MDROs, and isolation. Patient falls are a safety concern but not an infection category — falls associated with infection is not an IC.2 category.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_05",
      question: "The hospital conducts active surveillance for HAIs in patient care areas but not in food service or supply storage areas. Under DNV IC.3, this is:",
      options: [
        "Acceptable — active surveillance applies only to patient care areas",
        "Non-compliant — active surveillance must extend to all areas where infections could occur",
        "Acceptable if no outbreaks have been linked to environmental sources",
        "Non-compliant only if the facility has a kitchen",
      ],
      correctIndex: 1,
      explanation: "DNV IC.3 requires active surveillance to cover all areas where infections could occur, including food service, refrigerators, ice machines, ventilation systems, autoclave rooms, and supply storage. Environmental contamination is a significant source of HAIs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_06",
      question: "The hospital's IPC program has no documented CLABSI prevention bundle. Under DNV IC.2, this is:",
      options: [
        "Acceptable if nursing education covers central line care",
        "Non-compliant — a CLABSI prevention protocol or bundle is required",
        "Acceptable for facilities with fewer than 10 ICU beds",
        "Non-compliant only if CLABSI rates exceed national benchmarks",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 requires a specific documented CLABSI prevention strategy — this includes a bundle or protocol addressing aseptic insertion, ongoing line care, and prompt removal when the line is no longer needed. Education alone without a documented protocol is insufficient.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_07",
      question: "An infection log is maintained but is accessible to any staff member who wants to view it. Under DNV IC.4, what is the concern?",
      options: [
        "No concern — transparency is encouraged in IPC",
        "The log must be secure and protected from unauthorized access to protect patient privacy",
        "Concern only if the log contains patient names rather than coded identifiers",
        "No concern if the facility has a HIPAA policy",
      ],
      correctIndex: 1,
      explanation: "DNV IC.4 requires the infection log to be secure and protected from unauthorized access. Access must be limited to authorized personnel. Broad access creates privacy risks for identified patients and staff. The organization may use codes instead of names to protect privacy.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_08",
      question: "The Infection Control Officer has been appointed but their scope of responsibilities has never been formally documented. Under DNV IC.1, this is:",
      options: [
        "Acceptable if the ICO has appropriate credentials",
        "Non-compliant — the ICO's scope of responsibilities must be defined in writing",
        "Acceptable if the ICO reports to the CMO",
        "Non-compliant only if the hospital has had an outbreak",
      ],
      correctIndex: 1,
      explanation: "DNV IC.1 requires the Infection Control Officer to have a designated, written scope of responsibilities. Without a written scope, accountability for specific IPC functions is unclear, creating gaps in program oversight.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_09",
      question: "Under DNV IC.5, IPC program findings must be reported to which bodies to ensure corrective actions are implemented?",
      options: [
        "The Infection Control Committee only",
        "The medical staff AND organizational leadership",
        "The governing body only",
        "External regulatory agencies only",
      ],
      correctIndex: 1,
      explanation: "DNV IC.5 requires IPC findings to be reported to both the medical staff and organizational leadership. This dual reporting ensures that both clinical and administrative corrective actions can be implemented and that accountability exists at multiple organizational levels.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_10",
      question: "A local health authority identifies a potential outbreak of a communicable disease in the community. Under DNV IC.5, what is the hospital required to do?",
      options: [
        "Wait for official direction before taking any action",
        "Coordinate with local health authorities to address the communicable disease threat",
        "Issue a public notice about the outbreak",
        "No specific action is required unless hospital patients are affected",
      ],
      correctIndex: 1,
      explanation: "DNV IC.5 requires the IPC program to include coordination with national and local emergency preparedness and health authorities to address communicable disease threats, bioterrorism, and outbreaks. Proactive coordination is required — not reactive response after hospital cases appear.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_11",
      question: "Hand hygiene compliance monitoring data has been collected for 6 months but no action has been taken despite compliance rates below 60%. Under DNV IC.2, what is required?",
      options: [
        "No action — data collection alone satisfies the surveillance requirement",
        "Quality improvement action — data showing low compliance must drive corrective measures",
        "Action is required only if a HAI is linked to hand hygiene non-compliance",
        "A written reminder to staff about hand hygiene importance",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 requires the IPC program to address hand hygiene compliance through promotion AND action. Data showing compliance rates below acceptable levels must drive quality improvement interventions — data collection without action does not fulfill the IPC requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_12",
      question: "The hospital has a patient colonized with C. difficile who is not placed in contact precautions. Under DNV IC.2, what specific requirement is violated?",
      options: [
        "The CLABSI prevention requirement",
        "The isolation protocol requirement for MDROs",
        "The surgical prophylaxis protocol",
        "The VAP prevention bundle requirement",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 requires isolation protocols for MDROs including Clostridium difficile (C. diff). C. diff requires contact precautions as part of the MDRO control program. Failure to implement appropriate isolation violates the MDRO isolation protocol requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_13",
      question: "Under DNV IC.3, active surveillance requires the organization to use microbiological cultures in which situations?",
      options: [
        "Only when a patient has a confirmed infection",
        "As indicated by the surveillance program from patients and the environment",
        "Only in the ICU and surgical units",
        "Only when the health department requests cultures",
      ],
      correctIndex: 1,
      explanation: "DNV IC.3 requires authority and protocols for obtaining microbiological cultures from both patients and the environment as indicated by the surveillance program. Environmental cultures (e.g., water systems, surfaces) are part of active surveillance, not just cultures from symptomatic patients.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_14",
      question: "IPC data is reported to the Infection Control Committee but never provided to medical staff leadership. Under DNV IC.5, this is:",
      options: [
        "Acceptable — ICC reporting satisfies all IPC reporting requirements",
        "Non-compliant — IPC must report to both ICC AND medical staff/organizational leadership",
        "Acceptable if the CMO is an ICC member",
        "Non-compliant only if the medical staff requested the data",
      ],
      correctIndex: 1,
      explanation: "DNV IC.5 requires IPC findings to reach the medical staff and organizational leadership, not just the Infection Control Committee. Medical staff and leadership accountability for corrective actions requires that they receive and act on IPC data.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_15",
      question: "Under DNV IC.2, the SSI prevention program requires prophylactic antibiotic administration. What specific aspect does DNV emphasize?",
      options: [
        "Using the most broad-spectrum antibiotic available",
        "Administering the antibiotic prophylaxis for appropriate procedures AND discontinuing it appropriately after surgery",
        "Administering antibiotics for 7 days after every surgical procedure",
        "Using patient-specific antibiotic selection based on body weight",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 specifically requires protocols for both the appropriate administration of prophylactic antibiotics AND their appropriate discontinuation after surgery. Prolonged antibiotic use contributes to MDRO development — both initiation and discontinuation must be protocol-driven.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_16",
      question: "The hospital infection log includes only patients, not staff members with infections. Under DNV IC.4, this is:",
      options: [
        "Acceptable — the infection log is for patients only",
        "Non-compliant — the log must include infections in both patients AND staff",
        "Acceptable if staff infections are tracked in the HR system",
        "Non-compliant only for communicable diseases in staff",
      ],
      correctIndex: 1,
      explanation: "DNV IC.4 requires the infection log to include infections and communicable diseases in both patients and staff — including patient care staff, non-patient care staff, employees, contract staff, and volunteers. A patient-only log is incomplete.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_17",
      question: "Under DNV IC.1, the IPC program must include a process for which of the following regarding local health authorities?",
      options: [
        "Invoicing health authorities for IPC consultation services",
        "Meeting the reporting requirements of the local health authority",
        "Hiring local health department staff as IPC consultants",
        "Submitting annual IPC reports to the health department",
      ],
      correctIndex: 1,
      explanation: "DNV IC.1 requires the IPC program to include a procedure for meeting the reporting requirements of the local health authority. Many infections and communicable diseases are legally required to be reported to local health departments — the IPC program must ensure this occurs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_18",
      question: "Safe injection practices are required under DNV IC.2 to prevent which type of infection?",
      options: [
        "Surgical site infections",
        "Bloodborne pathogen transmission through contaminated needles or multi-dose vials",
        "Urinary tract infections from catheter use",
        "Respiratory infections from ventilators",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 specifically includes a Safe Injection Practice Program as a required element of HAI mitigation. Safe injection practices prevent bloodborne pathogen transmission through reuse of needles, contamination of multi-dose vials, and other injection-related practices.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_19",
      question: "Under DNV IC.5, the IPC program must be evaluated on what basis?",
      options: [
        "Only during accreditation survey preparation",
        "On an ongoing basis with revisions made as necessary based on the evaluation",
        "Every 5 years with a formal program review",
        "Only when an outbreak occurs",
      ],
      correctIndex: 1,
      explanation: "DNV IC.5 requires the IPC program to be evaluated on an ongoing basis and revised as necessary based on evaluation findings. Continuous evaluation — not just periodic formal review — is required to maintain a responsive and effective IPC program.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ic_20",
      question: "The hospital uses personal protective equipment (PPE) inconsistently during isolation procedures for immunosuppressed patients. Under DNV IC.2, what specific protocol addresses this?",
      options: [
        "The CLABSI bundle protocol",
        "Isolation procedures and requirements for immunosuppressed patients",
        "The environmental surface disinfection protocol",
        "The surgical hand antisepsis protocol",
      ],
      correctIndex: 1,
      explanation: "DNV IC.2 specifically requires isolation procedures and requirements for immunosuppressed patients as part of the HAI mitigation strategy. Immunocompromised patients require protective (reverse) isolation to prevent opportunistic infections — inconsistent PPE use violates this specific requirement.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
