import type { Level } from "./schema";

export const dnvMsLevel: Level = {
  id: "dnv_ms",
  module: "dnv",
  name: "Medical Staff",
  description: "DNV DIAS Section 7 — MS standards for medical staff organization, credentialing, privileging, peer review, and clinical accountability.",
  icon: "Stethoscope",
  color: "hsl(160, 55%, 40%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "MS: Medical Staff",
    plainLanguageSummary:
      "DNV's Medical Staff section establishes requirements for how hospitals organize, credential, privilege, and maintain accountability for all practitioners who provide patient care. The medical staff must be formally organized with bylaws, officers, and standing committees. Every practitioner must be credentialed and granted specific clinical privileges based on demonstrated competence. Ongoing performance evaluation (OPPE) and focused evaluation (FPPE) are required for all privileged providers. Peer review must be structured and used in privileging decisions.",
    keyOperationalExpectations: [
      "All practitioners are credentialed through a primary source verification process.",
      "Clinical privileges are granted based on demonstrated competence, not just licensure.",
      "OPPE conducted for all privileged providers using objective performance data.",
      "FPPE triggered for all new privileges and whenever performance concerns arise.",
      "Medical staff bylaws define authority, accountability, and due process rights.",
      "Peer review results are used in privilege renewal decisions.",
    ],
    commonRiskPoints: [
      "Privileges granted based on licensure alone without demonstrated competence review.",
      "OPPE reviews completed but never used to inform privilege renewal decisions.",
      "FPPE not triggered when a provider receives new privileges at the organization.",
      "Medical staff meetings held but minutes do not reflect quality or clinical performance discussion.",
    ],
    cmsTags: ["MS.1", "MS.2", "MS.3", "MS.4", "MS.5", "MS.6", "MS.7", "MS.8"],
  },
  studyMaterial: [
    {
      title: "MS.1 — Medical Staff Organization",
      content:
        "The medical staff must be formally organized with governing documents (bylaws, rules, and regulations) that define authority, accountability, and due process rights. The medical staff must elect officers and maintain standing committees including at minimum a credentials committee, an executive committee, and quality/peer review committee. Medical staff committees must meet at defined intervals with documented minutes. The organization of the medical staff must be approved by the governing body.",
      keyPoint:
        "Medical staff must have formal bylaws with defined committees (credentials, executive, quality/peer review), elected officers, and meeting minutes. Governing body approval required.",
    },
    {
      title: "MS.2 — Credentialing Process",
      content:
        "Every practitioner applying for medical staff membership or clinical privileges must undergo primary source verification (PSV) of all credentials — licenses, education, training, board certification, malpractice history, and National Practitioner Data Bank (NPDB) query. Credentialing must be completed before a practitioner provides patient care (except temporary privileges in defined emergencies). Credentials are re-verified at minimum every two years.",
      keyPoint:
        "PSV is required for ALL credentials — no practitioner provides care without completed credentialing. NPDB query is mandatory. Re-verification minimum every 2 years.",
    },
    {
      title: "MS.3 — Clinical Privileging",
      content:
        "Clinical privileges define what specific procedures and patient care activities a practitioner is authorized to perform at the organization. Privileges must be granted based on demonstrated competence — education, training, experience, and current performance data — not licensure alone. Privileges must be specific (e.g., 'laparoscopic cholecystectomy') not general (e.g., 'surgery'). Privileges are renewed at minimum every two years as part of reappointment.",
      keyPoint:
        "Privileges must be specific and based on demonstrated competence. 'Licensed physician' is not a privilege — each clinical activity must be specifically delineated and granted.",
    },
    {
      title: "MS.4 — OPPE and FPPE",
      content:
        "Ongoing Professional Practice Evaluation (OPPE) requires collection of performance data for all privileged providers on an ongoing basis. Data must be objective (volume, outcomes, complications, peer review findings) and reviewed at defined intervals. OPPE results must be used in privilege renewal decisions. Focused Professional Practice Evaluation (FPPE) is triggered for: (1) all new privileges, and (2) whenever performance concerns are identified through OPPE or other means. FPPE involves direct observation or case review for a defined period.",
      keyPoint:
        "OPPE = ongoing data for all providers → used in renewal. FPPE = triggered by new privileges OR performance concerns → direct observation/case review for defined period.",
    },
    {
      title: "MS.5 — Peer Review",
      content:
        "Peer review must be structured, ongoing, and conducted by peers — practitioners who are similarly privileged and/or licensed. Review criteria must be developed by privileged professionals. Clinical incidents must be reviewed. Each provider must be reviewed at least annually. Peer review results must be documented, reported to the medical staff executive committee, and used in privilege renewal decisions. Peer review must also be reported to the governing body at least annually.",
      keyPoint:
        "Peer review must be by similarly-privileged peers, cover all providers, include incidents, occur annually, and results must flow to governing body AND inform privilege renewal.",
    },
  ],
  questions: [
    {
      id: "dnv_ms_01",
      question: "Under DNV MS.2, which of the following must be verified through primary source verification before a practitioner provides patient care?",
      options: [
        "Patient satisfaction scores from prior facilities",
        "Licenses, education, training, board certification, malpractice history, and NPDB query",
        "Employment history only",
        "References from colleagues only",
      ],
      correctIndex: 1,
      explanation: "DNV MS.2 requires primary source verification of all credentials: licenses, education, training, board certification, malpractice history, and mandatory NPDB query. All elements must be verified before the practitioner provides patient care.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_02",
      question: "A hospital grants a physician the privilege of 'general surgery' without specifying individual procedures. Under DNV MS.3, this is:",
      options: [
        "Acceptable — specialty designation is sufficient",
        "Non-compliant — privileges must be specific to individual procedures",
        "Acceptable if the physician is board certified in general surgery",
        "Non-compliant only for high-risk procedures",
      ],
      correctIndex: 1,
      explanation: "DNV MS.3 requires clinical privileges to be specific — e.g., 'laparoscopic cholecystectomy' rather than 'general surgery.' Broad specialty designations do not constitute valid clinical privileging under DNV standards.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_03",
      question: "A nurse practitioner joins the medical staff and receives full privileges immediately without an FPPE period. Under DNV MS.4, this is:",
      options: [
        "Acceptable if the NP has 5+ years of experience elsewhere",
        "Non-compliant — FPPE is required for all new privileges",
        "Acceptable if the credentialing committee approved the appointment",
        "Non-compliant only for surgical privileges",
      ],
      correctIndex: 1,
      explanation: "DNV MS.4 requires FPPE to be triggered for ALL new privileges, regardless of a practitioner's prior experience. FPPE allows the organization to verify competence in the new practice setting before granting unrestricted privileges.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_04",
      question: "OPPE data is collected for all physicians but is never reviewed or used in privilege renewal decisions. Under DNV MS.4, this represents:",
      options: [
        "Partial compliance — data collection satisfies half the requirement",
        "Non-compliance — OPPE data must be used in privilege renewal decisions",
        "Full compliance — data collection is the primary OPPE requirement",
        "Non-compliance only for physicians with identified performance issues",
      ],
      correctIndex: 1,
      explanation: "DNV MS.4 requires OPPE data to be both collected AND used in privilege renewal decisions. Data collection without review and application to privileging decisions satisfies only the data collection element but fails the core purpose of OPPE.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_05",
      question: "A peer review of a surgeon's case identified multiple technique concerns. The concerns are documented but do not affect the surgeon's privilege renewal. Under DNV MS.5, this is:",
      options: [
        "Acceptable — peer review and privileging are separate processes",
        "Non-compliant — peer review results must be used in privilege renewal decisions",
        "Acceptable if the concerns were classified as low severity",
        "Non-compliant only if the surgeon had prior adverse events",
      ],
      correctIndex: 1,
      explanation: "DNV MS.5 requires peer review results to be used in privilege renewal decisions. The entire purpose of peer review is to inform clinical accountability — including privileging. Peer review that never influences privileges is a structural deficiency.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_06",
      question: "Medical staff credentials are verified once at appointment. Under DNV MS.2, how frequently must credentials be re-verified?",
      options: [
        "Every 5 years",
        "At minimum every 2 years",
        "Only if concerns are raised",
        "Every 10 years",
      ],
      correctIndex: 1,
      explanation: "DNV MS.2 requires credentials to be re-verified at minimum every two years as part of the reappointment process. Ongoing verification ensures that licenses remain current and no disqualifying events (e.g., malpractice, discipline) have occurred.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_07",
      question: "A medical staff peer review committee consists entirely of administrators with no physician peers. Under DNV MS.5, this is:",
      options: [
        "Acceptable if the administrators have clinical backgrounds",
        "Non-compliant — peer review must be conducted by similarly privileged/licensed peers",
        "Acceptable if the CMO chairs the committee",
        "Non-compliant only for surgical peer review",
      ],
      correctIndex: 1,
      explanation: "DNV MS.5 requires peer review to be conducted by practitioners who are similarly privileged and/or licensed. Administrators cannot substitute for clinical peers — the 'peer' in peer review requires equivalent clinical standing.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_08",
      question: "The medical staff bylaws have not been reviewed by the credentials committee in 3 years. Under DNV MS.1, what is the minimum review requirement?",
      options: [
        "Every 5 years",
        "Only when deficiencies are identified",
        "At minimum every 2 years with governing body approval",
        "Every 10 years",
      ],
      correctIndex: 2,
      explanation: "DNV MS.1 requires medical staff bylaws to be reviewed at minimum every 2 years and re-approved by the governing body. This ensures governance documents remain current and that the governing body maintains active oversight.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_09",
      question: "A physician requests privileges for robotic surgery, a new procedure at the institution. Under DNV MS.4, what evaluation process is triggered?",
      options: [
        "No additional evaluation if the physician is board certified",
        "FPPE — because this constitutes new privileges",
        "OPPE review only",
        "External peer review only",
      ],
      correctIndex: 1,
      explanation: "DNV MS.4 triggers FPPE for all new privileges, including when an established medical staff member requests privileges for a new procedure they haven't previously performed at the organization. The FPPE involves direct observation or case review for a defined period.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_10",
      question: "Under DNV MS.5, peer review results must be reported to which bodies?",
      options: [
        "The credentials committee only",
        "The governing body only",
        "Both the medical staff executive committee AND the governing body (at minimum annually)",
        "The state medical licensing board only",
      ],
      correctIndex: 2,
      explanation: "DNV MS.5 requires peer review results to be documented, reported to the medical staff executive committee, and reported to the governing body at minimum annually. This dual reporting ensures both clinical and governance accountability.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_11",
      question: "A practitioner's privileges are renewed every 2 years without any review of OPPE data. Under DNV MS.4, this renewal process is:",
      options: [
        "Acceptable if no complaints were received in the 2-year period",
        "Non-compliant — OPPE data must be reviewed and used in privilege renewal",
        "Acceptable if the practitioner submits a self-assessment",
        "Non-compliant only if adverse events occurred during the period",
      ],
      correctIndex: 1,
      explanation: "DNV MS.4 requires OPPE data to be reviewed and used in privilege renewal decisions. Automatic renewal without data review defeats the purpose of OPPE and fails the standard, even in the absence of complaints or adverse events.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_12",
      question: "Which of the following represents primary source verification (PSV) for a physician's medical license?",
      options: [
        "Reviewing a copy of the license provided by the physician",
        "Contacting the state medical board directly to verify licensure status",
        "Checking a professional reference who confirms the license",
        "Reviewing the physician's CV for license information",
      ],
      correctIndex: 1,
      explanation: "Primary source verification requires obtaining verification directly from the original issuing source — the state medical board. Copies provided by the applicant, references, or CVs are not primary sources and do not satisfy PSV requirements.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_13",
      question: "FPPE is triggered for a physician after OPPE data reveals a higher-than-expected complication rate. What should FPPE involve?",
      options: [
        "A verbal counseling session with the CMO",
        "Direct observation or prospective case review for a defined period",
        "A single case review by the credentials committee",
        "Self-reporting by the physician for 30 days",
      ],
      correctIndex: 1,
      explanation: "When FPPE is triggered by performance concerns, it involves direct observation of the practitioner's clinical practice or prospective case review for a defined period. This allows the organization to assess whether the performance concern is ongoing and to determine appropriate action.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_14",
      question: "A hospital's medical staff does not have a standing credentials committee. Under DNV MS.1, this is:",
      options: [
        "Acceptable if the executive committee handles credentialing",
        "Non-compliant — a credentials committee is a required standing committee",
        "Acceptable for hospitals with fewer than 50 medical staff members",
        "Non-compliant only if credentialing errors have occurred",
      ],
      correctIndex: 1,
      explanation: "DNV MS.1 requires medical staff to maintain standing committees including at minimum a credentials committee, an executive committee, and quality/peer review committee. The credentials committee is not optional regardless of medical staff size.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_15",
      question: "Under DNV MS.3, clinical privileges are granted based on which of the following?",
      options: [
        "Current licensure and malpractice insurance only",
        "Demonstrated competence — education, training, experience, and current performance data",
        "Years of experience in the specialty",
        "Board certification alone",
      ],
      correctIndex: 1,
      explanation: "DNV MS.3 requires privileges to be granted based on demonstrated competence — the combination of education, training, experience, and current performance data. Licensure alone, board certification alone, or years of experience are not sufficient bases for privileging.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_16",
      question: "Medical staff committee meeting minutes contain only attendance records with no discussion of quality or clinical performance. Under DNV MS.1, this is:",
      options: [
        "Acceptable if attendance is quorum-compliant",
        "Non-compliant — minutes must reflect substantive discussion of clinical quality and performance",
        "Acceptable if the CMO provides a verbal summary",
        "Non-compliant only if a sentinel event was discussed that month",
      ],
      correctIndex: 1,
      explanation: "DNV MS.1 requires medical staff committees to meet at defined intervals with documented minutes that reflect substantive discussion. Minutes containing only attendance records provide no evidence of the committee's quality oversight function.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_17",
      question: "An NPDB query has never been submitted for a physician granted privileges 5 years ago. Under DNV MS.2, this is:",
      options: [
        "Acceptable if the physician has had no malpractice claims",
        "Non-compliant — NPDB query is mandatory as part of credentialing",
        "Acceptable if the physician is board certified",
        "Non-compliant only at initial appointment, not reappointment",
      ],
      correctIndex: 1,
      explanation: "DNV MS.2 requires a mandatory NPDB (National Practitioner Data Bank) query as part of credentialing. This is not optional — the NPDB contains malpractice payment reports and adverse privilege actions that cannot be discovered through other means.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_18",
      question: "A physician peer reviews cases of other physicians but never has their own cases reviewed. Under DNV MS.5, this is:",
      options: [
        "Acceptable if the physician has no complications",
        "Non-compliant — each provider must be reviewed at least annually",
        "Acceptable for senior physicians with 20+ years of experience",
        "Non-compliant only if the physician is a department chief",
      ],
      correctIndex: 1,
      explanation: "DNV MS.5 requires each privileged provider to be reviewed at minimum annually. No exemptions exist based on seniority, specialty, or clean record. Universal application of peer review to all providers is a fundamental requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_19",
      question: "Under DNV MS.3, how often must clinical privileges be renewed?",
      options: [
        "Every 5 years",
        "At minimum every 2 years as part of reappointment",
        "Every 10 years",
        "Only when new procedures are requested",
      ],
      correctIndex: 1,
      explanation: "DNV MS.3 requires clinical privileges to be renewed at minimum every two years as part of the reappointment process. This ensures privileges remain aligned with demonstrated current competence and that practitioners' performance is regularly evaluated.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_ms_20",
      question: "Which of the following scenarios correctly represents compliant medical staff due process under DNV MS.1?",
      options: [
        "A physician's privileges are suspended without notification or opportunity to respond",
        "A physician's privileges are reduced with documented notice, opportunity to appeal, and fair hearing rights",
        "A physician's privileges are permanently revoked based on a single peer review case",
        "A physician's reappointment is denied without written explanation",
      ],
      correctIndex: 1,
      explanation: "DNV MS.1 requires medical staff bylaws to define due process rights for practitioners facing adverse privileging actions. This includes documented notice, opportunity to respond, appeal rights, and fair hearing procedures before final adverse action.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
