import type { Level } from "./schema";

export const dnvPcLevel: Level = {
  id: "dnv_pc",
  module: "dnv",
  name: "Patient-Centered Care",
  description: "DNV DIAS Section 10 — PC standards for patient rights, informed consent, care planning, patient education, and continuity of care.",
  icon: "UserCheck",
  color: "hsl(25, 70%, 48%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "PC: Patient-Centered Care",
    plainLanguageSummary:
      "DNV's Patient-Centered Care section establishes the rights of patients and the obligations of the organization to respect those rights throughout every episode of care. Patients have the right to dignity, privacy, informed consent, participation in care decisions, advance directives, and freedom from abuse or coercion. The organization must conduct individualized assessments, develop patient-specific care plans, educate patients about their conditions and treatments, and ensure continuity of care across settings. Cultural and language access requirements apply to all patient interactions.",
    keyOperationalExpectations: [
      "Patient rights are communicated in writing at admission and posted in care areas.",
      "Informed consent is obtained before all treatments, procedures, and participation in research.",
      "Advance directives are documented, honored, and accessible in the medical record.",
      "Patient assessments are individualized and guide development of care plans.",
      "Patient education is provided in the patient's preferred language at appropriate literacy levels.",
      "Discharge planning begins at admission and ensures continuity of care post-discharge.",
    ],
    commonRiskPoints: [
      "Advance directives documented but not accessible in the active medical record during a crisis.",
      "Informed consent obtained for surgery but not for high-risk medications or procedures.",
      "Patient education provided verbally without assessment of patient's health literacy.",
      "Discharge planning initiated the day of discharge rather than beginning at admission.",
    ],
    cmsTags: ["PC.1", "PC.2", "PC.3", "PC.4", "PC.5", "PC.6", "PC.7", "PC.8", "PC.9", "PC.10"],
  },
  studyMaterial: [
    {
      title: "PC.1 — Patient Rights",
      content:
        "Each patient has fundamental rights that the organization must respect and uphold: the right to dignity and respect, privacy and confidentiality, information about their condition and treatment options, participation in care decisions, refusal of treatment, freedom from abuse or coercion, access to pastoral or spiritual care, and the right to file grievances without fear of retaliation. Rights must be communicated in writing at admission in the patient's preferred language and must be posted in patient care areas.",
      keyPoint:
        "Patient rights must be communicated in writing at admission in the patient's language AND posted in care areas. Failure to notify of rights = violation regardless of actual care quality.",
    },
    {
      title: "PC.2 — Informed Consent",
      content:
        "Informed consent must be obtained before treatments, procedures, surgery, and research participation. Consent must include: the nature and purpose of the proposed treatment, material risks and benefits, available alternatives, consequences of refusal, and the identity of who will perform the procedure. Consent must be documented in the medical record. Consent for surgical procedures must be obtained before the patient receives pre-operative sedation. Surrogate decision-making and emergency exceptions are defined in policy.",
      keyPoint:
        "Consent must include 5 elements: nature/purpose, material risks/benefits, alternatives, consequences of refusal, practitioner identity. Consent before pre-op sedation — not after.",
    },
    {
      title: "PC.3 — Advance Directives",
      content:
        "The organization must ask every patient at admission whether they have an advance directive (living will, healthcare proxy, POLST/MOLST). If a patient has an advance directive, it must be documented and accessible in the medical record. The organization must honor advance directives to the extent permitted by law and must not condition care on the existence of an advance directive. Staff must be educated on advance directive policies. If the organization cannot honor a directive for religious/ethical reasons, it must inform the patient and assist with transfer.",
      keyPoint:
        "Advance directive status must be asked at every admission. If present, it must be in the medical record and accessible — especially during emergencies.",
    },
    {
      title: "PC.4 — Assessment and Care Planning",
      content:
        "Every patient must receive an individualized assessment that identifies their clinical, psychosocial, cultural, spiritual, and functional needs. Assessment results must drive development of an individualized care plan. Care plans must be documented, updated as patient condition changes, and developed with patient participation. Multidisciplinary input is required for complex patients. Reassessment occurs at defined intervals and when patient condition changes significantly.",
      keyPoint:
        "Assessment → individualized care plan → patient participation → multidisciplinary for complex patients → reassessment when condition changes. All must be documented.",
    },
    {
      title: "PC.5 — Patient Education and Discharge Planning",
      content:
        "Patient education must be provided in the patient's preferred language at an appropriate health literacy level. Education must cover the patient's condition, medications (including side effects), treatment, self-care, and follow-up requirements. Health literacy must be assessed and education adapted accordingly. Discharge planning must begin at or near admission, involve the patient and family, and ensure continuity of care — including follow-up appointments, community resources, and medication reconciliation.",
      keyPoint:
        "Education must be in preferred language, at appropriate literacy level, covering condition + medications + self-care. Discharge planning starts at admission — not the day of discharge.",
    },
  ],
  questions: [
    {
      id: "dnv_pc_01",
      question: "Under DNV PC.1, when must patient rights be communicated in writing?",
      options: [
        "Within 24 hours of admission",
        "At admission and in the patient's preferred language",
        "Only when the patient requests information",
        "At discharge as part of discharge instructions",
      ],
      correctIndex: 1,
      explanation: "DNV PC.1 requires patient rights to be communicated in writing at admission in the patient's preferred language. Rights communication cannot be deferred to later in the hospitalization.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_02",
      question: "Which of the following must be included in informed consent under DNV PC.2?",
      options: [
        "The patient's diagnosis history and insurance information",
        "Nature/purpose, material risks/benefits, alternatives, consequences of refusal, and practitioner identity",
        "The cost of the procedure and billing information",
        "A complete list of all possible complications regardless of likelihood",
      ],
      correctIndex: 1,
      explanation: "DNV PC.2 requires informed consent to include five elements: nature and purpose, material risks and benefits, available alternatives, consequences of refusal, and the identity of who will perform the procedure. Cost and billing are not components of informed consent.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_03",
      question: "A patient has a living will on file at their physician's office but it has not been placed in the hospital medical record. Under DNV PC.3, this is:",
      options: [
        "Acceptable if the patient verbally informed the nurse",
        "Non-compliant — advance directives must be documented and accessible in the medical record",
        "Acceptable if the family can produce it if needed",
        "Non-compliant only for ICU patients",
      ],
      correctIndex: 1,
      explanation: "DNV PC.3 requires advance directives to be documented AND accessible in the medical record. An advance directive filed elsewhere provides no real protection if staff cannot access it during a clinical emergency.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_04",
      question: "Informed consent for a surgical procedure is obtained while the patient is in the pre-operative holding area after receiving anxiolytic medication. Under DNV PC.2, this is:",
      options: [
        "Acceptable if the patient was alert and oriented",
        "Non-compliant — consent must be obtained before pre-operative sedation",
        "Acceptable if the surgeon witnessed the consent",
        "Non-compliant only if the patient later claims they did not understand",
      ],
      correctIndex: 1,
      explanation: "DNV PC.2 requires surgical consent to be obtained before pre-operative sedation. Once sedating medications are given, the patient's ability to make a truly informed, autonomous decision is compromised — even if they appear alert.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_05",
      question: "A patient's care plan is documented at admission but never updated despite significant deterioration in the patient's condition. Under DNV PC.4, this is:",
      options: [
        "Acceptable if the physician's orders were updated",
        "Non-compliant — care plans must be updated when patient condition changes significantly",
        "Acceptable if nursing assessments were documented",
        "Non-compliant only if the patient was transferred to the ICU",
      ],
      correctIndex: 1,
      explanation: "DNV PC.4 requires care plans to be updated as the patient's condition changes. A static care plan that doesn't reflect the current clinical situation fails to provide the individualized direction needed for complex patient management.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_06",
      question: "Patient education is provided entirely in English to a Spanish-speaking patient without interpreter services. Under DNV PC.5, this is:",
      options: [
        "Acceptable if a bilingual staff member was present",
        "Non-compliant — education must be provided in the patient's preferred language",
        "Acceptable if the patient nodded to indicate understanding",
        "Non-compliant only for discharge instructions",
      ],
      correctIndex: 1,
      explanation: "DNV PC.5 requires patient education to be provided in the patient's preferred language. Providing education in a language the patient doesn't fully understand fails the patient education standard regardless of whether a bilingual staff member was present.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_07",
      question: "Under DNV PC.3, if an organization cannot honor a patient's advance directive for religious or ethical reasons, what must occur?",
      options: [
        "The organization may override the directive with physician approval",
        "The organization must inform the patient and assist with transfer to a facility that will honor it",
        "The organization must obtain a court order before proceeding",
        "The organization may proceed with care according to its policies",
      ],
      correctIndex: 1,
      explanation: "DNV PC.3 requires that if the organization cannot honor an advance directive for religious or ethical reasons, it must inform the patient and assist with transfer to a facility that will honor the directive. Patient autonomy is not overridden by organizational values.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_08",
      question: "Discharge planning for an elderly patient with complex needs begins on the day of discharge. Under DNV PC.5, this is:",
      options: [
        "Acceptable if the discharge is planned and not emergent",
        "Non-compliant — discharge planning must begin at or near admission",
        "Acceptable if the patient lives with family members",
        "Non-compliant only for patients discharged to skilled nursing facilities",
      ],
      correctIndex: 1,
      explanation: "DNV PC.5 requires discharge planning to begin at or near admission, especially for complex patients. Late-stage discharge planning prevents adequate coordination of post-discharge resources, follow-up care, and community support.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_09",
      question: "A patient with low health literacy receives a standard printed educational handout with medical terminology. Under DNV PC.5, what additional step is required?",
      options: [
        "No additional step — the handout satisfies the education requirement",
        "Education must be adapted to the patient's health literacy level",
        "The patient must sign an acknowledgment that they received the handout",
        "A physician must verbally explain the handout",
      ],
      correctIndex: 1,
      explanation: "DNV PC.5 requires health literacy to be assessed and education adapted accordingly. Standard handouts with medical terminology do not meet the needs of patients with low health literacy — plain language, visual aids, or teach-back methods should be used.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_10",
      question: "Under DNV PC.1, can a hospital condition the provision of care on whether a patient has an advance directive?",
      options: [
        "Yes, for ICU admissions where advance directive status is clinically relevant",
        "No — care must not be conditioned on the existence or absence of an advance directive",
        "Yes, for elective surgical procedures",
        "No, but the patient can be counseled about advance directive benefits",
      ],
      correctIndex: 1,
      explanation: "DNV PC.3 explicitly prohibits conditioning care on whether a patient has an advance directive. Every patient has the right to care regardless of their advance directive status. Requiring an advance directive as a condition of admission or treatment violates patient rights.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_11",
      question: "A care plan for a complex patient is developed by the primary nurse without multidisciplinary input. Under DNV PC.4, this is:",
      options: [
        "Acceptable if the physician reviews and signs the plan",
        "Non-compliant — multidisciplinary input is required for complex patients",
        "Acceptable for patients expected to be discharged within 24 hours",
        "Non-compliant only if the patient has multiple comorbidities",
      ],
      correctIndex: 1,
      explanation: "DNV PC.4 requires multidisciplinary input for complex patient care plans. A plan developed by a single clinician cannot adequately address the clinical, psychosocial, functional, and discharge planning needs of complex patients.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_12",
      question: "Under DNV PC.1, a patient is discharged from the hospital without ever being informed of their right to file a grievance. This is:",
      options: [
        "Acceptable if no complaints were received during the stay",
        "Non-compliant — the right to file grievances must be communicated at admission",
        "Acceptable if the patient expressed satisfaction throughout the stay",
        "Non-compliant only if the patient was dissatisfied with care",
      ],
      correctIndex: 1,
      explanation: "DNV PC.1 requires all patient rights — including the right to file grievances without fear of retaliation — to be communicated in writing at admission. This must occur regardless of the patient's actual satisfaction with care.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_13",
      question: "Which of the following patient needs must be assessed as part of an individualized assessment under DNV PC.4?",
      options: [
        "Insurance coverage and financial ability to pay",
        "Clinical, psychosocial, cultural, spiritual, and functional needs",
        "Patient preferences for hospital food",
        "Visitor preferences and family contact information",
      ],
      correctIndex: 1,
      explanation: "DNV PC.4 requires individualized assessments to identify clinical, psychosocial, cultural, spiritual, and functional needs. This comprehensive assessment drives care planning that addresses the whole patient, not just their clinical diagnosis.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_14",
      question: "A patient refuses a recommended blood transfusion citing religious beliefs. Under DNV PC.1, the organization must:",
      options: [
        "Override the refusal if the patient's life is at risk",
        "Respect the patient's right to refuse treatment and document the informed refusal",
        "Obtain a court order to proceed with the transfusion",
        "Transfer the patient to another facility immediately",
      ],
      correctIndex: 1,
      explanation: "DNV PC.1 establishes the patient's right to refuse treatment, including on religious grounds. The organization must respect this right, ensure the patient is fully informed of the consequences of refusal, and document the informed refusal in the medical record.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_15",
      question: "Under DNV PC.5, what must discharge planning ensure beyond a follow-up appointment?",
      options: [
        "That the patient has transportation arranged",
        "Continuity of care including follow-up appointments, community resources, and medication reconciliation",
        "That the patient's family has been notified of the discharge",
        "That the patient's insurance has approved post-discharge services",
      ],
      correctIndex: 1,
      explanation: "DNV PC.5 requires comprehensive discharge planning that ensures continuity of care — including follow-up appointments, identification of community resources, and medication reconciliation. A discharge summary with only a follow-up appointment is insufficient.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_16",
      question: "A patient's care plan is developed without the patient's participation. Under DNV PC.4, this is:",
      options: [
        "Acceptable if the patient's physician is involved",
        "Non-compliant — care plans must be developed with patient participation",
        "Acceptable for patients who are acutely ill and cannot participate",
        "Non-compliant only if the patient later objects to the plan",
      ],
      correctIndex: 1,
      explanation: "DNV PC.4 requires care plans to be developed with patient participation. Patient-centered care means patients are active participants in decisions about their own care — not passive recipients of decisions made by clinicians.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_17",
      question: "Informed consent for a high-risk medication (e.g., chemotherapy) is not obtained because the physician believes the patient understands the risks from previous discussions. Under DNV PC.2, this is:",
      options: [
        "Acceptable if the risks were discussed in a previous visit",
        "Non-compliant — informed consent must be documented before each treatment course",
        "Acceptable if the patient signs a general consent at admission",
        "Non-compliant only for chemotherapy agents with black box warnings",
      ],
      correctIndex: 1,
      explanation: "DNV PC.2 requires informed consent to be obtained and documented before treatments. Previous verbal discussions do not substitute for documented consent. General admission consent forms do not cover specific high-risk treatment consents.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_18",
      question: "Under DNV PC.3, what must occur at every hospital admission regarding advance directives?",
      options: [
        "Patients must be required to create an advance directive",
        "The organization must ask every patient whether they have an advance directive",
        "Patients must update their advance directive with each admission",
        "Advance directives must be reviewed by the patient's physician",
      ],
      correctIndex: 1,
      explanation: "DNV PC.3 requires the organization to ask every patient at admission whether they have an advance directive. Patients cannot be required to have one — but the question must be asked and the status documented every admission.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_19",
      question: "A patient's assessment reveals spiritual distress. Under DNV PC.4, what should occur?",
      options: [
        "The clinical team notes the distress but takes no action unless the patient asks for help",
        "The care plan should be updated to address spiritual needs, potentially including chaplaincy referral",
        "Spiritual needs are outside the scope of clinical care planning",
        "A psychiatric consult is required for all spiritual distress",
      ],
      correctIndex: 1,
      explanation: "DNV PC.4 requires individualized assessments to identify spiritual needs and for those needs to be addressed in the care plan. Spiritual care (e.g., chaplaincy referral) is within scope of patient-centered care and may be incorporated into the care plan.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pc_20",
      question: "Under DNV PC.1, patient rights must be posted in which locations?",
      options: [
        "Only in the admissions office",
        "Patient care areas throughout the organization",
        "Only in the patient's room",
        "Only on the organization's website",
      ],
      correctIndex: 1,
      explanation: "DNV PC.1 requires patient rights to be posted in patient care areas throughout the organization. Posting only in the admissions office or only in patient rooms does not satisfy the requirement for visible, accessible rights information throughout care areas.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
