import type { Level } from "./schema";

export const dnvGbLevel: Level = {
  id: "dnv_gb",
  module: "dnv",
  name: "Governance & Governing Body",
  description: "DNV DIAS Section 5 — GB standards for governing body structure, accountability, executive leadership, and organizational authority.",
  icon: "Building2",
  color: "hsl(340, 60%, 45%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "GB: Governance & Governing Body",
    plainLanguageSummary:
      "The Governance section holds the governing body (board of directors or trustees) accountable for the overall quality and safety of patient care, financial integrity, and compliance with accreditation standards. The governing body must define the organization's mission, appoint and evaluate the CEO, approve medical staff bylaws, oversee quality management, and ensure adequate resources. DNV emphasizes that governance accountability cannot be fully delegated — the board retains ultimate responsibility.",
    keyOperationalExpectations: [
      "Governing body approves organizational mission, scope of services, and strategic direction.",
      "Governing body appoints the CEO and conducts formal CEO performance evaluations.",
      "Medical staff bylaws and rules/regulations are approved by the governing body.",
      "Governing body receives and acts on quality management and patient safety reports.",
      "Governing body reviews and approves the annual budget and major capital expenditures.",
      "Conflict of interest policies for governing body members are documented and enforced.",
    ],
    commonRiskPoints: [
      "Governing body passively receives quality reports without documented discussion or action.",
      "Medical staff bylaws not formally approved by the governing body in the past 2 years.",
      "No documented formal CEO performance evaluation process.",
      "Conflict of interest policy exists but disclosures are not consistently completed.",
    ],
    cmsTags: ["GB.1", "GB.2", "GB.3", "GB.4", "GB.5", "GB.6", "GB.7", "GB.8"],
  },
  studyMaterial: [
    {
      title: "GB.1 — Governing Body Authority and Accountability",
      content:
        "The governing body holds ultimate legal responsibility for the hospital's operations, quality of care, and patient safety. This responsibility cannot be fully delegated — while the governing body may delegate day-to-day management to the CEO and clinical oversight to the medical staff, it retains accountability for outcomes. The governing body must be constituted according to the hospital's bylaws and must include members who are independent of management.",
      keyPoint:
        "The governing body retains ultimate accountability — delegation of operations to CEO/medical staff does not relieve the board of its legal and accreditation responsibility.",
    },
    {
      title: "GB.2 — Mission, Scope, and Strategic Direction",
      content:
        "The governing body must formally approve the organization's mission statement, scope of services, and strategic plan. Changes to the scope of services (adding or eliminating service lines) require governing body approval. The mission must reflect commitment to quality patient care and be communicated to all staff. Strategic plans must be reviewed periodically and updated to reflect the organization's current environment.",
      keyPoint:
        "Any addition or elimination of services requires governing body approval — scope changes cannot be made by administration alone.",
    },
    {
      title: "GB.3 — CEO Appointment and Evaluation",
      content:
        "The governing body is responsible for appointing the CEO (or equivalent executive leader) and for conducting formal, documented performance evaluations. The evaluation must be structured and occur at defined intervals. The governing body must also establish the process for CEO succession. Performance criteria must include quality outcomes, financial stewardship, regulatory compliance, and organizational culture.",
      keyPoint:
        "CEO appointment AND formal performance evaluation are governing body responsibilities. The evaluation must be structured, documented, and occur at defined intervals.",
    },
    {
      title: "GB.4 — Medical Staff Bylaws Approval",
      content:
        "The governing body must approve the medical staff bylaws, rules, and regulations. These documents define the authority and accountability of the medical staff, including credentialing and privileging processes. The bylaws must be reviewed and re-approved at minimum every two years. Changes to bylaws proposed by the medical staff must be formally approved by the governing body before taking effect.",
      keyPoint:
        "Medical staff bylaws require governing body approval — medical staff cannot unilaterally change their own governance documents. Review minimum every 2 years.",
    },
    {
      title: "GB.5 — Quality Oversight and Patient Safety",
      content:
        "The governing body must actively participate in quality oversight by receiving quality management reports, reviewing patient safety data, approving the Quality Management Plan, and taking action when performance falls below expectations. Passive receipt of reports is insufficient — meeting minutes must reflect substantive discussion, questions asked, and actions directed. The governing body may not delegate quality accountability entirely to the medical staff or administration.",
      keyPoint:
        "Governing body quality oversight requires active participation with documented discussion — not just receipt of reports. Board meeting minutes are key evidence.",
    },
  ],
  questions: [
    {
      id: "dnv_gb_01",
      question: "Under DNV GB standards, who holds ultimate legal responsibility for the hospital's quality of care and patient safety?",
      options: [
        "The Chief Medical Officer",
        "The medical staff executive committee",
        "The governing body (board of directors/trustees)",
        "The Quality Management department",
      ],
      correctIndex: 2,
      explanation: "GB.1 establishes that the governing body holds ultimate legal responsibility for hospital operations, quality of care, and patient safety. This accountability cannot be fully delegated, even though day-to-day management is handled by the CEO and medical staff.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_02",
      question: "A hospital's administration decides to add an outpatient surgery service line without formal governing body approval. Under DNV GB.2, this is:",
      options: [
        "Acceptable if the CEO approved the change",
        "A violation — scope of service changes require governing body approval",
        "Acceptable if the medical staff voted to support it",
        "A violation only if the new service affects accreditation scope",
      ],
      correctIndex: 1,
      explanation: "DNV GB.2 requires governing body approval for changes to the scope of services. Administration cannot unilaterally add or eliminate service lines — this is a governance accountability that must remain with the board.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_03",
      question: "Medical staff bylaws have not been reviewed or re-approved by the governing body in 4 years. Under DNV GB.4, this represents:",
      options: [
        "No deficiency if no changes were made to the bylaws",
        "A deficiency — bylaws must be reviewed and re-approved at minimum every 2 years",
        "A deficiency only if the medical staff requested changes",
        "No deficiency if the CEO reviews them annually",
      ],
      correctIndex: 1,
      explanation: "DNV GB.4 requires governing body review and re-approval of medical staff bylaws at minimum every two years, regardless of whether changes are proposed. The review process itself demonstrates active governance oversight.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_04",
      question: "The governing body receives a quality report each quarter but meeting minutes show no discussion, questions, or actions taken. Under DNV GB.5, this is:",
      options: [
        "Compliant — receiving the report satisfies the standard",
        "Non-compliant — active participation with documented discussion is required",
        "Compliant if the Quality Director presents the report in person",
        "Non-compliant only if patient harm occurred that quarter",
      ],
      correctIndex: 1,
      explanation: "DNV GB.5 requires active participation in quality oversight — meeting minutes must reflect substantive discussion, questions, and directed actions. Passive receipt of reports without documented engagement fails the governing body oversight standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_05",
      question: "Which of the following CEO performance evaluation criteria does DNV expect the governing body to include?",
      options: [
        "Staff popularity scores only",
        "Quality outcomes, financial stewardship, regulatory compliance, and organizational culture",
        "Financial performance only",
        "Patient satisfaction scores only",
      ],
      correctIndex: 1,
      explanation: "DNV GB.3 requires that CEO performance evaluations be structured and include multiple dimensions: quality outcomes, financial stewardship, regulatory compliance, and organizational culture. Single-dimension evaluations do not reflect the comprehensive nature of executive accountability.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_06",
      question: "A governing body member who is also a major hospital vendor does not disclose this relationship before voting on a contract with their company. This violates which governance principle?",
      options: [
        "CEO appointment requirements",
        "Medical staff bylaws approval process",
        "Conflict of interest policy requirements",
        "Strategic planning approval process",
      ],
      correctIndex: 2,
      explanation: "DNV GB standards require conflict of interest policies for governing body members to be documented and enforced. Failure to disclose a financial relationship before voting on a related matter is a conflict of interest violation.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_07",
      question: "Under DNV GB.1, if the governing body delegates operational management to the CEO, what accountability does the board retain?",
      options: [
        "No accountability — full delegation transfers all responsibility",
        "Financial accountability only",
        "Ultimate accountability for quality, safety, and organizational outcomes",
        "Accountability only for major capital expenditures",
      ],
      correctIndex: 2,
      explanation: "DNV GB.1 is explicit: delegation of operations to the CEO does not relieve the governing body of ultimate accountability. The board retains responsibility for quality, patient safety, and organizational outcomes even when day-to-day management is delegated.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_08",
      question: "The governing body approves the annual budget but never reviews major capital expenditure requests. Under DNV GB standards, this is:",
      options: [
        "Compliant — budget approval satisfies the financial oversight requirement",
        "Non-compliant — major capital expenditures also require governing body review and approval",
        "Compliant if the CFO approves capital expenditures",
        "Non-compliant only for expenditures over $1 million",
      ],
      correctIndex: 1,
      explanation: "DNV GB standards require the governing body to review and approve the annual budget AND major capital expenditures. Financial stewardship extends beyond the operating budget to significant capital decisions that affect the organization's mission and resources.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_09",
      question: "The medical staff proposes changes to their credentialing criteria in the bylaws and implements them immediately without governing body review. Under DNV GB.4, this is:",
      options: [
        "Acceptable — the medical staff has autonomy over their own credentialing processes",
        "A violation — bylaw changes require governing body approval before taking effect",
        "Acceptable if the changes improve patient safety",
        "A violation only if the changes reduce credentialing standards",
      ],
      correctIndex: 1,
      explanation: "DNV GB.4 requires that changes to medical staff bylaws, rules, and regulations be formally approved by the governing body before taking effect. The medical staff cannot unilaterally change their governance documents.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_10",
      question: "A hospital has an 8-member governing body where 6 members are also employed by the hospital. What governance concern does this raise under DNV GB.1?",
      options: [
        "No concern — employed members have valuable operational knowledge",
        "Independence concern — the governing body should include independent members not employed by management",
        "A staffing concern — governing bodies should have exactly 10 members",
        "A financial concern — employed members may draw two salaries",
      ],
      correctIndex: 1,
      explanation: "DNV GB.1 requires that the governing body include members who are independent of management. A board dominated by employed members lacks the independence needed to hold management accountable for quality, safety, and financial stewardship.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_11",
      question: "How often must the CEO undergo a formal performance evaluation under DNV GB.3?",
      options: [
        "Every 5 years",
        "At defined intervals as established in governing body policy",
        "Only when performance problems are identified",
        "Every 10 years",
      ],
      correctIndex: 1,
      explanation: "DNV GB.3 requires formal, documented CEO performance evaluations at defined intervals. While DNV does not specify an exact frequency, the interval must be defined in governing body policy and consistently followed — typically annually.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_12",
      question: "The Quality Management Plan is developed by administration and the QM committee. Under DNV GB standards, what additional step is required?",
      options: [
        "Medical staff approval",
        "Governing body approval",
        "State health department review",
        "External accreditor pre-approval",
      ],
      correctIndex: 1,
      explanation: "Under DNV GB.5 and QM.1, the governing body must approve the Quality Management Plan. Quality accountability extends to the board, and plan approval demonstrates governing body engagement with the organization's quality strategy.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_13",
      question: "Which of the following best reflects DNV's approach to the relationship between the governing body and the medical staff?",
      options: [
        "The medical staff operates independently with no governing body oversight",
        "The governing body directly manages medical staff clinical decisions",
        "The governing body approves bylaws and receives quality reports; medical staff manages clinical operations",
        "The governing body and medical staff have equal and interchangeable authority",
      ],
      correctIndex: 2,
      explanation: "DNV establishes a clear division: the governing body approves the governance framework (bylaws) and receives quality accountability reports, while the medical staff manages clinical operations within that framework. Neither body has complete control — each has defined authority.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_14",
      question: "A governing body member states that quality and patient safety are 'the medical staff's job' and declines to review quality reports. Under DNV GB.5, this attitude represents:",
      options: [
        "A valid delegation of clinical authority to the medical staff",
        "A governance deficiency — the governing body cannot fully delegate quality accountability",
        "Acceptable if the CMO attends governing body meetings",
        "A deficiency only if sentinel events have occurred",
      ],
      correctIndex: 1,
      explanation: "DNV GB.5 specifically addresses this: the governing body may not delegate quality accountability entirely to the medical staff or administration. Active governing body engagement with quality data is a DNV requirement, not an optional practice.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_15",
      question: "Under DNV governance standards, what must the organization's mission statement reflect?",
      options: [
        "Financial sustainability goals",
        "A commitment to quality patient care, communicated to all staff",
        "Market share growth objectives",
        "The number of licensed beds",
      ],
      correctIndex: 1,
      explanation: "DNV GB.2 requires the mission to reflect commitment to quality patient care and be communicated to all staff. The mission is not just a document — it must be a living statement that guides organizational decisions and is known throughout the organization.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_16",
      question: "A board of trustees has no documented process for CEO succession. Under DNV GB.3, this represents:",
      options: [
        "An acceptable gap — succession planning is not required",
        "A deficiency — the governing body must establish a CEO succession process",
        "A deficiency only if the CEO has been in the role over 10 years",
        "Acceptable if a Deputy CEO has been appointed",
      ],
      correctIndex: 1,
      explanation: "DNV GB.3 requires the governing body to establish a CEO succession process as part of its executive leadership accountability. Without a documented succession process, the organization lacks governance continuity planning.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_17",
      question: "The governing body approves the initial medical staff bylaws at hospital opening. Under DNV GB.4, when must they be reviewed again at the latest?",
      options: [
        "Every 5 years",
        "Every 2 years",
        "Only when the medical staff requests changes",
        "Every 10 years",
      ],
      correctIndex: 1,
      explanation: "DNV GB.4 requires medical staff bylaws to be reviewed and re-approved at minimum every two years. This ensures the governance framework remains current and that the governing body maintains active oversight of medical staff governance.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_18",
      question: "Strategic plans are developed by administration and implemented without governing body review. Under DNV GB.2, this is:",
      options: [
        "Acceptable — strategic planning is an administrative function",
        "A deficiency — the governing body must approve the organization's strategic direction",
        "Acceptable if the plans align with the mission",
        "A deficiency only for strategies involving capital expenditure over $500,000",
      ],
      correctIndex: 1,
      explanation: "DNV GB.2 requires governing body approval of the organization's strategic direction and plan. Strategic planning is a governance responsibility, not purely an administrative function. Administration develops plans, but the governing body must approve them.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_19",
      question: "Which of the following governing body actions would BEST demonstrate active quality engagement under DNV GB.5?",
      options: [
        "Receiving quarterly quality reports filed in board packets",
        "Having the Quality Director brief the board annually",
        "Reviewing trended quality data, asking questions, directing specific corrective actions, and documenting all in meeting minutes",
        "Approving the Quality Management Plan at the start of each year",
      ],
      correctIndex: 2,
      explanation: "DNV GB.5 requires active participation, not passive receipt. The strongest evidence of compliance is governing body members actively engaging with data trends, asking substantive questions, and directing specific corrective actions — all documented in meeting minutes.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_gb_20",
      question: "Under DNV governance standards, which of the following statements about governing body independence is most accurate?",
      options: [
        "All governing body members should be employed by the hospital for operational expertise",
        "Governing body composition should include independent members not employed by management",
        "Independence requirements only apply to the board chair",
        "Governing body membership has no independence requirements under DNV",
      ],
      correctIndex: 1,
      explanation: "DNV GB.1 requires the governing body to include members who are independent of management. Independence is essential for the board to provide objective oversight and hold management accountable without conflicts of interest.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
