import type { Level } from "./schema";

export const dnvMrLevel: Level = {
  id: "dnv_mr",
  module: "dnv",
  name: "Medical Records",
  description: "DNV DIAS Section 26 — MR standards for medical record organization, content requirements, retention, confidentiality, authentication, and verbal order management.",
  icon: "FileText",
  color: "hsl(40, 65%, 45%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "MR: Medical Records Service",
    plainLanguageSummary:
      "DNV's Medical Records section establishes requirements for maintaining accurate, complete, confidential, and promptly completed medical records for every patient. Every record must contain specific content elements to justify admission, support diagnosis, and describe the patient's progress. All entries must be legible, dated, timed, and authenticated. Verbal orders must be authenticated within 48 hours. Records must be retained for at least 5 years and remain confidential. A coding and indexing system must enable retrieval by diagnosis and procedure.",
    keyOperationalExpectations: [
      "A complete medical record maintained for every inpatient and outpatient.",
      "All entries legible, dated, timed, and authenticated by the responsible clinician.",
      "Verbal orders authenticated within 48 hours by the prescribing or responsible practitioner.",
      "Records retained for minimum 5 years (or longer per applicable law).",
      "Medical records kept confidential with access limited to authorized personnel.",
      "Coding and indexing system allows retrieval by diagnosis and procedure for clinical audit.",
    ],
    commonRiskPoints: [
      "Verbal orders used routinely rather than in urgent situations, with authentication delays exceeding 48 hours.",
      "Medical records released without written patient authorization or appropriate legal order.",
      "Physical/electronic records accessible to unauthorized staff due to weak access controls.",
      "Records missing authentication on all entries — particularly nursing and ancillary staff entries.",
    ],
    cmsTags: ["MR.1", "MR.2", "MR.3", "MR.4", "MR.5", "MR.6", "MR.7"],
  },
  studyMaterial: [
    {
      title: "MR.1/MR.2 — Organization and Completeness",
      content:
        "Administrative responsibility for medical records rests with the medical records service. A medical record must be maintained for every individual evaluated or treated in any part of the organization. Records must accurately and completely document all orders, test results, evaluations, care plans, treatments, interventions, and the patient's response. The medical records service must define processes for completion, filing, and retrieval with defined timeframes. Records must be promptly completed after discharge.",
      keyPoint:
        "Medical records must be maintained for EVERY patient evaluated or treated anywhere in the organization. The completion, filing, and retrieval process must have defined timeframes.",
    },
    {
      title: "MR.3 — Retention and Destruction",
      content:
        "Medical records must be retained in their original or legally reproduced form for at least 5 years, or longer if required by applicable national/local laws. Records may be in hard copy, microfilm, or electronic form. The organization must have a coding and indexing system that allows timely retrieval by diagnosis and procedure to support clinical audit. If records are destroyed after the retention period, destruction must comply with all applicable laws and regulations.",
      keyPoint:
        "Minimum 5-year retention. Coding and indexing must enable retrieval by diagnosis AND procedure for clinical audit. Destruction must follow applicable legal requirements.",
    },
    {
      title: "MR.4 — Confidentiality and Access Control",
      content:
        "Confidentiality of medical records must be maintained at all times. Access is limited to individuals designated by law, regulation, and policy as having a need to know. Original records may only be released in accordance with national/local laws, court orders, or legal subpoenas. The organization must prevent unauthorized physical and electronic access to patient records. Policies for release of information must include written patient authorization for routine releases to external parties.",
      keyPoint:
        "Access limited by law and policy. Original records released only pursuant to law, court order, or subpoena. Patient written authorization required for routine external releases.",
    },
    {
      title: "MR.5 — Record Content and Authentication",
      content:
        "Medical records must contain information to: (1) justify admission and continued hospitalization; (2) support the diagnosis; and (3) describe the patient's progress and response to medications and services. All entries must be legible, complete, dated, and timed, and authenticated by the person responsible for care. Orders must be dated, timed, and authenticated promptly. Pre-printed order sets require the ordering practitioner to date, time, and authenticate the last page with the total number of pages identified.",
      keyPoint:
        "Every entry: legible, complete, dated, timed, authenticated. Pre-printed order sets: practitioner dates, times, and authenticates the last page identifying total pages. Internal changes must be initialed.",
    },
    {
      title: "MR.5/MR.6 — Verbal Orders and Author Identification",
      content:
        "Verbal orders are for urgent situations only and must be authenticated within 48 hours. Verbal orders are accepted only by personnel authorized by the medical staff. The ordering practitioner or a practitioner responsible for the patient's care must authenticate verbal orders within 48 hours. The organization must have a system to identify the author of each entry. Rubber stamps are permitted only when the identified individual has placed a signed statement in administrative offices confirming they alone use the stamp.",
      keyPoint:
        "Verbal orders: urgent use only, accept only by authorized personnel, authenticate within 48 hours. Every entry must have identifiable authorship — rubber stamps only with a signed administrative statement of sole use.",
    },
  ],
  questions: [
    {
      id: "dnv_mr_01",
      question: "Under DNV MR.1, for which patients must the hospital maintain a medical record?",
      options: [
        "Inpatients only",
        "Every individual evaluated or treated in any part of the organization",
        "Patients admitted for more than 24 hours",
        "Patients who receive surgical procedures",
      ],
      correctIndex: 1,
      explanation: "DNV MR.1 requires medical records for every individual evaluated or treated in any part or location of the organization — including outpatients, emergency visits, and all locations. There is no minimum length of stay or procedure threshold.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_02",
      question: "Under DNV MR.3, what is the minimum period for which medical records must be retained?",
      options: [
        "3 years",
        "5 years",
        "7 years",
        "10 years",
      ],
      correctIndex: 1,
      explanation: "DNV MR.3 requires medical records to be retained for at least 5 years (or longer if required by national/local laws). The 5-year minimum applies unless applicable law requires a longer period — in that case, the longer period governs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_03",
      question: "A verbal medication order is given by a physician on a Saturday. Under DNV MR.5, when must it be authenticated?",
      options: [
        "The next business day",
        "Within 48 hours",
        "Within 24 hours",
        "Within 7 days",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 requires verbal orders to be authenticated within 48 hours. This timeframe applies regardless of weekends, holidays, or whether the physician is on call. If national/local law specifies a shorter timeframe, that shorter period governs.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_04",
      question: "A patient requests a copy of their medical record. Under DNV MR.4, what is required?",
      options: [
        "Written patient authorization before release to external parties",
        "Physician approval before any record is released",
        "A court order is always required before releasing records",
        "Records may be released without restriction to any requesting party",
      ],
      correctIndex: 1,
      explanation: "DNV MR.4 requires written patient authorization for routine releases of medical records to external parties. Court orders and legal subpoenas allow release without patient authorization, but routine requests (including from the patient themselves) require appropriate authorization documentation.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_05",
      question: "A medical record entry is undated and unsigned. Under DNV MR.5, this is:",
      options: [
        "Acceptable if the entry is part of a pre-printed form",
        "Non-compliant — all entries must be dated, timed, and authenticated",
        "Acceptable if the identity of the author can be inferred from context",
        "Non-compliant only for physician entries",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 requires ALL entries to be legible, complete, dated, timed, and authenticated by the person responsible for providing care. No exceptions exist for pre-printed forms or inferred authorship — explicit authentication of each entry is required.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_06",
      question: "Under DNV MR.5, a physician uses a rubber stamp as their signature on medical record entries. Under what condition is this permissible?",
      options: [
        "Never — rubber stamps are never permitted",
        "When the physician has placed a signed statement in administrative offices confirming sole use of the stamp",
        "When the medical records director approves the use",
        "When the stamp includes the physician's DEA number",
      ],
      correctIndex: 1,
      explanation: "DNV MR.6 (through MR.5 authentication requirements) permits rubber stamps only when the individual whose signature the stamp represents has placed a signed statement in administrative offices confirming they alone have and use the stamp. No other person may use it under any circumstance.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_07",
      question: "Medical records are stored in an area that experiences periodic flooding. Under DNV MR.2, what is the concern?",
      options: [
        "No concern if electronic backup copies are maintained",
        "Records must be stored in areas that protect them from damage by flood, fire, and other casualties",
        "Concern only if the records are paper-based",
        "No concern if the flooding occurs infrequently",
      ],
      correctIndex: 1,
      explanation: "DNV MR.2 requires records to be stored in areas that ensure they are secure and protected from damage by flood, fire, and other casualties. Flood risk in the storage area is a direct threat to record integrity and must be mitigated.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_08",
      question: "Under DNV MR.3, the coding and indexing system must allow retrieval by which parameters?",
      options: [
        "Patient name and date of admission only",
        "Diagnosis and procedure, to support clinical audit",
        "Insurance carrier and attending physician",
        "Room number and length of stay",
      ],
      correctIndex: 1,
      explanation: "DNV MR.3 requires the coding and indexing system to allow timely retrieval by diagnosis and procedure to support clinical audit. This enables the organization to identify patterns in diagnoses and procedures for quality review and performance improvement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_09",
      question: "The three types of information that the medical record must contain under DNV MR.5 include which of the following?",
      options: [
        "Insurance information, patient preferences, and family contact details",
        "Justification for admission, support for diagnosis, and description of patient's progress/response",
        "Discharge instructions, follow-up appointments, and prescription list",
        "Nursing notes, physician orders, and billing codes",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 requires medical records to contain information to: (1) justify admission and continued hospitalization; (2) support the diagnosis; and (3) describe the patient's progress and response to medications and services. These three purposes define the minimum content standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_10",
      question: "Verbal orders are routinely used for all medication changes at the hospital because it is more efficient. Under DNV MR.5, this practice is:",
      options: [
        "Acceptable if all verbal orders are authenticated within 48 hours",
        "Non-compliant — verbal orders should be used only in urgent situations",
        "Acceptable for nursing-driven medication adjustments",
        "Non-compliant only for high-alert medications",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 specifies that telephone or verbal orders are to be used infrequently and only when clinically necessary (urgent situations). Routine use of verbal orders for efficiency is not appropriate under the standard — written or electronic orders should be used in non-urgent situations.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_11",
      question: "A physician authenticates a pre-printed order set by signing the first page only. Under DNV MR.5, this is:",
      options: [
        "Acceptable if the physician reviewed all pages before signing",
        "Non-compliant — the practitioner must date, time, and authenticate the last page, identifying the total number of pages",
        "Acceptable for standard order sets with 3 or fewer pages",
        "Non-compliant only for surgical order sets",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 SR.4b specifically requires that for pre-printed order sets, the ordering practitioner dates, times, and authenticates the LAST page of the order set, with the last page also identifying the total number of pages. Signing only the first page is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_12",
      question: "Under DNV MR.4, when may original medical records be released outside the hospital?",
      options: [
        "At any time when requested by another healthcare provider",
        "Only in accordance with national/local laws, court orders, or legal subpoenas",
        "When approved by the attending physician",
        "When the patient's insurance company requests them",
      ],
      correctIndex: 1,
      explanation: "DNV MR.4 SR.4 states that original medical records may be released by the hospital only in accordance with national and local laws, court orders, or legal subpoenas. Even when releasing copies, patient authorization is required for most external requests.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_13",
      question: "A medical records filing system has no mechanism to retrieve records by diagnosis. Under DNV MR.3, this is:",
      options: [
        "Acceptable if records can be retrieved by patient name",
        "Non-compliant — the system must allow retrieval by diagnosis and procedure for clinical audit",
        "Acceptable for facilities with fewer than 100 annual admissions",
        "Non-compliant only for the top 10 most common diagnoses",
      ],
      correctIndex: 1,
      explanation: "DNV MR.3 requires a coding and indexing system that allows timely retrieval by diagnosis AND procedure. A system that only retrieves by patient name cannot support the clinical audit function that is core to the medical records standard's purpose.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_14",
      question: "A verbal medication order is given and transcribed by an unlicensed nursing assistant. Under DNV MR.5, this is:",
      options: [
        "Acceptable if the nursing assistant reads the order back to the physician",
        "Non-compliant — verbal orders are accepted only by personnel authorized by the medical staff",
        "Acceptable if the charge nurse cosigns the order",
        "Non-compliant only for high-alert medications",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 SR.5a requires verbal orders to be accepted only by personnel authorized by the medical staff. Medical staff bylaws define who is authorized to accept verbal orders — unlicensed nursing assistants are not typically authorized to accept medication orders.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_15",
      question: "Under DNV MR.5, what must a practitioner do when a change (deletion) is made in the body of a pre-printed order set?",
      options: [
        "Draw a line through the deleted item without any further documentation",
        "Initial the change — all internal pages with changes must be signed or initialed by the ordering practitioner",
        "Delete the item electronically without documentation",
        "Have a witness cosign the deletion",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 SR.4c requires that changes (additions, deletions, strikeouts) in pre-printed order sets be initialed by the ordering practitioner, and all internal pages must be signed or initialed. This ensures the ordering practitioner has reviewed and authorized all modifications.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_16",
      question: "Medical records are kept in an area that can be accessed by non-clinical administrative staff without role-based access controls. Under DNV MR.4, this is:",
      options: [
        "Acceptable if staff have signed HIPAA training certificates",
        "Non-compliant — access must be limited to individuals designated by law, regulation, and policy",
        "Acceptable if the administrator is employed by the hospital",
        "Non-compliant only for records of VIP patients",
      ],
      correctIndex: 1,
      explanation: "DNV MR.4 requires access to medical records to be limited to individuals designated by law, regulation, and policy as having a need to know. Broad access by administrative staff without role-based controls fails the access limitation requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_17",
      question: "The hospital has no defined timeframe for completing medical records after patient discharge. Under DNV MR.2, this is:",
      options: [
        "Acceptable if records are eventually completed",
        "Non-compliant — the completion process must include defined timeframes",
        "Acceptable for hospitals with a small number of beds",
        "Non-compliant only if records are incomplete at 90 days",
      ],
      correctIndex: 1,
      explanation: "DNV MR.2 requires the medical records completion process to define timeframes for record completion after discharge. Without defined timeframes, there is no mechanism to ensure records are completed promptly — a core requirement of the standard.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_18",
      question: "Under DNV MR.5, when a practitioner signs an order, what additional elements must accompany the signature?",
      options: [
        "DEA number and NPI",
        "Date and time — separately added by the signing practitioner",
        "Department and specialty designation",
        "The patient's medical record number and diagnosis",
      ],
      correctIndex: 1,
      explanation: "DNV MR.5 SR.4a requires practitioners to separately date and time their signature when authenticating an entry, even if the document already has a date and time. The practitioner's authentication must independently reflect when THEY reviewed and approved the entry.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_19",
      question: "A medical record is destroyed 4 years after the patient's last visit. Under DNV MR.3, this is:",
      options: [
        "Acceptable if the patient is deceased",
        "Non-compliant — records must be retained for at least 5 years",
        "Acceptable if electronic backups exist",
        "Non-compliant only if applicable law requires longer retention",
      ],
      correctIndex: 1,
      explanation: "DNV MR.3 requires minimum 5-year retention. Destroying a record at 4 years violates this minimum retention requirement regardless of whether electronic backups exist, the patient's status, or whether applicable law would otherwise permit earlier destruction.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mr_20",
      question: "Under DNV MR.6, what system must exist for identifying the author of each medical record entry?",
      options: [
        "A verbal declaration system where clinicians state their name aloud",
        "An organizational system to identify the author of each entry, with entries made only by individuals specified in policy",
        "A witness cosignature for every entry",
        "A supervisor review system where all entries are reviewed within 24 hours",
      ],
      correctIndex: 1,
      explanation: "DNV MR.6 requires the organization to have a system to identify the author of each entry in the medical record, with entries made only by individuals specified in organization policies. This authorship system ensures accountability and prevents unauthorized documentation.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
