import type { Level } from "./schema";

export const dnvMmLevel: Level = {
  id: "dnv_mm",
  module: "dnv",
  name: "Medication Management",
  description: "DNV DIAS Section 11 — MM standards for medication ordering, dispensing, administration, high-alert medications, after-hours access, and ADR reporting.",
  icon: "Pill",
  color: "hsl(270, 55%, 48%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "MM: Medication Management",
    plainLanguageSummary:
      "DNV's Medication Management section covers the entire medication use process: ordering, dispensing, preparing, administering, and monitoring. Every step must be controlled by written policies. High-alert medications require special safeguards including double-check processes. Pharmacist oversight is required for all medication management. After-hours pharmacy access must be controlled and documented. All medication errors, adverse drug reactions, and drug incompatibilities must be reported immediately to the attending physician and to quality management for trending and corrective action.",
    keyOperationalExpectations: [
      "Written policies govern every phase of the medication use process.",
      "High-alert medications are identified, labeled, and subject to enhanced safeguards.",
      "After-hours pharmacy access is controlled with documented quantity and type of removal.",
      "All ADRs and medication errors are immediately reported to the attending physician.",
      "ADR/error data is aggregated, trended, and reviewed by quality management oversight.",
      "Drug information resources are available to all clinical staff.",
    ],
    commonRiskPoints: [
      "High-alert medications stored without special labeling or separation from other medications.",
      "After-hours pharmacy access occurs without documentation of type and quantity removed.",
      "ADRs documented in individual records but never aggregated for organizational trend analysis.",
      "Pharmacist review of after-hours medication removal not occurring routinely.",
    ],
    cmsTags: ["MM.1", "MM.2", "MM.3", "MM.4", "MM.5", "MM.6", "MM.7"],
  },
  studyMaterial: [
    {
      title: "MM.1 — Pharmaceutical Services Organization",
      content:
        "The hospital must maintain pharmaceutical services under the direction of a qualified pharmacist. Pharmacy services may be provided directly or through a contractual arrangement, but pharmacist oversight is always required. The pharmacist is responsible for all aspects of medication management: formulary management, drug procurement, storage, preparation, dispensing, and clinical oversight. Pharmacy policies and procedures must be developed by the pharmacist and reviewed at least annually.",
      keyPoint:
        "All pharmaceutical services require qualified pharmacist oversight — even when provided through contract. Pharmacist accountability cannot be fully delegated to nursing or administration.",
    },
    {
      title: "MM.2/MM.3 — Medication Ordering and Dispensing Controls",
      content:
        "Medication orders must be legible, complete (drug name, dose, route, frequency), and authenticated by the prescribing practitioner. Verbal orders are accepted only in urgent situations and must be authenticated within 48 hours. The pharmacy must review all medication orders before dispensing, with pharmacist clinical review of appropriateness, drug interactions, and dosing. Unit-dose dispensing is preferred to minimize preparation errors. Standing and PRN orders require special documentation and periodic review.",
      keyPoint:
        "Pharmacist review before dispensing is required. Verbal orders must be authenticated within 48 hours. Unit-dose dispensing is preferred for safety.",
    },
    {
      title: "MM.4 — High-Alert Medications",
      content:
        "The organization must maintain a list of high-alert medications — drugs that bear a heightened risk of causing significant patient harm when used in error (e.g., anticoagulants, insulin, concentrated electrolytes, opioids, chemotherapy). High-alert medications must be distinctively labeled and stored separately from routine medications. Enhanced safeguards are required: double-check processes, automated alerts, independent double-verification before administration, removal from floor stock where feasible.",
      keyPoint:
        "High-alert medications require: (1) organizational list, (2) distinctive labeling, (3) separate storage, (4) double-check/independent verification before administration. All four elements required.",
    },
    {
      title: "MM.5 — After-Hours Pharmacy Access",
      content:
        "When the pharmacy is closed, access must be controlled and limited to designated staff. The organization must have a policy identifying who may access the pharmacy or emergency medication supply, what quantity may be removed, and documentation requirements. Every removal must document the type and quantity of medication removed. A pharmacist or physician must review all after-hours removal activity and correlate removals with current medication orders. The pharmacy must routinely assess whether the emergency supply meets after-hours needs.",
      keyPoint:
        "After-hours access must be controlled, documented (type AND quantity), and reviewed by pharmacist/physician who correlates removals with current orders.",
    },
    {
      title: "MM.6 — ADR Reporting and Error Management",
      content:
        "Medication errors, adverse drug reactions (ADRs), and drug incompatibilities must be immediately reported to the attending physician. All such events must also be aggregated and reported to quality management for trending and analysis. The organization must measure the effectiveness of its reporting system to ensure errors are being identified at expected rates (compared to benchmarks). A non-punitive reporting culture is encouraged. The organization must demonstrate that aggregate data is analyzed and used to implement corrective actions.",
      keyPoint:
        "ADRs/errors require two-track reporting: (1) immediate notification to attending physician, and (2) aggregate reporting to QM for trending and corrective action. Both tracks are required.",
    },
  ],
  questions: [
    {
      id: "dnv_mm_01",
      question: "Under DNV MM.1, who must have oversight responsibility for all pharmaceutical services?",
      options: [
        "The Chief Nursing Officer",
        "A qualified pharmacist",
        "The Medical Director",
        "The hospital administrator",
      ],
      correctIndex: 1,
      explanation: "DNV MM.1 requires a qualified pharmacist to have oversight responsibility for all pharmaceutical services. Even when pharmacy services are provided through a contract, pharmacist oversight and accountability cannot be eliminated.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_02",
      question: "Concentrated potassium chloride is stored in the medication room alongside routine IV fluids without any special labeling. Under DNV MM.4, this is:",
      options: [
        "Acceptable if nursing staff know which medications are high-alert",
        "Non-compliant — high-alert medications must be distinctively labeled and stored separately",
        "Acceptable if the medication is locked",
        "Non-compliant only in the ICU",
      ],
      correctIndex: 1,
      explanation: "DNV MM.4 requires high-alert medications (including concentrated electrolytes like potassium chloride) to be distinctively labeled AND stored separately from routine medications. Storage alongside routine items without distinctive labeling creates serious error risk.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_03",
      question: "During after-hours pharmacy access, a nurse removes 10 tablets of oxycodone but does not document the quantity. Under DNV MM.5, this is:",
      options: [
        "Acceptable if the nurse later enters it in the medication administration record",
        "Non-compliant — type and quantity must be documented at time of removal",
        "Acceptable if a supervisor is present during the removal",
        "Non-compliant only for Schedule II controlled substances",
      ],
      correctIndex: 1,
      explanation: "DNV MM.5 requires documentation of both the type and quantity of every medication removed after hours, at the time of removal. Post-hoc documentation or MAR entries alone do not satisfy the after-hours removal documentation requirement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_04",
      question: "A patient experiences an adverse drug reaction to heparin. Under DNV MM.6, what immediate action is required?",
      options: [
        "Document the ADR in the medical record and file a report with the pharmacy next business day",
        "Immediately report the ADR to the attending physician",
        "File an internal incident report within 24 hours",
        "Report the ADR to the FDA MedWatch program within 72 hours",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 requires immediate reporting of ADRs to the attending physician. This immediate physician notification is the first required action — documentation and aggregate reporting to quality management are also required but follow the immediate clinical response.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_05",
      question: "ADR data is collected in individual patient records but is never aggregated for organizational trend analysis. Under DNV MM.6, this is:",
      options: [
        "Acceptable if ADRs are reported to the attending physician",
        "Non-compliant — ADR data must be aggregated and reported to quality management for trending",
        "Acceptable if the pharmacy reviews ADRs on a case-by-case basis",
        "Non-compliant only if the ADR rate is above national benchmarks",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 requires a two-track reporting system: immediate physician notification AND aggregate reporting to quality management for trending and corrective action. Aggregate analysis is required to identify systemic patterns that individual case review cannot reveal.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_06",
      question: "A pharmacist has not reviewed after-hours medication removal activity for 3 months. Under DNV MM.5, this is:",
      options: [
        "Acceptable if no discrepancies were identified",
        "Non-compliant — a pharmacist must routinely review all after-hours removal activity",
        "Acceptable if the charge nurse reviewed the removals",
        "Non-compliant only for controlled substances",
      ],
      correctIndex: 1,
      explanation: "DNV MM.5 requires a pharmacist (or physician) to review all after-hours removal activity and correlate removals with current medication orders. This review must occur routinely — not just when discrepancies are suspected.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_07",
      question: "Under DNV MM.2, a verbal medication order is given in a non-urgent situation. What is required?",
      options: [
        "Verbal orders are always acceptable and must be authenticated within 48 hours",
        "Verbal orders should be avoided in non-urgent situations and must be authenticated within 48 hours",
        "Verbal orders are not permitted under any circumstances",
        "Verbal orders require authentication within 24 hours only for controlled substances",
      ],
      correctIndex: 1,
      explanation: "DNV MM.2 requires verbal orders to be used only in urgent situations. In non-urgent situations, written or electronic orders are preferred. All verbal orders, regardless of urgency, must be authenticated by the prescribing practitioner within 48 hours.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_08",
      question: "A hospital does not have a formal list of high-alert medications. Under DNV MM.4, this is:",
      options: [
        "Acceptable if nurses are educated about commonly dangerous medications",
        "Non-compliant — the organization must maintain a formal high-alert medication list",
        "Acceptable if the pharmacy reviews all orders before dispensing",
        "Non-compliant only if a high-alert medication error has occurred",
      ],
      correctIndex: 1,
      explanation: "DNV MM.4 requires the organization to formally identify and list high-alert medications. This written list drives the safeguards (labeling, storage, verification) that protect patients. Education without a formal list is insufficient.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_09",
      question: "Under DNV MM.3, before dispensing a medication, what review must occur?",
      options: [
        "A nursing review of the patient's allergies",
        "A pharmacist clinical review of appropriateness, drug interactions, and dosing",
        "A physician co-signature on the pharmacy label",
        "A nursing verification that the dose is within the standard range",
      ],
      correctIndex: 1,
      explanation: "DNV MM.3 requires pharmacist clinical review before dispensing — assessing appropriateness, drug interactions, and dosing. This pharmacist review is a clinical safeguard, not just a dispensing function, and cannot be replaced by nursing review.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_10",
      question: "The organization's ADR reporting rate seems unusually low compared to peer institutions. Under DNV MM.6, what does this finding require?",
      options: [
        "No action if no patient harm has resulted",
        "An assessment of reporting system effectiveness compared to established benchmarks",
        "Automatic disciplinary action for non-reporting staff",
        "Consultation with the state pharmacy board",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 requires the organization to measure reporting system effectiveness, including comparison to benchmarks and published peer-reviewed reporting rates. A low ADR rate compared to peers suggests underreporting — requiring investigation and system improvement.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_11",
      question: "Insulin is not on the hospital's high-alert medication list. Under DNV MM.4, what concern does this raise?",
      options: [
        "No concern — insulin is a commonly used medication",
        "Insulin is a universally recognized high-alert medication and must be on the list",
        "Concern only for U-500 concentrated insulin, not U-100",
        "No concern if nurses routinely double-check insulin doses",
      ],
      correctIndex: 1,
      explanation: "Insulin is universally recognized as a high-alert medication by ISMP and is consistently cited in DNV survey findings when not properly identified and safeguarded. All insulin formulations require high-alert designation with appropriate safeguards.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_12",
      question: "The pharmacy policies have not been reviewed in 3 years. Under DNV MM.1, this is:",
      options: [
        "Acceptable if no medication errors have occurred",
        "Non-compliant — pharmacy policies must be reviewed at least annually",
        "Acceptable if the pharmacist has been in the role for 3+ years",
        "Non-compliant only if the pharmacy director has changed",
      ],
      correctIndex: 1,
      explanation: "DNV MM.1 requires pharmacy policies and procedures to be reviewed at least annually. Annual review ensures policies reflect current standards, regulations, formulary changes, and lessons learned from medication safety events.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_13",
      question: "A medication error involving the wrong dose of a high-alert medication is identified. Under DNV MM.6, who must be notified immediately?",
      options: [
        "The pharmacy director only",
        "The attending physician",
        "The Risk Management department",
        "The state health department",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 requires immediate notification of drug errors to the attending physician. The attending physician's immediate awareness allows for clinical intervention if needed. Other notifications (Risk Management, QM) follow the immediate physician notification.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_14",
      question: "Under DNV MM.5, who must the organization policy designate as authorized to access the pharmacy after hours?",
      options: [
        "Any licensed nurse in the facility",
        "Specific individuals designated by name with appropriate qualifications",
        "Any licensed clinical professional",
        "The House Supervisor and any available nurse",
      ],
      correctIndex: 1,
      explanation: "DNV MM.5 requires the after-hours access policy to identify designated individuals by name with appropriate qualifications. Open access to 'any licensed nurse' does not provide the controlled access required — specific designation by name is required.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_15",
      question: "Drug information resources are available only in the pharmacy and not in patient care areas. Under DNV MM.7, this is:",
      options: [
        "Acceptable — pharmacy staff will answer drug information questions",
        "Non-compliant — drug information must be available to all clinical staff involved in medication management",
        "Acceptable for facilities with 24-hour pharmacy coverage",
        "Non-compliant only for ICU and emergency areas",
      ],
      correctIndex: 1,
      explanation: "DNV MM.7 requires drug information resources (drug interactions, side effects, dosing, toxicology) to be available to ALL staff involved in medication management — not just pharmacy staff. Bedside nursing staff need immediate access to drug information during medication administration.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_16",
      question: "A hospital requires an independent double-check before administering IV heparin. Which DNV MM standard does this safeguard specifically address?",
      options: [
        "MM.2 — Medication Ordering",
        "MM.4 — High-Alert Medications",
        "MM.5 — After-Hours Access",
        "MM.6 — ADR Reporting",
      ],
      correctIndex: 1,
      explanation: "DNV MM.4 requires enhanced safeguards for high-alert medications including independent double-check/verification processes before administration. Heparin is a recognized high-alert medication requiring these additional safety measures.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_17",
      question: "A hospital's corrective action for a pattern of insulin errors is to 'remind staff to be more careful.' Under DNV MM.6, why is this insufficient?",
      options: [
        "It is sufficient if the reminder is documented",
        "ADR/error aggregate analysis must lead to system-level corrective actions, not just behavioral reminders",
        "It is insufficient only if errors occurred in the ICU",
        "It is sufficient if the pharmacist approved the corrective action",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 requires aggregate ADR/error data to drive meaningful corrective actions. Behavioral reminders ('be more careful') are system-level failures disguised as individual blame — they do not address the system factors (labeling, access, verification) that created the error opportunity.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_18",
      question: "Under DNV MM.3, medication orders must contain which minimum elements?",
      options: [
        "Drug name and dose only",
        "Drug name, dose, route, and frequency",
        "Drug name, dose, route, frequency, and patient's diagnosis",
        "Drug name and prescribing physician name only",
      ],
      correctIndex: 1,
      explanation: "DNV MM.3 requires medication orders to be complete with drug name, dose, route, and frequency. Orders missing any of these elements are incomplete and must be clarified before the medication is dispensed or administered.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_19",
      question: "The emergency supply in a satellite pharmacy has not been assessed for adequacy in 2 years. Under DNV MM.5, this is:",
      options: [
        "Acceptable if no after-hours access has been needed",
        "Non-compliant — the pharmacy must routinely assess whether the emergency supply meets after-hours needs",
        "Acceptable if the supply matches the hospital's formulary",
        "Non-compliant only for critical care areas",
      ],
      correctIndex: 1,
      explanation: "DNV MM.5 requires the pharmacy to routinely assess whether the emergency supply is adequate to meet after-hours needs and to implement corrective action when deficiencies are identified. A 2-year gap in this assessment is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_mm_20",
      question: "Under DNV MM.6, what approach does DNV encourage for improving ADR and medication error reporting rates?",
      options: [
        "A punitive system that identifies and disciplines non-reporting staff",
        "A non-punitive system focused on system improvement rather than individual blame",
        "Mandatory reporting requirements with automatic consequences for non-compliance",
        "Anonymous reporting with no individual accountability",
      ],
      correctIndex: 1,
      explanation: "DNV MM.6 specifically encourages a non-punitive reporting system focused on the system rather than individual staff. Non-punitive cultures improve reporting rates, which is essential for identifying the true scope of medication errors and implementing meaningful system corrections.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
