import type { Level } from "./schema";

export const dnvPeLevel: Level = {
  id: "dnv_pe",
  module: "dnv",
  name: "Physical Environment & Safety",
  description: "DNV DIAS Section 4 — RM/PE standards covering risk management, physical environment safety, life safety, utility systems, and emergency preparedness.",
  icon: "Building",
  color: "hsl(55, 65%, 42%)",
  requiredScore: 0,
  chapterSummary: {
    chapterTitle: "RM/PE: Risk Management & Physical Environment",
    plainLanguageSummary:
      "DNV's Physical Environment and Risk Management sections require hospitals to identify and manage risks in the physical environment, maintain safe utility systems, conduct life safety compliance activities, and implement a comprehensive risk management program. The physical environment must be safe, functional, and supportive of patient care. Utility systems must be maintained and tested. The organization must have a plan for managing emergencies affecting the physical environment. Risk management must be integrated with quality management and include incident reporting, risk analysis, and corrective action.",
    keyOperationalExpectations: [
      "Physical environment inspections conducted regularly to identify safety hazards.",
      "Utility systems (electrical, medical gas, water, HVAC) maintained with documented testing.",
      "Life safety code compliance maintained and documented.",
      "Risk management program integrated with quality management with incident reporting and analysis.",
      "Emergency operations plan (EOP) addresses physical environment failures.",
      "Environment of care risks proactively identified and corrected before patient harm occurs.",
    ],
    commonRiskPoints: [
      "Utility system testing (generators, medical gas) not documented or performed at required intervals.",
      "Life safety deficiencies identified during fire marshal inspections not corrected within required timeframes.",
      "Risk management data collected but never analyzed for patterns or linked to quality improvement.",
      "Emergency operations plan not tested with drills or exercises at required frequencies.",
    ],
    cmsTags: ["RM.1", "RM.2", "RM.3", "RM.4", "PE.1", "PE.2", "PE.3", "PE.4"],
  },
  studyMaterial: [
    {
      title: "RM.1/RM.2 — Risk Management Program",
      content:
        "The hospital must maintain a comprehensive risk management program that identifies, evaluates, and addresses patient, visitor, and staff safety risks. The program must include: incident identification and reporting systems (with a non-punitive culture), risk analysis to identify root causes and contributing factors, corrective/preventive actions, and integration with the quality management system. Risk data must be analyzed for patterns and trends. The risk management program must receive input from all departments and services.",
      keyPoint:
        "Risk management must identify, evaluate, and correct risks proactively — not just reactively. Non-punitive reporting culture, pattern analysis, and QM integration are all required.",
    },
    {
      title: "PE.1 — Physical Environment Safety",
      content:
        "The hospital's physical environment must be safe, functional, and supportive of patient care. The organization must conduct regular inspections to identify physical environment safety hazards. Hazards must be corrected promptly — or if immediate correction is not possible, interim safety measures must be implemented. The environment must comply with applicable building codes, fire codes, and life safety requirements. Access to patient care areas must be controlled to prevent unauthorized entry.",
      keyPoint:
        "Regular inspections required. Hazards must be corrected promptly — or interim measures implemented. Life safety code compliance is not optional — it is a DNV requirement.",
    },
    {
      title: "PE.2 — Utility Systems Management",
      content:
        "The organization must maintain safe and functional utility systems including electrical systems, medical gas and vacuum systems, water systems, HVAC/ventilation, and emergency power. All utility systems must be maintained with documented preventive maintenance programs, regular testing, and inspection records. Emergency power systems (generators) must be tested at defined intervals. Medical gas systems require installer performance testing, verification testing, and routine maintenance. Utility failures must be managed through contingency plans.",
      keyPoint:
        "All utility systems require: documented PM programs, regular testing at defined intervals, inspection records, and contingency plans for failures. Medical gas and emergency power have specific testing requirements.",
    },
    {
      title: "PE.3 — Life Safety Code and Fire Safety",
      content:
        "The hospital must comply with applicable life safety requirements including fire protection, means of egress, occupancy requirements, and construction requirements. The organization must conduct fire drills at required frequencies with documented critiques. Fire detection and suppression systems must be maintained, tested, and inspected. The organization must have plans for managing construction and renovation projects to maintain life safety (Interim Life Safety Measures/ILSM). Life safety deficiencies identified during inspections must be corrected within defined timeframes.",
      keyPoint:
        "Fire drills at required frequency with documented critiques. Fire systems maintained, tested, inspected. Construction requires ILSM/fire watch plan. Deficiencies require timely correction.",
    },
    {
      title: "PE.4 — Emergency Preparedness and Operations Plan",
      content:
        "The hospital must have a comprehensive Emergency Operations Plan (EOP) that addresses how the organization will respond to and recover from emergencies affecting the physical environment and patient care operations. The EOP must be developed based on a Hazard Vulnerability Analysis (HVA) that identifies the most likely threats. The EOP must be exercised (drilled) at defined intervals with documented after-action reviews. The plan must address utility failures, building damage, patient evacuation, and coordination with community emergency response.",
      keyPoint:
        "EOP must be based on HVA, exercised at required intervals, with documented after-action reviews. Must address utility failures, building damage, patient evacuation, and community coordination.",
    },
  ],
  questions: [
    {
      id: "dnv_pe_01",
      question: "Under DNV RM.1, what must the risk management program include regarding incident reporting?",
      options: [
        "A punitive system to discourage careless behavior",
        "A non-punitive incident reporting system with pattern analysis and integration with quality management",
        "Mandatory external reporting of all incidents to regulatory agencies",
        "A confidential system visible only to senior leadership",
      ],
      correctIndex: 1,
      explanation: "DNV RM.1 requires a non-punitive incident reporting culture, pattern analysis of incidents, corrective/preventive actions, and integration with the quality management system. Punitive systems suppress reporting and undermine the risk management program's effectiveness.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_02",
      question: "A physical environment inspection identifies a faulty fire door that cannot be corrected immediately due to parts availability. Under DNV PE.1, what is required?",
      options: [
        "Close the affected area until repairs are complete",
        "Implement interim safety measures while awaiting repair",
        "Document the deficiency and repair it within 90 days",
        "Notify the state fire marshal and await their direction",
      ],
      correctIndex: 1,
      explanation: "DNV PE.1 requires hazards to be corrected promptly — but when immediate correction is not possible, interim safety measures must be implemented. For a faulty fire door, interim measures may include enhanced fire watch, temporary barriers, or other compensatory measures.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_03",
      question: "The hospital's emergency generator has not been tested for 6 months. Under DNV PE.2, this is:",
      options: [
        "Acceptable if the generator has never failed",
        "Non-compliant — emergency power systems must be tested at defined intervals",
        "Acceptable for hospitals with dual utility feeds",
        "Non-compliant only if the hospital is in an area prone to power outages",
      ],
      correctIndex: 1,
      explanation: "DNV PE.2 requires emergency power systems to be tested at defined intervals with documented results. Regular testing at defined intervals (typically monthly load tests and annual extended load tests) is required regardless of failure history or local power reliability.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_04",
      question: "Under DNV PE.4, what analysis must be used to develop the Emergency Operations Plan?",
      options: [
        "A patient satisfaction analysis",
        "A Hazard Vulnerability Analysis (HVA)",
        "A financial impact analysis",
        "A workforce capacity analysis",
      ],
      correctIndex: 1,
      explanation: "DNV PE.4 requires the Emergency Operations Plan to be developed based on a Hazard Vulnerability Analysis (HVA) that identifies the most likely threats to the organization. The HVA drives prioritization of planning efforts toward the highest-probability, highest-impact threats.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_05",
      question: "Fire drills are conducted but no post-drill critique or documentation is produced. Under DNV PE.3, this is:",
      options: [
        "Acceptable if the drill was observed by the fire marshal",
        "Non-compliant — fire drills must be documented with critiques",
        "Acceptable if no deficiencies were observed during the drill",
        "Non-compliant only if the drill failed to meet evacuation time standards",
      ],
      correctIndex: 1,
      explanation: "DNV PE.3 requires fire drills to be documented with critiques. The post-drill critique identifies improvement opportunities and demonstrates that the organization uses drills as a learning exercise — not just a compliance checkbox. Documentation without critique is insufficient.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_06",
      question: "Risk management data is collected from incident reports but never analyzed for patterns or trends. Under DNV RM.2, this is:",
      options: [
        "Acceptable if individual incidents are investigated",
        "Non-compliant — risk data must be analyzed for patterns and trends to drive corrective action",
        "Acceptable if the Chief Risk Officer reviews reports monthly",
        "Non-compliant only if patient harm has occurred",
      ],
      correctIndex: 1,
      explanation: "DNV RM.2 requires risk data to be analyzed for patterns and trends. Individual investigation of incidents without aggregate pattern analysis cannot identify systemic risk factors that drive ongoing patient safety risks across the organization.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_07",
      question: "Under DNV PE.4, the Emergency Operations Plan must be exercised how frequently?",
      options: [
        "Only when real emergencies occur",
        "At defined intervals with documented after-action reviews",
        "Every 5 years",
        "Annually for new staff only",
      ],
      correctIndex: 1,
      explanation: "DNV PE.4 requires the EOP to be exercised at defined intervals with documented after-action reviews. The intervals must be defined in policy (typically twice annually for community-scale exercises) and after-action reviews must identify improvement opportunities.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_08",
      question: "Construction is occurring in a hospital wing adjacent to patient care areas. Under DNV PE.3, what is required?",
      options: [
        "Closing the construction area to all hospital staff",
        "Implementing Interim Life Safety Measures (ILSM) to maintain life safety during construction",
        "Relocating all patients in the adjacent wing",
        "Hiring an external fire marshal to monitor the construction",
      ],
      correctIndex: 1,
      explanation: "DNV PE.3 requires Interim Life Safety Measures (ILSM) during construction and renovation projects that impair life safety systems or egress paths. ILSM may include enhanced fire watch, additional staff training, temporary fire barriers, or increased evacuation drills.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_09",
      question: "Medical gas systems in the OR have never had installer performance testing or third-party verification testing. Under DNV PE.2, this is:",
      options: [
        "Acceptable if the gas systems have been functioning without complaints",
        "Non-compliant — medical gas systems require specific installer and third-party verification testing",
        "Acceptable if the anesthesia staff perform daily checks",
        "Non-compliant only for nitrous oxide systems",
      ],
      correctIndex: 1,
      explanation: "DNV PE.2 requires medical gas systems to have installer performance testing, third-party verification testing, and routine maintenance documentation. The complexity and patient safety implications of medical gas systems require specific validated testing — not just operational checks.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_10",
      question: "Under DNV RM.1, risk management data must be integrated with which organizational function?",
      options: [
        "The human resources department",
        "The quality management system",
        "The finance department",
        "The marketing department",
      ],
      correctIndex: 1,
      explanation: "DNV RM.1 requires the risk management program to be integrated with the quality management system. This integration ensures that identified risks drive quality improvement activities and that QM data informs risk identification — creating a unified approach to organizational safety.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_11",
      question: "A life safety deficiency identified during an AHJ inspection is still not corrected after 12 months. Under DNV PE.3, what is the compliance status?",
      options: [
        "Acceptable if the organization submitted a written plan of correction",
        "Non-compliant — life safety deficiencies must be corrected within defined timeframes",
        "Acceptable if the deficiency is classified as low risk",
        "Non-compliant only if patient harm resulted",
      ],
      correctIndex: 1,
      explanation: "DNV PE.3 requires life safety deficiencies to be corrected within defined timeframes. While interim measures can be used while awaiting repairs, indefinite delays in correction are non-compliant. DNV surveyors will review AHJ inspection reports and correction timelines.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_12",
      question: "The Emergency Operations Plan does not address utility failures. Under DNV PE.4, this is:",
      options: [
        "Acceptable if the hospital has never experienced a utility failure",
        "Non-compliant — the EOP must address utility failures among other emergency scenarios",
        "Acceptable if utility failures are addressed in a separate contingency plan",
        "Non-compliant only for hospitals in high-risk geographic areas",
      ],
      correctIndex: 1,
      explanation: "DNV PE.4 requires the EOP to address utility failures as one of the emergency scenarios. Utility failures (power, water, medical gas) are among the most common physical environment emergencies in hospitals and must be explicitly addressed in the plan.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_13",
      question: "Under DNV PE.1, which of the following best describes the required approach to physical environment safety?",
      options: [
        "Reactive correction of hazards after they are identified by staff or surveyors",
        "Proactive identification of hazards through regular inspections with prompt correction",
        "Annual safety survey conducted by an external consultant",
        "Staff self-reporting of hazards with 30-day correction timelines",
      ],
      correctIndex: 1,
      explanation: "DNV PE.1 requires a proactive approach: regular inspections to identify hazards before they cause harm, with prompt correction of identified hazards. Reactive or annual-only approaches do not satisfy the regular inspection and prompt correction requirements.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_14",
      question: "The risk management program collects incident reports only from nursing staff, excluding ancillary departments. Under DNV RM.1, this is:",
      options: [
        "Acceptable if nursing staff are the primary care providers",
        "Non-compliant — the risk management program must receive input from all departments and services",
        "Acceptable if the nursing staff report on behalf of all departments",
        "Non-compliant only if ancillary staff incidents have caused patient harm",
      ],
      correctIndex: 1,
      explanation: "DNV RM.1 requires the risk management program to receive input from all departments and services. Risks that originate in environmental services, dietary, pharmacy, maintenance, or other support areas can directly affect patient safety — limiting reporting to nursing creates blind spots.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_15",
      question: "Under DNV PE.2, what must accompany a preventive maintenance program for utility systems?",
      options: [
        "Staff satisfaction surveys about utility system reliability",
        "Documented testing records, inspection records, and contingency plans for failures",
        "Annual cost-benefit analysis of PM activities",
        "External certification of all utility system components",
      ],
      correctIndex: 1,
      explanation: "DNV PE.2 requires utility system PM programs to include documented testing records, inspection records, and contingency plans for failures. Documentation of PM activities is the evidence of compliance — programs without documentation cannot be verified.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_16",
      question: "An Environmental Services staff member discovers a slip-and-fall hazard (wet floor without signage) and reports it. Under DNV RM.1, what should occur?",
      options: [
        "The staff member should be commended privately",
        "The hazard should be immediately corrected and the report incorporated into risk management data for pattern analysis",
        "The report should be filed and reviewed annually",
        "The staff member should be informed that slip-and-falls are not a risk management concern",
      ],
      correctIndex: 1,
      explanation: "DNV RM.1 requires incident reports to be acted upon (correcting the immediate hazard) and incorporated into risk management pattern analysis. A single report may not reveal a pattern, but aggregate analysis of similar reports across the organization might reveal systemic wet floor or signage deficiencies.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_17",
      question: "Under DNV PE.3, fire detection and suppression systems must be:",
      options: [
        "Present — no maintenance or testing is required beyond initial installation",
        "Maintained, tested, and inspected at required intervals",
        "Tested only after a fire event",
        "Replaced every 10 years regardless of condition",
      ],
      correctIndex: 1,
      explanation: "DNV PE.3 requires fire detection and suppression systems to be maintained, tested, and inspected at required intervals. Regular testing verifies that these life safety systems will function when needed — presence without maintenance creates false security.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_18",
      question: "The Emergency Operations Plan has never been tested with a drill or exercise. Under DNV PE.4, this is:",
      options: [
        "Acceptable if the plan has been reviewed and updated annually",
        "Non-compliant — the EOP must be exercised at defined intervals",
        "Acceptable if the organization has successfully responded to real emergencies",
        "Non-compliant only for hospitals with large emergency departments",
      ],
      correctIndex: 1,
      explanation: "DNV PE.4 requires the EOP to be exercised at defined intervals. A plan that has never been tested cannot be assumed to be workable — exercises reveal gaps in the plan, staff familiarity, resource availability, and inter-department coordination.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_19",
      question: "Under DNV RM.2, when corrective/preventive actions are implemented for an identified risk, what must be verified?",
      options: [
        "That the corrective action was approved by the governing body",
        "That the corrective action was effective in reducing or eliminating the identified risk",
        "That the corrective action was implemented within 30 days",
        "That all staff are aware of the corrective action",
      ],
      correctIndex: 1,
      explanation: "DNV RM.2 requires verification that corrective/preventive actions were effective in reducing or eliminating the identified risk. Simply implementing an action without measuring its effectiveness is insufficient — the risk management cycle must close with verified effectiveness.",
      xpReward: 10,
      isSwipe: false,
    },
    {
      id: "dnv_pe_20",
      question: "The hospital's HVAC system in the OR has not been tested for air pressure, temperature, and humidity in 2 years. Under DNV PE.2, this is:",
      options: [
        "Acceptable if no air quality complaints have been received",
        "Non-compliant — HVAC systems require regular testing at defined intervals with documented results",
        "Acceptable if the OR temperature is monitored daily by nursing staff",
        "Non-compliant only during outbreak periods",
      ],
      correctIndex: 1,
      explanation: "DNV PE.2 requires all utility systems including HVAC/ventilation to be maintained with regular testing at defined intervals with documented results. OR air pressure, temperature, and humidity directly affect infection control — the 2-year gap in testing is non-compliant.",
      xpReward: 10,
      isSwipe: false,
    },
  ],
};
