import type { Level } from "./schema";

export const levels: Level[] = [
  {
    id: "transport",
    name: "Transport of Instruments",
    description: "Master the proper handling and transport of surgical instruments from OR to sterile processing.",
    icon: "Truck",
    color: "hsl(152, 82%, 39%)",
    requiredScore: 0,
    questions: [
      {
        id: "t1",
        question: "Where should clean red bins with lids be stored when not in use?",
        scenario: "You just finished a case and need to store equipment properly.",
        options: ["Soiled utility room", "Clean supply room", "OR hallway"],
        correctIndex: 1,
        explanation: "Clean red bins/rigid containers with lids must be stored in the clean supply room, never in soiled areas.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t2",
        question: "Should gross bioburden be removed from instruments at the point of use?",
        scenario: "A surgical case just ended. The scrub tech is handling used instruments.",
        options: ["Yes, always", "No, that's SPD's job"],
        correctIndex: 0,
        explanation: "Gross bioburden must be removed at the point of use to prevent drying and make decontamination more effective.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "t3",
        question: "How should instruments be positioned before transport to sterile processing?",
        options: ["Locked/closed position", "Open/unhinged position", "Stacked tightly", "Wrapped in drapes"],
        correctIndex: 1,
        explanation: "Instruments must be placed in the open/unhinged position before transport to ensure proper cleaning of all surfaces.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t4",
        question: "Is enzymatic spray applied correctly if a staff member uses it without gloves?",
        scenario: "You observe a colleague applying enzymatic pre-cleaner to instruments bare-handed.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Enzymatic spray must be applied with appropriate PPE including gloves. Chemical exposure without protection is a safety violation.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t5",
        question: "After applying enzymatic spray, what must happen to the instrument container?",
        options: ["Leave open for ventilation", "Secure the lid before transport", "Stack on top of other bins", "Label with patient info"],
        correctIndex: 1,
        explanation: "The lid must be secured before transporting to the soiled room to prevent contamination and splashing during transport.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t6",
        question: "Is it acceptable to transport soiled instruments through the clean core?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Soiled instruments must never be transported through clean areas. Designated soiled corridors prevent cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t7",
        question: "What PPE should be available in the soiled utility room?",
        options: ["Just gloves", "Gloves and face shield only", "Gloves, gown, face shield/goggles, and mask", "No PPE needed"],
        correctIndex: 2,
        explanation: "The soiled utility room must have full PPE available: gloves, gown, face shield or goggles, and a mask for safe handling of contaminated items.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t8",
        question: "Should pre-cleaner solution be available in the soiled utility room?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Pre-cleaner solution must be available in the soiled utility room for initial instrument decontamination before transport to SPD.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "environment",
    name: "Environment & Surfaces",
    description: "Identify infection prevention issues related to walls, ceilings, and environmental surfaces.",
    icon: "Building2",
    color: "hsl(217, 91%, 52%)",
    requiredScore: 60,
    questions: [
      {
        id: "e1",
        question: "You see tape residue on a wall in a patient care area. Is this compliant?",
        scenario: "During your rounds, you notice old tape marks and residue on the wall near a patient bed.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Areas must be free of visible tape and tape residue. This creates surfaces that cannot be properly cleaned and may harbor pathogens.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e2",
        question: "What should you do if you find a cracked ceiling tile in a procedure area?",
        options: ["Report it immediately", "Cover it with tape", "Ignore if small", "Paint over it"],
        correctIndex: 0,
        explanation: "Cracked or damaged ceiling tiles must be reported immediately. They can harbor mold, dust, and pathogens that could contaminate the sterile field.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "e3",
        question: "Is visible dust on overhead lights in a clinical area acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Overhead lights, booms, and carts must be free of visible dust. Dust can harbor microorganisms and fall into sterile fields.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e4",
        question: "You notice a small hole in the countertop of a medication prep area. What should happen?",
        options: ["Fill it with caulk yourself", "Report for proper repair", "Cover with contact paper", "It's fine if kept clean"],
        correctIndex: 1,
        explanation: "Countertops must be intact and impervious. Holes and cracks cannot be properly disinfected and must be professionally repaired.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "e5",
        question: "Are stained ceiling tiles in a sterile storage area a compliance concern?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Stained ceiling tiles may indicate water damage or leaks, which can lead to mold growth and contamination of stored sterile supplies.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "e6",
        question: "Which surface issue would NOT typically be flagged during an EOC round?",
        options: ["Tape residue on walls", "Dust on light fixtures", "Minor scuff marks on the floor", "Hole in the wall"],
        correctIndex: 2,
        explanation: "Minor floor scuffs are normal wear. Tape residue, dust accumulation, and wall damage are all infection prevention concerns.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
  {
    id: "segregation",
    name: "Clean vs. Dirty",
    description: "Master the principles of clean and dirty segregation in clinical environments.",
    icon: "ArrowLeftRight",
    color: "hsl(270, 60%, 55%)",
    requiredScore: 60,
    questions: [
      {
        id: "s1",
        question: "Equipment is stored directly on the floor in the clean utility room. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Nothing should be stored on the floor. Items must be on shelves or racks at least 6-8 inches off the floor for proper cleaning.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "s2",
        question: "Where should soiled linen be stored?",
        options: ["In a covered hamper in a designated soiled area", "In the clean utility room in bags", "In any available room", "In the hallway near the exit"],
        correctIndex: 0,
        explanation: "Soiled linen must be in covered hampers in designated soiled areas to prevent cross-contamination with clean supplies.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s3",
        question: "Can clean and soiled items be processed in the same sink?",
        options: ["Yes, if cleaned between uses", "No, never"],
        correctIndex: 1,
        explanation: "Clean and soiled items must never share the same sink. Designated sinks prevent cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s4",
        question: "You see a staff member's lunch in the medication room refrigerator. Is this acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Staff food and beverages must never be stored in clinical areas or medication refrigerators. This is a serious contamination and food safety concern.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s5",
        question: "Clean linen should be stored in which of the following ways?",
        options: ["Open shelving in the hallway", "In a clean room or covered cart", "In the soiled utility room in bags", "Any location is fine"],
        correctIndex: 1,
        explanation: "Clean linen must be stored in a designated clean room or on a covered cart to prevent contamination from airborne particles.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s6",
        question: "Is it acceptable to have a staff coffee mug at the nurses' station in a patient care area?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Staff food and drinks are not permitted in clinical/patient care areas. They must be kept in designated break rooms.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "sterile_storage",
    name: "Sterile Storage",
    description: "Learn the standards for proper sterile supply storage and event-related sterility.",
    icon: "Package",
    color: "hsl(32, 95%, 55%)",
    requiredScore: 60,
    questions: [
      {
        id: "ss1",
        question: "You find sterile supplies stored in their original cardboard shipping boxes. Is this compliant?",
        scenario: "During a supply room check, you notice boxes of sterile gloves still in their brown cardboard shipping containers on the shelf.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Cardboard shipping boxes are not permitted in sterile storage areas. Cardboard harbors dust, insects, and cannot be properly cleaned.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss2",
        question: "What type of shelving is required for sterile supply storage?",
        options: ["Any shelving is fine", "Wire shelving with impervious bottom shelf", "Wood shelving", "Cardboard shelving units"],
        correctIndex: 1,
        explanation: "Storage requires wire shelving with impervious (solid) bottom shelves to prevent contamination from floor cleaning and spills.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss3",
        question: "A sterile pack has a small tear in the wrapper. Can it still be used?",
        options: ["Yes, if the inner contents look clean", "No, it must be reprocessed"],
        correctIndex: 1,
        explanation: "Any breach in sterile packaging compromises sterility. The item must be returned for reprocessing regardless of the contents' appearance.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss4",
        question: "How should sterile supplies be rotated?",
        options: ["Newest in front", "First in, first out (FIFO)", "Random order is fine", "By package size"],
        correctIndex: 1,
        explanation: "Sterile supplies must follow FIFO rotation: first in, first out. Newer items go to the back to ensure older stock is used first.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss5",
        question: "Under event-related sterility, when does a sterile package become non-sterile?",
        options: ["After a set expiration date", "When the packaging integrity is compromised", "After 30 days", "After 6 months"],
        correctIndex: 1,
        explanation: "Event-related sterility means items remain sterile until an event compromises the package (tear, moisture, contamination) - not based on time alone.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "ss6",
        question: "Is it acceptable to store sterile supplies within 18 inches of a sprinkler head?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Supplies must be stored at least 18 inches below sprinkler heads to ensure proper fire suppression coverage and prevent water damage.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "instruments",
    name: "Instrument Integrity",
    description: "Inspect instruments for damage, rust, and packaging issues in peel packs.",
    icon: "Wrench",
    color: "hsl(340, 82%, 50%)",
    requiredScore: 60,
    questions: [
      {
        id: "i1",
        question: "You notice orange staining on a surgical instrument in a peel pack. Should you use it?",
        options: ["Yes, it's just discoloration", "No, it indicates corrosion"],
        correctIndex: 1,
        explanation: "Orange staining indicates rust or corrosion. The instrument must be removed from service and inspected. Corroded instruments cannot be properly sterilized.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "i2",
        question: "How should instruments be positioned inside peel packs?",
        options: ["Closed/locked position", "Open position", "Any position is acceptable", "Wrapped in gauze"],
        correctIndex: 1,
        explanation: "Instruments in peel packs must be in the open position to allow sterilant contact with all surfaces, especially hinged areas.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i3",
        question: "You find frayed chemical indicator tape on a sterile package. Is this a concern?",
        options: ["Concern", "Not a Concern"],
        correctIndex: 0,
        explanation: "Frayed tape indicates the package seal may be compromised. The package should be inspected and potentially reprocessed.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "i4",
        question: "What does surface etching on a surgical instrument indicate?",
        options: ["Normal wear from sterilization", "Chemical damage requiring removal from service", "The instrument was recently sharpened", "It needs polishing"],
        correctIndex: 1,
        explanation: "Surface etching indicates chemical damage from improper cleaning solutions or processes. The instrument must be removed from service for evaluation.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "i5",
        question: "A single-use instrument is found to be manufactured in Pakistan with no FDA clearance markings. Can it be used?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Single-use instruments must have proper FDA clearance. Non-FDA-cleared instruments from any origin must not be used on patients.",
        xpReward: 20,
        isSwipe: true,
      },
      {
        id: "i6",
        question: "What should you check for when inspecting instrument peel packs?",
        options: [
          "Only the expiration date",
          "Seal integrity, indicator color change, instrument position, and package condition",
          "Just the chemical indicator",
          "Only whether it's the right instrument",
        ],
        correctIndex: 1,
        explanation: "Complete inspection includes: seal integrity, chemical indicator color change, instrument position (open), and overall package condition (no tears, moisture, or contamination).",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
  {
    id: "facilities",
    name: "Facilities & Equipment",
    description: "Ensure ice machines, refrigerators, sinks, and facility equipment meet compliance standards.",
    icon: "Thermometer",
    color: "hsl(195, 80%, 45%)",
    requiredScore: 60,
    questions: [
      {
        id: "f1",
        question: "Are ice machine temperature logs required to be maintained and current?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Ice machines must have current temperature logs to verify they are maintaining safe temperatures and preventing bacterial growth.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "f2",
        question: "You notice items stored in a handwashing sink. Is this acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Handwashing sinks must be kept clear of all items. They are designated solely for hand hygiene and cannot double as storage or cleaning stations.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "f3",
        question: "How often should medication refrigerator temperatures be checked?",
        options: ["Weekly", "Monthly", "Daily", "Only when adding new medications"],
        correctIndex: 2,
        explanation: "Medication refrigerator temperatures must be checked and logged daily to ensure medications are stored within the proper temperature range.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f4",
        question: "What should you do if a toilet in a patient bathroom is visibly soiled?",
        options: ["Ignore it, housekeeping will get it", "Report it immediately for cleaning", "Clean it yourself without proper supplies", "Close the bathroom door"],
        correctIndex: 1,
        explanation: "Soiled patient areas must be reported immediately for proper cleaning. This is both an infection prevention and patient dignity concern.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f5",
        question: "Can personal items (phones, keys) be placed on clinical surfaces?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Personal items should not be placed on clinical surfaces as they introduce outside contaminants to clean patient care areas.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "f6",
        question: "A shower in a patient room has visible mold. How urgent is this issue?",
        options: ["Low priority - schedule for next cleaning", "High priority - report and remediate immediately", "Medium - note for the next deep clean", "Not a concern if patient isn't using it"],
        correctIndex: 1,
        explanation: "Visible mold is a high-priority infection prevention concern. It must be reported and remediated immediately regardless of patient usage.",
        xpReward: 15,
        isSwipe: false,
      },
    ],
  },
];
