import type { Level } from "./schema";

export const levels: Level[] = [
  {
    id: "transport",
    name: "Transport of Instruments",
    description: "Master the proper handling and transport of surgical instruments from OR to sterile processing.",
    icon: "Truck",
    color: "hsl(152, 82%, 39%)",
    requiredScore: 0,
    studyMaterial: [
      {
        title: "Point-of-Use Cleaning",
        content: "Gross bioburden (blood, tissue, bone fragments) must be removed from instruments at the point of use before transport. This prevents organic material from drying on instruments, which makes later decontamination much harder. Use enzymatic spray or pre-soaking solution immediately after the case ends.",
        keyPoint: "Always remove gross bioburden at the point of use — don't wait for SPD.",
      },
      {
        title: "Instrument Positioning",
        content: "Before transport, all hinged instruments (scissors, clamps, hemostats) must be placed in the open/unhinged position. This allows cleaning solution to reach all surfaces, especially the box locks and jaw areas where bioburden accumulates. Heavy instruments go on the bottom of the tray.",
        keyPoint: "Instruments must be open/unhinged for transport — never locked or closed.",
      },
      {
        title: "Containment & PPE",
        content: "Soiled instruments must be transported in closed, leak-proof containers (red rigid bins with lids). The lid must be secured after applying enzymatic spray. Full PPE (gloves, gown, face shield/goggles, mask) must be available and worn when handling contaminated instruments.",
        keyPoint: "Lids must be secured before transport. Full PPE is required for handling soiled instruments.",
      },
      {
        title: "Transport Pathways",
        content: "Soiled instruments must travel through designated soiled corridors — never through clean cores or patient care areas. This prevents cross-contamination. Clean and soiled pathways should be clearly marked and separated.",
        keyPoint: "Never transport soiled instruments through clean areas.",
      },
      {
        title: "Soiled Utility Room Requirements",
        content: "The soiled utility room must have: pre-cleaner solution available, full PPE readily accessible, proper waste receptacles, and hand hygiene stations. Clean red bins/rigid containers with lids must be stored separately in the clean supply room when not in use.",
        keyPoint: "Clean bins go in the clean supply room. Soiled utility rooms must have PPE and pre-cleaner available.",
      },
    ],
    questions: [
      {
        id: "t1",
        question: "Where should clean red bins with lids be stored when not in use?",
        scenario: "You just finished a case and need to store equipment properly.",
        options: ["Soiled utility room", "Clean supply room", "OR hallway"],
        correctIndex: 1,
        explanation: "Clean red bins/rigid containers with lids must be stored in the clean supply room, never in soiled areas.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t2",
        question: "Should gross bioburden be removed from instruments at the point of use?",
        scenario: "A surgical case just ended. The scrub tech is handling used instruments.",
        options: ["Yes, always", "No, that's SPD's job"],
        correctIndex: 0,
        explanation: "Gross bioburden must be removed at the point of use to prevent drying and make decontamination more effective.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "t3",
        question: "How should instruments be positioned before transport to sterile processing?",
        options: ["Locked/closed position", "Open/unhinged position", "Stacked tightly", "Wrapped in drapes"],
        correctIndex: 1,
        explanation: "Instruments must be placed in the open/unhinged position before transport to ensure proper cleaning of all surfaces.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t4",
        question: "Is enzymatic spray applied correctly if a staff member uses it without gloves?",
        scenario: "You observe a colleague applying enzymatic pre-cleaner to instruments bare-handed.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Enzymatic spray must be applied with appropriate PPE including gloves. Chemical exposure without protection is a safety violation.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t5",
        question: "After applying enzymatic spray, what must happen to the instrument container?",
        options: ["Leave open for ventilation", "Secure the lid before transport", "Stack on top of other bins", "Label with patient info"],
        correctIndex: 1,
        explanation: "The lid must be secured before transporting to the soiled room to prevent contamination and splashing during transport.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t6",
        question: "Is it acceptable to transport soiled instruments through the clean core?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Soiled instruments must never be transported through clean areas. Designated soiled corridors prevent cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t7",
        question: "What PPE should be available in the soiled utility room?",
        options: ["Just gloves", "Gloves and face shield only", "Gloves, gown, face shield/goggles, and mask", "No PPE needed"],
        correctIndex: 2,
        explanation: "The soiled utility room must have full PPE available: gloves, gown, face shield or goggles, and a mask for safe handling of contaminated items.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t8",
        question: "Should pre-cleaner solution be available in the soiled utility room?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Pre-cleaner solution must be available in the soiled utility room for initial instrument decontamination before transport to SPD.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "t9",
        question: "A scrub tech leaves soiled instruments sitting for 2 hours before applying enzymatic spray. Is this acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Bioburden should never be allowed to dry on instruments. Enzymatic spray must be applied promptly at the point of use to prevent dried-on contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t10",
        question: "Where should heavy instruments be placed in the transport container?",
        options: ["On top of lighter instruments", "On the bottom of the tray", "In a separate container", "It doesn't matter"],
        correctIndex: 1,
        explanation: "Heavy instruments must go on the bottom of the tray to prevent damage to delicate instruments and ensure safe transport.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t11",
        question: "Is it compliant to transport instruments in an open container through the hallway?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Soiled instruments must always be transported in closed, leak-proof containers to prevent exposure and cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t12",
        question: "What is the primary reason for using enzymatic spray on instruments at the point of use?",
        options: ["To sterilize the instruments", "To prevent bioburden from drying on surfaces", "To disinfect the container", "To make instruments easier to count"],
        correctIndex: 1,
        explanation: "Enzymatic spray prevents bioburden from drying and hardening on instrument surfaces, making decontamination in SPD more effective.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "t13",
        question: "Can sharps and delicate instruments be mixed together loosely in the same transport bin?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Sharps and delicate instruments must be separated or protected to prevent injury during handling and damage to precision instruments.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "t14",
        question: "Who is responsible for ensuring instruments are properly prepared for transport after a case?",
        options: ["Only the surgeon", "Only the SPD tech", "The OR staff at the point of use", "Housekeeping"],
        correctIndex: 2,
        explanation: "OR staff at the point of use are responsible for point-of-use cleaning, positioning instruments open, and securing them for transport.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
  {
    id: "environment",
    name: "Environment & Surfaces",
    description: "Identify infection prevention issues related to walls, ceilings, and environmental surfaces.",
    icon: "Building2",
    color: "hsl(217, 91%, 52%)",
    requiredScore: 60,
    studyMaterial: [
      {
        title: "Wall & Surface Integrity",
        content: "All walls, countertops, and surfaces in clinical areas must be intact and impervious (able to be properly cleaned and disinfected). Tape residue, holes, cracks, and peeling paint create surfaces that cannot be effectively disinfected and may harbor pathogens. These must be reported immediately for proper repair.",
        keyPoint: "Surfaces must be intact and impervious — tape residue, holes, and cracks are all compliance issues.",
      },
      {
        title: "Ceiling Tiles",
        content: "Ceiling tiles in clinical areas must be intact, unstained, and properly seated in the grid. Cracked, stained, or damaged tiles can harbor mold, dust, and pathogens. Stained tiles often indicate water damage or leaks above, which is an even more serious concern. Missing or displaced tiles expose the plenum (space above) which is not clean.",
        keyPoint: "Stained ceiling tiles may indicate water damage. Damaged tiles must be reported immediately.",
      },
      {
        title: "Dust & Overhead Surfaces",
        content: "All overhead surfaces including lights, booms, shelves, vents, and equipment must be free of visible dust. Dust harbors microorganisms that can fall into sterile fields or wound sites. Regular cleaning schedules must include high-touch and overhead surfaces.",
        keyPoint: "Visible dust on overhead surfaces is never acceptable in clinical areas.",
      },
      {
        title: "Environmental Rounding (EOC)",
        content: "Environment of Care (EOC) rounds are regular inspections that check for infection prevention hazards. Items that get flagged include: tape residue on walls, dust on fixtures, damaged ceiling tiles, holes in walls/counters, and improperly stored supplies. Minor floor scuffs from normal wear are generally not flagged.",
        keyPoint: "EOC rounds focus on infection prevention hazards — not cosmetic wear like floor scuffs.",
      },
      {
        title: "Floor & Baseboard Requirements",
        content: "Floors must be clean and in good repair. Cove base (baseboards) must be intact and sealed to prevent moisture infiltration. Damaged cove base allows water and contaminants to seep behind walls, creating conditions for mold growth. Floors should be free of standing water.",
        keyPoint: "Intact cove base prevents moisture infiltration and mold. Damaged baseboards must be reported.",
      },
    ],
    questions: [
      {
        id: "e1",
        question: "You see tape residue on a wall in a patient care area. Is this compliant?",
        scenario: "During your rounds, you notice old tape marks and residue on the wall near a patient bed.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Areas must be free of visible tape and tape residue. This creates surfaces that cannot be properly cleaned and may harbor pathogens.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e2",
        question: "What should you do if you find a cracked ceiling tile in a procedure area?",
        options: ["Report it immediately", "Cover it with tape", "Ignore if small", "Paint over it"],
        correctIndex: 0,
        explanation: "Cracked or damaged ceiling tiles must be reported immediately. They can harbor mold, dust, and pathogens that could contaminate the sterile field.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "e3",
        question: "Is visible dust on overhead lights in a clinical area acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Overhead lights, booms, and carts must be free of visible dust. Dust can harbor microorganisms and fall into sterile fields.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e4",
        question: "You notice a small hole in the countertop of a medication prep area. What should happen?",
        options: ["Fill it with caulk yourself", "Report for proper repair", "Cover with contact paper", "It's fine if kept clean"],
        correctIndex: 1,
        explanation: "Countertops must be intact and impervious. Holes and cracks cannot be properly disinfected and must be professionally repaired.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "e5",
        question: "Are stained ceiling tiles in a sterile storage area a compliance concern?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Stained ceiling tiles may indicate water damage or leaks, which can lead to mold growth and contamination of stored sterile supplies.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "e6",
        question: "Which surface issue would NOT typically be flagged during an EOC round?",
        options: ["Tape residue on walls", "Dust on light fixtures", "Minor scuff marks on the floor", "Hole in the wall"],
        correctIndex: 2,
        explanation: "Minor floor scuffs are normal wear. Tape residue, dust accumulation, and wall damage are all infection prevention concerns.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "e7",
        question: "Peeling paint is observed on a wall in a patient room. Is this a compliance concern?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Peeling paint creates a surface that cannot be properly disinfected and may release particles. It must be reported and repaired.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e8",
        question: "What is the concern with a displaced or missing ceiling tile in a clinical area?",
        options: ["It looks unprofessional", "It exposes the unclean plenum space above", "It wastes energy", "It creates a noise issue"],
        correctIndex: 1,
        explanation: "Missing or displaced ceiling tiles expose the plenum (space above the ceiling), which contains dust, debris, and potentially mold that can contaminate the clinical environment.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "e9",
        question: "Is it acceptable to use tape to hang signs or reminders on walls in patient care areas?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Tape on walls creates residue that cannot be properly cleaned. Use approved bulletin boards or clip-on frames instead.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e10",
        question: "You notice damaged cove base (baseboard) in a procedure room. Why is this a concern?",
        options: ["It's just cosmetic", "It allows moisture to seep behind walls, promoting mold", "It's a trip hazard", "It affects room temperature"],
        correctIndex: 1,
        explanation: "Damaged cove base allows water from floor cleaning to infiltrate behind walls, creating conditions for mold growth and structural damage.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "e11",
        question: "Should dust on ventilation grilles in clinical areas be flagged during an environmental inspection?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Dusty ventilation grilles can distribute airborne contaminants throughout the clinical space. They must be cleaned regularly.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "e12",
        question: "What is the primary reason surfaces in clinical areas must be intact and impervious?",
        options: ["For aesthetics", "So they can be properly disinfected", "For sound insulation", "For temperature control"],
        correctIndex: 1,
        explanation: "Surfaces must be intact and impervious (non-porous) so they can be effectively cleaned and disinfected, preventing pathogen harborage.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "e13",
        question: "You find standing water on the floor near a sink in a procedure room. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Standing water is a slip hazard and a potential source of microbial growth. It must be cleaned up immediately and the source investigated.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "segregation",
    name: "Clean vs. Dirty",
    description: "Master the principles of clean and dirty segregation in clinical environments.",
    icon: "ArrowLeftRight",
    color: "hsl(270, 60%, 55%)",
    requiredScore: 60,
    studyMaterial: [
      {
        title: "Clean/Dirty Separation Principle",
        content: "The fundamental principle of infection prevention is that clean and soiled (dirty) items must be strictly separated at all times. This applies to storage rooms, sinks, transport paths, and workflows. Clean items must never pass through or be stored in soiled areas, and vice versa.",
        keyPoint: "Clean and soiled items must NEVER share the same space, sink, or transport path.",
      },
      {
        title: "Storage Requirements",
        content: "Nothing should be stored directly on the floor — all items must be on shelves or racks at least 6-8 inches off the floor. This allows proper floor cleaning underneath. Soiled linen goes in covered hampers in designated soiled areas. Clean linen must be stored in designated clean rooms or on covered carts.",
        keyPoint: "Nothing on the floor. 6-8 inches clearance required for proper cleaning.",
      },
      {
        title: "Sink Designation",
        content: "Sinks have designated purposes and cannot be used interchangeably. Handwashing sinks are only for hand hygiene. Instrument cleaning sinks are only for instruments. Clean and soiled items can never share the same sink, even if cleaned between uses.",
        keyPoint: "Sinks are designated for specific purposes — never mix clean and dirty in the same sink.",
      },
      {
        title: "Food & Beverage Restrictions",
        content: "Staff food and beverages are strictly prohibited in all clinical and patient care areas, including nurses' stations, medication rooms, and procedure areas. Food must be kept in designated break rooms only. Staff food can never be stored in clinical refrigerators (medication or specimen fridges).",
        keyPoint: "No food or drinks in clinical areas — period. Designated break rooms only.",
      },
      {
        title: "Utility Room Requirements",
        content: "Clean and soiled utility rooms serve different purposes and must be clearly designated. Clean utility rooms store clean supplies and patient care items. Soiled utility rooms handle contaminated items and waste. These rooms must never be used interchangeably, and doors should be kept closed.",
        keyPoint: "Clean and soiled utility rooms have distinct purposes and must never be mixed.",
      },
    ],
    questions: [
      {
        id: "s1",
        question: "Equipment is stored directly on the floor in the clean utility room. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Nothing should be stored on the floor. Items must be on shelves or racks at least 6-8 inches off the floor for proper cleaning.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "s2",
        question: "Where should soiled linen be stored?",
        options: ["In a covered hamper in a designated soiled area", "In the clean utility room in bags", "In any available room", "In the hallway near the exit"],
        correctIndex: 0,
        explanation: "Soiled linen must be in covered hampers in designated soiled areas to prevent cross-contamination with clean supplies.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s3",
        question: "Can clean and soiled items be processed in the same sink?",
        options: ["Yes, if cleaned between uses", "No, never"],
        correctIndex: 1,
        explanation: "Clean and soiled items must never share the same sink. Designated sinks prevent cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s4",
        question: "You see a staff member's lunch in the medication room refrigerator. Is this acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Staff food and beverages must never be stored in clinical areas or medication refrigerators. This is a serious contamination and food safety concern.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s5",
        question: "Clean linen should be stored in which of the following ways?",
        options: ["Open shelving in the hallway", "In a clean room or covered cart", "In the soiled utility room in bags", "Any location is fine"],
        correctIndex: 1,
        explanation: "Clean linen must be stored in a designated clean room or on a covered cart to prevent contamination from airborne particles.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s6",
        question: "Is it acceptable to have a staff coffee mug at the nurses' station in a patient care area?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Staff food and drinks are not permitted in clinical/patient care areas. They must be kept in designated break rooms.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "s7",
        question: "What is the minimum distance items should be stored off the floor?",
        options: ["2-3 inches", "6-8 inches", "12-18 inches", "No minimum required"],
        correctIndex: 1,
        explanation: "Items must be stored at least 6-8 inches off the floor to allow for proper floor cleaning and prevent contamination from mopping.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s8",
        question: "A nurse uses the handwashing sink to rinse a bedpan. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Handwashing sinks are designated solely for hand hygiene. Using them for cleaning equipment causes cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s9",
        question: "Where should patient care supplies be stored when a clean utility room is full?",
        options: ["In the soiled utility room temporarily", "In another designated clean area", "In the hallway on the floor", "In the patient's bathroom"],
        correctIndex: 1,
        explanation: "Patient care supplies must always be stored in designated clean areas. Soiled utility rooms, hallways, and bathrooms are never acceptable alternatives.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s10",
        question: "Is it acceptable to leave the soiled utility room door propped open?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Soiled utility room doors must be kept closed to prevent airborne contamination from spreading to clean areas and patient care spaces.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "s11",
        question: "A clean supply cart is parked in the hallway outside a patient's room with soiled linen bags nearby. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Clean supplies must be physically separated from soiled items. Proximity to soiled linen creates a cross-contamination risk.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "s12",
        question: "Which of the following items may be stored in a clean utility room?",
        options: ["Soiled linen hampers", "Patient care supplies and clean equipment", "Biohazard waste bags", "Used suction canisters"],
        correctIndex: 1,
        explanation: "Clean utility rooms are exclusively for storing patient care supplies and clean equipment. All soiled or contaminated items belong in the soiled utility room.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "s13",
        question: "Can personal water bottles be kept at the nurses' workstation?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "No food or beverages are permitted in clinical or patient care areas, including workstations. Staff must use designated break areas.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "sterile_storage",
    name: "Sterile Storage",
    description: "Learn the standards for proper sterile supply storage and event-related sterility.",
    icon: "Package",
    color: "hsl(32, 95%, 55%)",
    requiredScore: 60,
    studyMaterial: [
      {
        title: "Event-Related Sterility",
        content: "Modern sterility standards follow 'event-related' sterility, not time-based expiration. This means a properly packaged sterile item remains sterile until an EVENT compromises it — such as a tear, moisture exposure, contamination, or improper handling. There is no arbitrary expiration date; sterility depends on the integrity of the packaging.",
        keyPoint: "Sterile items remain sterile until an event compromises the package — not based on time.",
      },
      {
        title: "Shipping & Storage Containers",
        content: "Cardboard shipping boxes are never permitted in sterile storage areas. Cardboard sheds fibers, harbors dust, insects, and moisture, and cannot be properly cleaned. Items must be removed from shipping cartons and placed on appropriate shelving before entering sterile storage.",
        keyPoint: "No cardboard in sterile storage — ever. Remove items from shipping boxes.",
      },
      {
        title: "Shelving Requirements",
        content: "Sterile storage requires wire shelving with impervious (solid) bottom shelves to protect items from floor-level contamination. The bottom shelf must be at least 8-10 inches off the floor. Supplies must be stored at least 18 inches below sprinkler heads for fire safety. Items should not touch walls.",
        keyPoint: "Wire shelving with solid bottom shelf. 8-10 inches off floor, 18 inches below sprinklers.",
      },
      {
        title: "Package Inspection",
        content: "Before use, every sterile package must be inspected for: seal integrity (no tears or openings), chemical indicator color change (confirming sterilant exposure), moisture (wetness compromises sterility), and overall package condition. Any compromised package must be returned for reprocessing.",
        keyPoint: "Always inspect seal integrity, indicator color, moisture, and condition before use.",
      },
      {
        title: "Stock Rotation (FIFO)",
        content: "Sterile supplies must follow First In, First Out (FIFO) rotation. When new stock arrives, place it behind existing stock so older items are used first. While event-related sterility means items don't technically expire, FIFO ensures packaging integrity is maintained through regular turnover.",
        keyPoint: "First In, First Out — newer items go to the back of the shelf.",
      },
    ],
    questions: [
      {
        id: "ss1",
        question: "You find sterile supplies stored in their original cardboard shipping boxes. Is this compliant?",
        scenario: "During a supply room check, you notice boxes of sterile gloves still in their brown cardboard shipping containers on the shelf.",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Cardboard shipping boxes are not permitted in sterile storage areas. Cardboard harbors dust, insects, and cannot be properly cleaned.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss2",
        question: "What type of shelving is required for sterile supply storage?",
        options: ["Any shelving is fine", "Wire shelving with impervious bottom shelf", "Wood shelving", "Cardboard shelving units"],
        correctIndex: 1,
        explanation: "Storage requires wire shelving with impervious (solid) bottom shelves to prevent contamination from floor cleaning and spills.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss3",
        question: "A sterile pack has a small tear in the wrapper. Can it still be used?",
        options: ["Yes, if the inner contents look clean", "No, it must be reprocessed"],
        correctIndex: 1,
        explanation: "Any breach in sterile packaging compromises sterility. The item must be returned for reprocessing regardless of the contents' appearance.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss4",
        question: "How should sterile supplies be rotated?",
        options: ["Newest in front", "First in, first out (FIFO)", "Random order is fine", "By package size"],
        correctIndex: 1,
        explanation: "Sterile supplies must follow FIFO rotation: first in, first out. Newer items go to the back to ensure older stock is used first.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss5",
        question: "Under event-related sterility, when does a sterile package become non-sterile?",
        options: ["After a set expiration date", "When the packaging integrity is compromised", "After 30 days", "After 6 months"],
        correctIndex: 1,
        explanation: "Event-related sterility means items remain sterile until an event compromises the package (tear, moisture, contamination) — not based on time alone.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "ss6",
        question: "Is it acceptable to store sterile supplies within 18 inches of a sprinkler head?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Supplies must be stored at least 18 inches below sprinkler heads to ensure proper fire suppression coverage and prevent water damage.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "ss7",
        question: "You notice moisture on a sterile package in storage. Is it still considered sterile?",
        options: ["Yes, if it dries out", "No, moisture compromises sterility"],
        correctIndex: 1,
        explanation: "Moisture is a strike-through contamination event. Wet or damp sterile packages must be considered contaminated and reprocessed.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss8",
        question: "What is the minimum distance sterile items should be stored from the floor?",
        options: ["2-4 inches", "8-10 inches", "18 inches", "No minimum"],
        correctIndex: 1,
        explanation: "The bottom shelf must be at least 8-10 inches off the floor to protect sterile items from contamination during floor cleaning.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss9",
        question: "Is it acceptable for sterile packages to touch the wall in a storage room?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Sterile packages should not touch walls. Walls can transfer moisture, dust, and contaminants to packaging surfaces.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "ss10",
        question: "A chemical indicator inside a peel pack has NOT changed color. What does this mean?",
        options: ["The item is properly sterilized", "The item was not exposed to the sterilant and must not be used", "The indicator expired", "The indicator is cosmetic only"],
        correctIndex: 1,
        explanation: "An unchanged chemical indicator means the package was not properly exposed to the sterilization process. It must not be used and should be reported.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "ss11",
        question: "Can sterile supplies be stored in a room that has a leaking ceiling?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Sterile supplies must never be stored in areas with water leaks. Moisture compromises packaging integrity and creates conditions for microbial growth.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "ss12",
        question: "What should you do if you find a sterile item on the floor?",
        options: ["Pick it up and put it back on the shelf", "Inspect it and use if packaging looks intact", "Remove it from inventory for reprocessing", "Wipe it down and return to shelf"],
        correctIndex: 2,
        explanation: "Items that have fallen to the floor should be considered potentially compromised. They must be removed from inventory and evaluated for reprocessing.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "ss13",
        question: "Is dust accumulation on sterile packages a compliance concern?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Dust on sterile packages indicates inadequate environmental cleaning and can compromise packaging integrity over time. Storage areas must be kept clean.",
        xpReward: 10,
        isSwipe: true,
      },
    ],
  },
  {
    id: "instruments",
    name: "Instrument Integrity",
    description: "Inspect instruments for damage, rust, and packaging issues in peel packs.",
    icon: "Wrench",
    color: "hsl(340, 82%, 50%)",
    requiredScore: 60,
    studyMaterial: [
      {
        title: "Visual Inspection Basics",
        content: "Every instrument must be visually inspected before use. Look for: rust (orange/brown staining), corrosion, pitting, cracks, bent tips, dull cutting edges, and stiff joints. Instruments with any defects must be removed from service immediately. Never assume a defect is 'just cosmetic.'",
        keyPoint: "Always inspect for rust, corrosion, damage, and functionality before use.",
      },
      {
        title: "Rust & Corrosion",
        content: "Orange or brown staining on instruments indicates rust or corrosion. This means the instrument's protective finish is compromised and it cannot be properly sterilized. Corroded surfaces harbor bacteria in microscopic pits and crevices. These instruments must be immediately removed from service.",
        keyPoint: "Any orange/brown staining = rust. Remove from service immediately — it can't be sterilized.",
      },
      {
        title: "Surface Etching & Chemical Damage",
        content: "Surface etching appears as rough, dull, or frosted areas on instruments. It's caused by improper cleaning chemicals, wrong concentration, or prolonged exposure to harsh solutions. Etched surfaces cannot be properly sterilized because bacteria can hide in the microscopic irregularities.",
        keyPoint: "Etching = chemical damage. The instrument must be removed from service for evaluation.",
      },
      {
        title: "Peel Pack Inspection",
        content: "Before opening a peel pack, check: seal integrity (no peeling or gaps), chemical indicator color change (proves sterilant exposure), instrument position (must be open/unhinged), package condition (no tears, moisture, or contamination), and that the package is not compressed or crushed.",
        keyPoint: "Check seal, indicator, instrument position, and package condition before every use.",
      },
      {
        title: "Single-Use & FDA Compliance",
        content: "Single-use (disposable) instruments must have proper FDA clearance markings. Non-FDA-cleared instruments, regardless of country of origin, must never be used on patients. Single-use items must never be reprocessed or resterilized unless done by an FDA-registered third-party reprocessor.",
        keyPoint: "All instruments must be FDA-cleared. Single-use items cannot be reprocessed in-house.",
      },
    ],
    questions: [
      {
        id: "i1",
        question: "You notice orange staining on a surgical instrument in a peel pack. Should you use it?",
        options: ["Yes, it's just discoloration", "No, it indicates corrosion"],
        correctIndex: 1,
        explanation: "Orange staining indicates rust or corrosion. The instrument must be removed from service and inspected. Corroded instruments cannot be properly sterilized.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "i2",
        question: "How should instruments be positioned inside peel packs?",
        options: ["Closed/locked position", "Open position", "Any position is acceptable", "Wrapped in gauze"],
        correctIndex: 1,
        explanation: "Instruments in peel packs must be in the open position to allow sterilant contact with all surfaces, especially hinged areas.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i3",
        question: "You find frayed chemical indicator tape on a sterile package. Is this a concern?",
        options: ["Concern", "Not a Concern"],
        correctIndex: 0,
        explanation: "Frayed tape indicates the package seal may be compromised. The package should be inspected and potentially reprocessed.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "i4",
        question: "What does surface etching on a surgical instrument indicate?",
        options: ["Normal wear from sterilization", "Chemical damage requiring removal from service", "The instrument was recently sharpened", "It needs polishing"],
        correctIndex: 1,
        explanation: "Surface etching indicates chemical damage from improper cleaning solutions or processes. The instrument must be removed from service for evaluation.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "i5",
        question: "A single-use instrument is found to be manufactured in Pakistan with no FDA clearance markings. Can it be used?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Single-use instruments must have proper FDA clearance. Non-FDA-cleared instruments from any origin must not be used on patients.",
        xpReward: 20,
        isSwipe: true,
      },
      {
        id: "i6",
        question: "What should you check for when inspecting instrument peel packs?",
        options: [
          "Only the expiration date",
          "Seal integrity, indicator color change, instrument position, and package condition",
          "Just the chemical indicator",
          "Only whether it's the right instrument",
        ],
        correctIndex: 1,
        explanation: "Complete inspection includes: seal integrity, chemical indicator color change, instrument position (open), and overall package condition (no tears, moisture, or contamination).",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i7",
        question: "An instrument has visible pitting on its surface. Is it safe to use?",
        options: ["Safe", "Not Safe"],
        correctIndex: 1,
        explanation: "Pitting creates microscopic cavities that harbor bacteria and cannot be effectively sterilized. Pitted instruments must be removed from service.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "i8",
        question: "What causes 'stiff joints' in hinged instruments like hemostats?",
        options: ["Normal use over time", "Dried bioburden or inadequate lubrication", "Sterilization temperature", "Storage position"],
        correctIndex: 1,
        explanation: "Stiff joints are usually caused by dried-on bioburden in the box lock area or lack of proper lubrication. These instruments need evaluation and may need repair or removal.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i9",
        question: "Can a single-use instrument be resterilized and reused at your facility?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Single-use instruments must never be reprocessed in-house. Only FDA-registered third-party reprocessors are authorized to reprocess certain single-use devices.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "i10",
        question: "You notice a scissors has a bent tip. What should you do?",
        options: ["Use it carefully", "Straighten it yourself", "Remove it from service for repair", "Use it only for non-critical tasks"],
        correctIndex: 2,
        explanation: "Instruments with physical damage (bent tips, misaligned jaws) must be removed from service and sent for professional repair or replacement.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i11",
        question: "Is brown discoloration on the box lock area of a hemostat acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Brown discoloration in the box lock area often indicates trapped bioburden or early corrosion. The instrument needs thorough inspection and potentially reprocessing.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "i12",
        question: "What is the purpose of the chemical indicator inside a sterile pack?",
        options: ["To verify the package is sealed", "To confirm exposure to the sterilization process", "To show the expiration date", "To identify the instrument type"],
        correctIndex: 1,
        explanation: "Internal chemical indicators change color to confirm the contents were exposed to the sterilization process parameters (temperature, pressure, chemical exposure).",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "i13",
        question: "A peel pack appears crushed but the seal is intact. Is it safe to use?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Crushed packaging may have micro-tears not visible to the eye and the instrument inside may be damaged. The item should be inspected thoroughly and potentially reprocessed.",
        xpReward: 15,
        isSwipe: true,
      },
    ],
  },
  {
    id: "facilities",
    name: "Facilities & Equipment",
    description: "Ensure ice machines, refrigerators, sinks, and facility equipment meet compliance standards.",
    icon: "Thermometer",
    color: "hsl(195, 80%, 45%)",
    requiredScore: 60,
    studyMaterial: [
      {
        title: "Temperature Monitoring",
        content: "Medication refrigerators must have temperatures checked and logged daily (acceptable range: 36-46°F / 2-8°C). Ice machines require current temperature logs. Warming cabinets, blanket warmers, and any temperature-sensitive equipment must also have documented monitoring. Out-of-range temperatures must be reported immediately.",
        keyPoint: "Daily temperature checks are required for medication fridges, ice machines, and warming cabinets.",
      },
      {
        title: "Handwashing Sink Requirements",
        content: "Handwashing sinks must be kept clear of all items — no storage, no equipment rinsing, no food preparation. They must have soap, paper towels (not cloth), and be easily accessible. Splash guards or knee/foot pedals are preferred. Sinks must not be blocked by equipment or supplies.",
        keyPoint: "Handwashing sinks are for hand hygiene ONLY — keep them clear and fully stocked.",
      },
      {
        title: "Ice Machine Compliance",
        content: "Ice machines must have current cleaning logs showing regular maintenance. Ice scoops must be stored in a clean, designated holder — never left inside the ice bin resting on ice. Staff must use proper hand hygiene before handling ice scoops. Temperature monitoring must be documented.",
        keyPoint: "Ice scoops must be stored outside the ice bin. Cleaning logs must be current.",
      },
      {
        title: "Clinical Surface Restrictions",
        content: "Personal items (phones, keys, bags) should not be placed on clinical surfaces as they introduce outside contaminants. Clinical surfaces must be kept clean and uncluttered to allow proper disinfection. Only items needed for patient care should be on clinical work surfaces.",
        keyPoint: "Personal items don't belong on clinical surfaces. Keep work areas clean and uncluttered.",
      },
      {
        title: "Mold & Water Damage",
        content: "Visible mold anywhere in a patient care facility is a high-priority concern requiring immediate remediation. Common locations include shower stalls, window sills, and areas around plumbing. Water damage indicators (stained ceiling tiles, bubbling paint) must be investigated promptly as they create conditions for mold growth.",
        keyPoint: "Visible mold = immediate action required. Water damage must be investigated promptly.",
      },
    ],
    questions: [
      {
        id: "f1",
        question: "Are ice machine temperature logs required to be maintained and current?",
        options: ["Yes", "No"],
        correctIndex: 0,
        explanation: "Ice machines must have current temperature logs to verify they are maintaining safe temperatures and preventing bacterial growth.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "f2",
        question: "You notice items stored in a handwashing sink. Is this acceptable?",
        options: ["Acceptable", "Not Acceptable"],
        correctIndex: 1,
        explanation: "Handwashing sinks must be kept clear of all items. They are designated solely for hand hygiene and cannot double as storage or cleaning stations.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "f3",
        question: "How often should medication refrigerator temperatures be checked?",
        options: ["Weekly", "Monthly", "Daily", "Only when adding new medications"],
        correctIndex: 2,
        explanation: "Medication refrigerator temperatures must be checked and logged daily to ensure medications are stored within the proper temperature range.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f4",
        question: "What should you do if a toilet in a patient bathroom is visibly soiled?",
        options: ["Ignore it, housekeeping will get it", "Report it immediately for cleaning", "Clean it yourself without proper supplies", "Close the bathroom door"],
        correctIndex: 1,
        explanation: "Soiled patient areas must be reported immediately for proper cleaning. This is both an infection prevention and patient dignity concern.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f5",
        question: "Can personal items (phones, keys) be placed on clinical surfaces?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Personal items should not be placed on clinical surfaces as they introduce outside contaminants to clean patient care areas.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "f6",
        question: "A shower in a patient room has visible mold. How urgent is this issue?",
        options: ["Low priority - schedule for next cleaning", "High priority - report and remediate immediately", "Medium - note for the next deep clean", "Not a concern if patient isn't using it"],
        correctIndex: 1,
        explanation: "Visible mold is a high-priority infection prevention concern. It must be reported and remediated immediately regardless of patient usage.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "f7",
        question: "Is it compliant to leave the ice scoop resting inside the ice bin?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Ice scoops must be stored in a designated holder outside the ice bin. Leaving scoops in the bin introduces contamination from handling.",
        xpReward: 10,
        isSwipe: true,
      },
      {
        id: "f8",
        question: "What is the acceptable temperature range for a medication refrigerator?",
        options: ["28-35°F", "36-46°F (2-8°C)", "45-55°F", "Any temperature below 60°F"],
        correctIndex: 1,
        explanation: "Medication refrigerators must maintain temperatures between 36-46°F (2-8°C) to ensure medication efficacy and safety.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f9",
        question: "You find a cloth towel at a handwashing station instead of paper towels. Is this compliant?",
        options: ["Compliant", "Non-Compliant"],
        correctIndex: 1,
        explanation: "Handwashing stations in clinical areas must have paper towels (single-use). Cloth towels harbor bacteria and can spread contamination between users.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "f10",
        question: "Equipment is blocking access to a handwashing sink. Is this acceptable?",
        options: ["Acceptable if temporary", "Never acceptable"],
        correctIndex: 1,
        explanation: "Handwashing sinks must be easily accessible at all times. Blocking access impedes hand hygiene compliance, which is critical for infection prevention.",
        xpReward: 10,
        isSwipe: false,
      },
      {
        id: "f11",
        question: "A medication refrigerator shows an out-of-range temperature. What is the first step?",
        options: ["Wait and recheck in an hour", "Notify pharmacy/supervisor immediately", "Adjust the thermostat yourself", "Move medications to a regular fridge"],
        correctIndex: 1,
        explanation: "Out-of-range temperatures must be reported to pharmacy/supervisor immediately. They will determine if medications have been compromised and direct next steps.",
        xpReward: 15,
        isSwipe: false,
      },
      {
        id: "f12",
        question: "Is it acceptable to use a patient care sink for filling mop buckets?",
        options: ["Yes", "No"],
        correctIndex: 1,
        explanation: "Patient care sinks and handwashing sinks have designated purposes. Filling mop buckets requires a designated utility sink to prevent cross-contamination.",
        xpReward: 15,
        isSwipe: true,
      },
      {
        id: "f13",
        question: "Bubbling paint is found near a window in a patient room. Why should this be reported?",
        options: ["For cosmetic reasons", "It may indicate water intrusion and potential mold growth", "Paint fumes are toxic", "It's a fire hazard"],
        correctIndex: 1,
        explanation: "Bubbling paint often indicates moisture infiltration, which creates conditions for mold growth behind walls. This must be investigated and remediated promptly.",
        xpReward: 10,
        isSwipe: false,
      },
    ],
  },
];
